// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __AkCommunicationSettings_Il2CppStaticFields {
};

struct __AkCommunicationSettings_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _5_setCPtr;
  VirtualInvokeData _6_Dispose;
};

struct __AkCommunicationSettings_Il2CppClass {
  Il2CppClass_1 _1;
  __AkCommunicationSettings_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __AkCommunicationSettings_Il2CppVtbl vtbl;
};

class AkCommunicationSettings {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C4C998;
  static inline    __AkCommunicationSettings_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __AkCommunicationSettings_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__AkCommunicationSettings_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __AkCommunicationSettings_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t swigCPtr;
  bool swigCMemOwn;

  // Member methods:
  void ::ctor(intptr_t cPtr, bool cMemoryOwn) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, intptr_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1715ED0))(this, cPtr, cMemoryOwn);
  }
  void setCPtr(intptr_t cPtr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1715F70))(this, cPtr);
  }
  void Finalize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C370))(this);
  }
  void Dispose() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C3F0))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C600))(this);
  }
  void set_uPoolSize(uint32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C720))(this, value);
  }
  uint32_t get_uPoolSize() {
    return reinterpret_cast<uint32_t(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C850))(this);
  }
  void set_uDiscoveryBroadcastPort(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C970))(this, value);
  }
  uint16_t get_uDiscoveryBroadcastPort() {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251CAA0))(this);
  }
  void set_uCommandPort(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251CBC0))(this, value);
  }
  uint16_t get_uCommandPort() {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251CCF0))(this);
  }
  void set_uNotificationPort(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251CE10))(this, value);
  }
  uint16_t get_uNotificationPort() {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251CF40))(this);
  }
  void set_bInitSystemLib(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251D060))(this, value);
  }
  bool get_bInitSystemLib() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251D190))(this);
  }
  void set_szAppNetworkName(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251D2C0))(this, value);
  }
  System_String* get_szAppNetworkName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251D4C0))(this);
  }

  // Static methods:
  static inline intptr_t getCPtr(ModdingAPI::Exposed::AkCommunicationSettings* obj) {
    return reinterpret_cast<intptr_t(__fastcall*)(ModdingAPI::Exposed::AkCommunicationSettings*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x251C2E0))(obj);
  }
};
}