// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __CameraPathTiltList_Il2CppStaticFields {
};

struct __CameraPathTiltList_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Init;
  VirtualInvokeData _5_CleanUp;
  VirtualInvokeData _6_RecalculatePoints;
};

struct __CameraPathTiltList_Il2CppClass {
  Il2CppClass_1 _1;
  __CameraPathTiltList_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __CameraPathTiltList_Il2CppVtbl vtbl;
};

class CameraPathTiltList {
public:
  // Il2Cpp fields:
  __CameraPathTiltList_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* CameraPathPointList__points;
  ModdingAPI::Exposed::CameraPath* cameraPath;
  System_String* pointTypeName;
  bool initialised;
  int32_t interpolation;
  bool listEnabled;
  float autoSensitivity;

  // Member methods:
  void OnEnable() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B73A50))(this);
  }
  void Init(ModdingAPI::Exposed::CameraPath* _cameraPath) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, ModdingAPI::Exposed::CameraPath*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B748C0))(this, _cameraPath);
  }
  void CleanUp() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B74A60))(this);
  }
  ModdingAPI::Exposed::CameraPathTilt* get_Item(int32_t index) {
    return reinterpret_cast<ModdingAPI::Exposed::CameraPathTilt*(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B74BE0))(this, index);
  }
  void AddTilt(ModdingAPI::Exposed::CameraPathControlPoint* atPoint) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, ModdingAPI::Exposed::CameraPathControlPoint*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B74CC0))(this, atPoint);
  }
  ModdingAPI::Exposed::CameraPathTilt* AddTilt(ModdingAPI::Exposed::CameraPathControlPoint* curvePointA, ModdingAPI::Exposed::CameraPathControlPoint* curvePointB, float curvePercetage, float tilt) {
    return reinterpret_cast<ModdingAPI::Exposed::CameraPathTilt*(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, ModdingAPI::Exposed::CameraPathControlPoint*, ModdingAPI::Exposed::CameraPathControlPoint*, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B74E30))(this, curvePointA, curvePointB, curvePercetage, tilt);
  }
  float GetTilt(float percentage) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B74FE0))(this, percentage);
  }
  void AutoSetTilts() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B75170))(this);
  }
  void AutoSetTilt(ModdingAPI::Exposed::CameraPathTilt* point) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, ModdingAPI::Exposed::CameraPathTilt*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B75230))(this, point);
  }
  float LinearInterpolation(float percentage) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B75710))(this, percentage);
  }
  float SmoothStepInterpolation(float percentage) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B75950))(this, percentage);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::CameraPathTiltList*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B75BC0))(this);
  }
};
}