// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"


namespace ModdingAPI::Exposed {
struct __Campfire_Il2CppStaticFields {
  ModdingAPI::Exposed::CampfireSaveDataProxy* m_CampfireSaveDataProxy;
};

struct __Campfire_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __Campfire_Il2CppClass {
  Il2CppClass_1 _1;
  __Campfire_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Campfire_Il2CppVtbl vtbl;
};

class Campfire {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C24C80;
  static inline    __Campfire_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __Campfire_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__Campfire_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __Campfire_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::LocalizedString* m_LocalizedDisplayName;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_PlacedMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_LitMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_BurntMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_PlacementBlockColliderObj;
  ModdingAPI::Exposed::UnityEngine::Collider* m_RockRingCollider;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_RockRingParent;
  float m_RockOffsetFromGround;
  float m_RockMaxValidOffsetFromGround;
  System_String* m_PlaceAudio;
  bool m_BurnedOut;
  int32_t m_State;
  ModdingAPI::Exposed::Fire* m_Fire;
  bool m_IsBeingPlaced;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* m_RockPositions;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* m_PlacePointRocks;
  ModdingAPI::Exposed::UnityEngine::RaycastHit_array* m_RockRaycastResults;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_LastPosition;
  float m_LargestRockOffset;
  bool m_ValidatePlacePoints;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* m_ColliderLayerByTransform;

  // Member methods:
  System_String* get_m_DisplayName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15E35A0))(this);
  }
  void Awake() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B78C20))(this);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B78D00))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B791A0))(this);
  }
  System_String* Serialize() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B79E60))(this);
  }
  void Deserialize(System_String* text) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A170))(this, text);
  }
  bool CanFeedFire() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A670))(this);
  }
  bool IsBurnedOut() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A750))(this);
  }
  bool AreAnyRockOffsetsInvalid() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A760))(this);
  }
  float GetMinutesLeftToBurn() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A770))(this);
  }
  void SetState(int32_t state) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A850))(this, state);
  }
  bool TooWindyToStart() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7A970))(this);
  }
  void LaunchFireStartInterface() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7AB80))(this);
  }
  System_String* GetHoverText() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7ACD0))(this);
  }
  ModdingAPI::Exposed::Fire* GetFire() {
    return reinterpret_cast<ModdingAPI::Exposed::Fire*(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319930))(this);
  }
  void OnEnteredPlaceMesh() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7B1D0))(this);
  }
  void OnExitedPlaceMesh() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7B670))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Campfire*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7B950))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::CampfireSaveDataProxy*> m_CampfireSaveDataProxy = __CppStaticProperty<ModdingAPI::Exposed::CampfireSaveDataProxy*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_CampfireSaveDataProxy; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1B7BCC0))();
  }
};
}