// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"

namespace ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj {
struct __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppObject {
  uint16_t hKkVcCkhPduqnwDqFinitiARQdC;
  uint16_t dDSORkcNcYEFcWijOPpKUBEBmRu;
  uint16_t hhyTQvAlxrCWGTPuFyNHaaUzBNe;
  uint16_t IZRUARnWYxVtdoWTkudDVexQEsd;
  uint16_t FGZbXPEqkDomNBsFfeAzMhEhIxeA;
  uint16_t PnUbifzXZvACLdybBZwsAjHfrdi;
  uint16_t XaNQjEaIMyDtTNDisyHtiJhrHEn;
  uint16_t RxUuVfCMHXmtoAkuOEtxRbzVIQz;
};
struct __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppStaticFields {
};

struct __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppClass {
  Il2CppClass_1 _1;
  __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __dJePwHOWhFmOPldscjHiLUuIwhO_Il2CppVtbl vtbl;
};

class dJePwHOWhFmOPldscjHiLUuIwhO {
public:
  // Member fields:
  uint16_t hKkVcCkhPduqnwDqFinitiARQdC;
  uint16_t dDSORkcNcYEFcWijOPpKUBEBmRu;
  uint16_t hhyTQvAlxrCWGTPuFyNHaaUzBNe;
  uint16_t IZRUARnWYxVtdoWTkudDVexQEsd;
  uint16_t FGZbXPEqkDomNBsFfeAzMhEhIxeA;
  uint16_t PnUbifzXZvACLdybBZwsAjHfrdi;
  uint16_t XaNQjEaIMyDtTNDisyHtiJhrHEn;
  uint16_t RxUuVfCMHXmtoAkuOEtxRbzVIQz;

  // Member methods:
  uint16_t get_Usage() {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3500))(this);
  }
  void set_Usage(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3510))(this, value);
  }
  void set_Reserved1(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3530))(this, value);
  }
  void set_StringIndex(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3540))(this, value);
  }
  void set_Reserved2(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3550))(this, value);
  }
  void set_DesignatorIndex(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3560))(this, value);
  }
  void set_Reserved3(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3570))(this, value);
  }
  uint16_t get_DataIndex() {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5A50))(this);
  }
  void set_DataIndex(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3580))(this, value);
  }
  void set_Reserved4(uint16_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::DfEDoqobsGHkEFkVYccmnwCbZTj::dJePwHOWhFmOPldscjHiLUuIwhO*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3590))(this, value);
  }

};
}