// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Color.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector4.hpp"


namespace ModdingAPI::Exposed::EasyRoads3Dv3 {
struct __ERMesh_Il2CppStaticFields {
};

struct __ERMesh_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ERMesh_Il2CppClass {
  Il2CppClass_1 _1;
  __ERMesh_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ERMesh_Il2CppVtbl vtbl;
};

class ERMesh {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C66DC8;
  static inline    __ERMesh_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ERMesh_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ERMesh_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ERMesh_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecsInt;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* uv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* uv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* colors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* normals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* tangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* triangles;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startVecsInt;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startUv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startUv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startColors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startTangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startTriangles;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endVecsInt;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endUv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endUv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endColors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endTangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endTriangles;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* materials;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sColors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTriangles;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTerrainNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sVecsGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUvGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUv2Groups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sColorsGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sNormalsGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTangentsGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTrianglesGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTerrainNormalsGroups;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartUv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartUv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartColors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartTangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sStartTriangles;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndUv;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndUv2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndColors;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndNormals;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndTangents;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sEndTriangles;
  int32_t startEndVecCount;
  int32_t middleStartVecCount;
  int32_t middleEndVecCount;
  int32_t endStartVecCount;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndVecs;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startEndInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleStartInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleStartStartInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndEndInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endStartInts;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* startEndIntsNC;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleStartStartIntsNC;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleStartIntsNC;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndIntsNC;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndEndIntsNC;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* endStartIntsNC;
  int32_t ODODCOOOCDInt;
  int32_t OOOQOODOCDInt;
  int32_t middleLeftInt;
  int32_t middleRightInt;
  int32_t endLeftInt;
  int32_t endRightInt;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray1;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray1Group;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray2Group;
  int32_t vecCount;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValues;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValueVecIndexes;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValuesStart;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValueVecIndexesStart;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValuesEnd;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* zValueVecIndexesEnd;
  float minZ;
  float minMiddleZ;
  float maxZ;
  float maxMiddleZ;
  float totalZDistance;
  float offset1;
  float offset2;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* vertexBatches;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* triangleBatches;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::UnityEngine::GameObject* m_go, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject* soScript, float minZ, ModdingAPI::Exposed::UnityEngine::Transform* sourceTransform) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::UnityEngine::GameObject*, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject*, float, ModdingAPI::Exposed::UnityEngine::Transform*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x415620))(this, m_go, soScript, minZ, sourceTransform);
  }
  void GetMiddleSementInfo(ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecs, float minMiddleZ, float maxMiddleZ, ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleStartInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* middleEndInts) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float, float, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x422570))(this, vecs, minMiddleZ, maxMiddleZ, middleStartInts, middleEndInts);
  }
  void GetMiddleEdges(ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecs, float z, ModdingAPI::Exposed::System::Collections::Generic::List_T_* edgeInts) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x422700))(this, vecs, z, edgeInts);
  }
  bool ODDQCCDQCQ(ModdingAPI::Exposed::UnityEngine::Vector3 v, int32_t index, ModdingAPI::Exposed::System::Collections::Generic::List_T_* zV, ModdingAPI::Exposed::System::Collections::Generic::List_T_* zVIndexes) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::UnityEngine::Vector3, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4228E0))(this, v, index, zV, zVIndexes);
  }
  void ODDCQDDQQD(int32_t index, ModdingAPI::Exposed::UnityEngine::Vector3 v, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecsInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* uv, ModdingAPI::Exposed::System::Collections::Generic::List_T_* uv2, ModdingAPI::Exposed::System::Collections::Generic::List_T_* normals, ModdingAPI::Exposed::System::Collections::Generic::List_T_* colors, ModdingAPI::Exposed::System::Collections::Generic::List_T_* tangents, ModdingAPI::Exposed::UnityEngine::Vector2 sourceUv, ModdingAPI::Exposed::UnityEngine::Vector2 sourceUv2, ModdingAPI::Exposed::UnityEngine::Vector3 sourceNormal, ModdingAPI::Exposed::UnityEngine::Color sourceColor, ModdingAPI::Exposed::UnityEngine::Vector4 sourceTangent, int32_t tri) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Color, ModdingAPI::Exposed::UnityEngine::Vector4, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x422A90))(this, index, v, vecsInts, vecs, uv, uv2, normals, colors, tangents, sourceUv, sourceUv2, sourceNormal, sourceColor, sourceTangent, tri);
  }
  void OQDCQQQDDO(int32_t index, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecsInts) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x422E50))(this, index, vecsInts);
  }
  void InEdgePairArray(int32_t index1, int32_t index2, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecsInts) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, int32_t, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x422F80))(this, index1, index2, vecsInts);
  }
  void OODDQOCDOC(float adjustZ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x423120))(this, adjustZ);
  }
  void ODCDCQQOOO(ModdingAPI::Exposed::System::Collections::Generic::List_T_* groups, ModdingAPI::Exposed::System::Collections::Generic::List_T_* triInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* edgeInts) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4233D0))(this, groups, triInts, edgeInts);
  }
  void ODDCDCQQOC(ModdingAPI::Exposed::System::Collections::Generic::List_T_* edges, int32_t curInt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x424220))(this, edges, curInt);
  }
  bool ODOODDQQOD(ModdingAPI::Exposed::System::Collections::Generic::List_T_* edges, int32_t index, int32_t curInt) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4243B0))(this, edges, index, curInt);
  }
  bool OQDCQQQDDO(int32_t index, ModdingAPI::Exposed::System::Collections::Generic::List_T_* edgeInts) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4244C0))(this, index, edgeInts);
  }
  bool OCDOOQCQDC(ModdingAPI::Exposed::System::Collections::Generic::List_T_* edges, int32_t index1, int32_t index2) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x424590))(this, edges, index1, index2);
  }
  void MatchEdgePairs(ModdingAPI::Exposed::System::Collections::Generic::List_T_* startEdgePairs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endEdgePairs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startIntsNC, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endIntsNC, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startVecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endVecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startNormals, ModdingAPI::Exposed::System::Collections::Generic::List_T_* normals, int32_t ODODCOOOCDInt, int32_t OOOQOODOCDInt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x424700))(this, startEdgePairs, endEdgePairs, startInts, endInts, startIntsNC, endIntsNC, startVecs, endVecs, startNormals, normals, ODODCOOOCDInt, OOOQOODOCDInt);
  }
  void ODCQQQCQCQ(ModdingAPI::Exposed::System::Collections::Generic::List_T_* startGroups, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endGroups, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endInts, ModdingAPI::Exposed::System::Collections::Generic::List_T_* startVecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* endVecs) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x425D00))(this, startGroups, endGroups, startInts, endInts, startVecs, endVecs);
  }
  void OODOQQQCDD(ModdingAPI::Exposed::UnityEngine::GameObject* go, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject* so, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase* scr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::UnityEngine::GameObject*, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject*, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x427470))(this, go, so, scr);
  }
  void BuildMeshInstance(ModdingAPI::Exposed::UnityEngine::GameObject* go, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject* so, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase* scr, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sVecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUv, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sUv2, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sColors, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sNormals, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTangents, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTriangles, ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray1, ModdingAPI::Exposed::System::Collections::Generic::List_T_* normalArray2, ModdingAPI::Exposed::System::Collections::Generic::List_T_* materials, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sTerrainNormals) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::UnityEngine::GameObject*, ModdingAPI::Exposed::EasyRoads3Dv3::SideObject*, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x428DF0))(this, go, so, scr, sVecs, sUv, sUv2, sColors, sNormals, sTangents, sTriangles, normalArray1, normalArray2, materials, sTerrainNormals);
  }
  void OCDCDOOODQ(int32_t vecCount, ModdingAPI::Exposed::System::Collections::Generic::List_T_* intList, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecsList, float zValue) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x429CB0))(this, vecCount, intList, vecsList, zValue);
  }
  void OOQDDCCQCO(ModdingAPI::Exposed::System::Collections::Generic::List_T_* targetIntList, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sourceIntList, ModdingAPI::Exposed::System::Collections::Generic::List_T_* targetVecs, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sourceVecs) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x429EE0))(this, targetIntList, sourceIntList, targetVecs, sourceVecs);
  }
  void Clear() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERMesh*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x42A330))(this);
  }
};
}