// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::EasyRoads3Dv3 {
struct __ERRoundaboutsFunctions_Il2CppStaticFields {
};

struct __ERRoundaboutsFunctions_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ERRoundaboutsFunctions_Il2CppClass {
  Il2CppClass_1 _1;
  __ERRoundaboutsFunctions_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ERRoundaboutsFunctions_Il2CppVtbl vtbl;
};

class ERRoundaboutsFunctions {
public:
  // Il2Cpp fields:
  __ERRoundaboutsFunctions_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundaboutsFunctions*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }

  // Static methods:
  static inline void OOODCQOQOQ(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, int32_t currentIndex) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BABF0))(scr, currentIndex);
  }
  static inline void OCCDCCDCOO(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, int32_t currentIndex) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BB610))(scr, currentIndex);
  }
  static inline void OOOOOOOCDO(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, int32_t currentIndex) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BBDD0))(scr, currentIndex);
  }
  static inline void OOQODDCCCC(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecArray, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecArrayOther, ModdingAPI::Exposed::EasyRoads3Dv3::QDOQDSQOOQDDD* corner, int32_t startEnd, int32_t mainOrConnected, int32_t outerCornerInt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EasyRoads3Dv3::QDOQDSQOOQDDD*, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BCC60))(scr, vecArray, vecArrayOther, corner, startEnd, mainOrConnected, outerCornerInt);
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* OQQQDODQDO(ModdingAPI::Exposed::System::Collections::Generic::List_T_* outer, ModdingAPI::Exposed::System::Collections::Generic::List_T_* outerOther, float dist, float height, int32_t startend, int32_t leftright, int32_t outerCornerInt) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float, float, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BE650))(outer, outerOther, dist, height, startend, leftright, outerCornerInt);
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* ODCOQOOOCO(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, ModdingAPI::Exposed::System::Collections::Generic::List_T_* innerArray, ModdingAPI::Exposed::System::Collections::Generic::List_T_* outerOther, float dist, float height, float sidewalkWidth, int32_t startend, int32_t leftright, int32_t outerCornerInt) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float, float, float, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BEDB0))(scr, innerArray, outerOther, dist, height, sidewalkWidth, startend, leftright, outerCornerInt);
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* ODCQODDDQD(ModdingAPI::Exposed::System::Collections::Generic::List_T_* outer, float height) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BF480))(outer, height);
  }
  static inline void OQQCODQQCO(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecArray, ModdingAPI::Exposed::System::Collections::Generic::List_T_* uvArray, ModdingAPI::Exposed::EasyRoads3Dv3::QDOQDSQOOQDDD* corner, bool reverse) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EasyRoads3Dv3::QDOQDSQOOQDDD*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5BF790))(scr, vecArray, uvArray, corner, reverse);
  }
  static inline void ODQCQCDQQQ(ModdingAPI::Exposed::System::Collections::Generic::List_T_* vecArray, ModdingAPI::Exposed::System::Collections::Generic::List_T_* sidewalkUVs) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5C01E0))(vecArray, sidewalkUVs);
  }
  static inline void OCQCDODODO(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5C0720))(scr);
  }
  static inline void SetInnerSidewalkVars(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, int32_t preset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5C0C80))(scr, preset);
  }
  static inline void BuildInnerRoundaboutSidewalkData(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts* scr, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase* baseScr, ModdingAPI::Exposed::System::Collections::Generic::List_T_* mainRightPoints, ModdingAPI::Exposed::System::Collections::Generic::List_T_* innerRoundaboutSidewalkV3, ModdingAPI::Exposed::System::Collections::Generic::List_T_* innerRoundaboutSidewalUV, ModdingAPI::Exposed::System::Collections::Generic::List_T_* innerRoundaboutSidewalTris, int32_t innerSidewalkSegments) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EasyRoads3Dv3::ERRoundabouts*, ModdingAPI::Exposed::EasyRoads3Dv3::ERModularBase*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5C1210))(scr, baseScr, mainRightPoints, innerRoundaboutSidewalkV3, innerRoundaboutSidewalUV, innerRoundaboutSidewalTris, innerSidewalkSegments);
  }
};
}