// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __Encumber_Il2CppStaticFields {
  ModdingAPI::Exposed::EncumberSaveDataProxy* m_EncumberSaveDataProxy;
};

struct __Encumber_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __Encumber_Il2CppClass {
  Il2CppClass_1 _1;
  __Encumber_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Encumber_Il2CppVtbl vtbl;
};

class Encumber {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C909C8;
  static inline    __Encumber_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __Encumber_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__Encumber_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __Encumber_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  float m_MaxCarryCapacityKG;
  float m_MaxCarryCapacityWhenExhaustedKG;
  float m_ReduceCarryCapacityAtFatigue;
  float m_NoSprintCarryCapacityKG;
  float m_NoWalkCarryCapacityKG;
  float m_HourlyCalorieBurnPerKG;
  float m_EncumberLowThresholdKG;
  float m_EncumberMedThresholdKG;
  float m_EncumberHighThresholdKG;
  System_String* m_EncumberLowVoiceOver;
  System_String* m_EncumberMedVoiceOver;
  System_String* m_EncumberHighVoiceOver;
  float m_MinSecondsBetweenVoiceOverVariations;
  int32_t m_EcumberLevelForPreviousVoiceOver;
  float m_NumSecondsSinceLastVoiceOver;
  ModdingAPI::Exposed::CarryingCapacityBuff::BuffValues* m_CarryingCapacityBuffValues;
  float m_GearWeightKG;
  bool m_EncumberedInLog;
  bool m_StartHasBeenCalled;

  // Member methods:
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19465B0))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946820))(this);
  }
  System_String* Serialize() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946A50))(this);
  }
  void Deserialize(System_String* text) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946B70))(this, text);
  }
  float GetEncumbranceSlowdownMultiplier() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946C50))(this);
  }
  float GetHourlyCalorieBurnFromWeight() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946E20))(this);
  }
  bool IsCapacityBuffed() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946E30))(this);
  }
  bool IsEncumbered() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946EE0))(this);
  }
  bool IsEncumberedIgnoringPlaceMesh() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1946F10))(this);
  }
  float GetEffectiveCarryCapacityKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19470E0))(this);
  }
  System_String* GetPlayerCarryCapacityString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19473D0))(this);
  }
  System_String* GetCapacityString(float weightKG, float effectiveCapacityKG, float capacityKG, float capacityKGBuff) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Encumber*, float, float, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947520))(this, weightKG, effectiveCapacityKG, capacityKG, capacityKGBuff);
  }
  float GetGearWeightKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947D90))(this);
  }
  float GetMaxCarryCapacityKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947DA0))(this);
  }
  float GetMaxCarryCapacityWhenExhaustedKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947E60))(this);
  }
  float GetNoSprintCarryCapacityKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947F20))(this);
  }
  float GetNoWalkCarryCapacityKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1947FE0))(this);
  }
  float GetEncumberLowThresholdKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19480A0))(this);
  }
  float GetEncumberMedThresholdKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1948160))(this);
  }
  float GetEncumberHighThresholdKG() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1948220))(this);
  }
  bool ShouldPlayEncumbereVoiceOver() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19482E0))(this);
  }
  void MaybePlayerEncumberStatusVoiceOver() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1948320))(this);
  }
  int32_t GetEncumberLevel() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19484C0))(this);
  }
  void UpdateEncumberedStatusOnHUD() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19487A0))(this);
  }
  void MaybeUpdateEncumberedStatusInLog() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1949210))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Encumber*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::EncumberSaveDataProxy*> m_EncumberSaveDataProxy = __CppStaticProperty<ModdingAPI::Exposed::EncumberSaveDataProxy*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_EncumberSaveDataProxy; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x19492B0))();
  }
};
}