// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __EventDelegate_Il2CppStaticFields {
  int32_t s_Hash;
};

struct __EventDelegate_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __EventDelegate_Il2CppClass {
  Il2CppClass_1 _1;
  __EventDelegate_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __EventDelegate_Il2CppVtbl vtbl;
};

class EventDelegate {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C561E0;
  static inline    __EventDelegate_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __EventDelegate_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__EventDelegate_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __EventDelegate_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::UnityEngine::MonoBehaviour* mTarget;
  System_String* mMethodName;
  ModdingAPI::Exposed::EventDelegate::Parameter_array* mParameters;
  bool oneShot;
  ModdingAPI::Exposed::EventDelegate::Callback* mCachedCallback;
  bool mRawDelegate;
  bool mCached;
  ModdingAPI::Exposed::System::Reflection::MethodInfo* mMethod;
  ModdingAPI::Exposed::System::Reflection::ParameterInfo_array* mParameterInfos;
  ModdingAPI::Exposed::System::Object_array* mArgs;

  // Member methods:
  ModdingAPI::Exposed::UnityEngine::MonoBehaviour* get_target() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::MonoBehaviour*(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  void set_target(ModdingAPI::Exposed::UnityEngine::MonoBehaviour* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, ModdingAPI::Exposed::UnityEngine::MonoBehaviour*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19518E0))(this, value);
  }
  System_String* get_methodName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  void set_methodName(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951900))(this, value);
  }
  ModdingAPI::Exposed::EventDelegate::Parameter_array* get_parameters() {
    return reinterpret_cast<ModdingAPI::Exposed::EventDelegate::Parameter_array*(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951920))(this);
  }
  bool get_isValid() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951950))(this);
  }
  bool get_isEnabled() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951A50))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  void ::ctor(ModdingAPI::Exposed::EventDelegate::Callback* call) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951B80))(this, call);
  }
  void ::ctor(ModdingAPI::Exposed::UnityEngine::MonoBehaviour* target, System_String* methodName) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, ModdingAPI::Exposed::UnityEngine::MonoBehaviour*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951B90))(this, target, methodName);
  }
  bool Equals(Il2CppObject* obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951C50))(this, obj);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951ED0))(this);
  }
  void Set(ModdingAPI::Exposed::EventDelegate::Callback* call) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951F70))(this, call);
  }
  void Set(ModdingAPI::Exposed::UnityEngine::MonoBehaviour* target, System_String* methodName) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*, ModdingAPI::Exposed::UnityEngine::MonoBehaviour*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951B90))(this, target, methodName);
  }
  void Cache() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1952150))(this);
  }
  bool Execute() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1952A70))(this);
  }
  void Clear() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953390))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19533C0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<int32_t> s_Hash = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_Hash; }
  );

  // Static methods:
  static inline System_String* GetMethodName(ModdingAPI::Exposed::EventDelegate::Callback* callback) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951BC0))(callback);
  }
  static inline bool IsValid(ModdingAPI::Exposed::EventDelegate::Callback* callback) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1951C10))(callback);
  }
  static inline void Execute(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953560))(list);
  }
  static inline bool IsValid(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953700))(list);
  }
  static inline ModdingAPI::Exposed::EventDelegate* Set(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate::Callback* callback) {
    return reinterpret_cast<ModdingAPI::Exposed::EventDelegate*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19537F0))(list, callback);
  }
  static inline void Set(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate* del) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953990))(list, del);
  }
  static inline ModdingAPI::Exposed::EventDelegate* Add(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate::Callback* callback) {
    return reinterpret_cast<ModdingAPI::Exposed::EventDelegate*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953A50))(list, callback);
  }
  static inline ModdingAPI::Exposed::EventDelegate* Add(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate::Callback* callback, bool oneShot) {
    return reinterpret_cast<ModdingAPI::Exposed::EventDelegate*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate::Callback*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953B00))(list, callback, oneShot);
  }
  static inline void Add(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate* ev) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953D30))(list, ev);
  }
  static inline void Add(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate* ev, bool oneShot) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1953E00))(list, ev, oneShot);
  }
  static inline bool Remove(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate::Callback* callback) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate::Callback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19541B0))(list, callback);
  }
  static inline bool Remove(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list, ModdingAPI::Exposed::EventDelegate* ev) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::EventDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19542C0))(list, ev);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x19543D0))();
  }
};
}