// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"

namespace ModdingAPI::Exposed {
struct __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppObject {
  uint8_t ujxEOvEKFkYasTNlstZTJefcsoBa;
  char SzGxByCIiMEHuJLUQiYMKdlzaWRw;
  wchar_t cHsavhzIkNjzPCkqPBNNtiCypIzc;
  int16_t ZapBitbtLZAxIFINkkfjabpYsjv;
  uint16_t EnWkhTxfuKJEGDZourHprdqjpJx;
  int32_t fJKRBirWxtujMgVBhlRmmzgnfgq;
  uint32_t yjuyoXWbJQMErFwMgAEUHITbcKLJ;
  int64_t TjXHLARHBYgtUThLxcIWoNHCBNFE;
  uint64_t SVmDKqhJUWpCUaUhgBrtgCYHmvUZ;
  float gTAoElCLmVpNqgNPocTkegdbyvi;
  double hUyjfTWhJXQGgIUMoXTYarvvlWP;
  bool FDbwFgnESORqmXKvGXNQJjQCoQw;
};
struct __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppStaticFields {
};

struct __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppClass {
  Il2CppClass_1 _1;
  __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __FnmztnLddJqCqxGCEqqkXvzeimS_Il2CppVtbl vtbl;
};

class FnmztnLddJqCqxGCEqqkXvzeimS {
public:
  // Member fields:
  uint8_t ujxEOvEKFkYasTNlstZTJefcsoBa;
  char SzGxByCIiMEHuJLUQiYMKdlzaWRw;
  wchar_t cHsavhzIkNjzPCkqPBNNtiCypIzc;
  int16_t ZapBitbtLZAxIFINkkfjabpYsjv;
  uint16_t EnWkhTxfuKJEGDZourHprdqjpJx;
  int32_t fJKRBirWxtujMgVBhlRmmzgnfgq;
  uint32_t yjuyoXWbJQMErFwMgAEUHITbcKLJ;
  int64_t TjXHLARHBYgtUThLxcIWoNHCBNFE;
  uint64_t SVmDKqhJUWpCUaUhgBrtgCYHmvUZ;
  float gTAoElCLmVpNqgNPocTkegdbyvi;
  double hUyjfTWhJXQGgIUMoXTYarvvlWP;
  bool FDbwFgnESORqmXKvGXNQJjQCoQw;

  // Member methods:
  void ::ctor(uint8_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, uint8_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D140))(this, item);
  }
  void ::ctor(char item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, char)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D140))(this, item);
  }
  void ::ctor(wchar_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D150))(this, item);
  }
  void ::ctor(int16_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, int16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D150))(this, item);
  }
  void ::ctor(uint16_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D150))(this, item);
  }
  void ::ctor(int32_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D160))(this, item);
  }
  void ::ctor(uint32_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D160))(this, item);
  }
  void ::ctor(int64_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2C00))(this, item);
  }
  void ::ctor(uint64_t item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, uint64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2C00))(this, item);
  }
  void ::ctor(float item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D170))(this, item);
  }
  void ::ctor(double item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D180))(this, item);
  }
  void ::ctor(bool item) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FnmztnLddJqCqxGCEqqkXvzeimS*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D140))(this, item);
  }

};
}