// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Guid.hpp"
#include "ModdingAPI.Exposed.FYLzHqYGKVWoZLdqDNTOUcCJjse.uZJdHjcMsDcvWQDZlpRZEVOxuzeG.hpp"


namespace ModdingAPI::Exposed {
struct __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppStaticFields {
};

struct __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppClass {
  Il2CppClass_1 _1;
  __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppVtbl vtbl;
};

class FYLzHqYGKVWoZLdqDNTOUcCJjse {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C757D8;
  static inline    __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __FYLzHqYGKVWoZLdqDNTOUcCJjse_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* hUItqOVJotFHywXqZqyvDqbxAoI;
  ModdingAPI::Exposed::System::Guid oqwhnVfFGYmehgPpBjFKkfYabzC;
  int32_t ZfuMljoXhhqAdjaFNIAMdBcKBlCY;
  int32_t oaZiIiZeqOGqcKJGboJSaWkckG;
  int32_t QltCkXCWbvJhpqCPRTHThMAKGPQG;
  int32_t OlcUTFKxzgCgUHlOpuiPuoBNVxU;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Guid guid, int32_t offset, int32_t typeFlags, int32_t flags, int32_t instanceNumber) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, ModdingAPI::Exposed::System::Guid, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F7D0))(this, guid, offset, typeFlags, flags, instanceNumber);
  }
  System_String* get_Name() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  void set_Name(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30D060))(this, value);
  }
  ModdingAPI::Exposed::System::Guid get_Guid() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Guid(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F7F0))(this);
  }
  void set_Guid(ModdingAPI::Exposed::System::Guid value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, ModdingAPI::Exposed::System::Guid)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F800))(this, value);
  }
  int32_t get_Offset() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F810))(this);
  }
  void set_Offset(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x31DD50))(this, value);
  }
  int32_t get_TypeFlags() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F820))(this);
  }
  void set_TypeFlags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x31DD60))(this, value);
  }
  int32_t get_InstanceNumber() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D870))(this);
  }
  void set_InstanceNumber(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x31DD70))(this, value);
  }
  int32_t get_Flags() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D880))(this);
  }
  void set_Flags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D890))(this, value);
  }
  void SuVeWMvXMdajhaPUdFpFoMvRYpN(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse::uZJdHjcMsDcvWQDZlpRZEVOxuzeG ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse*, ModdingAPI::Exposed::FYLzHqYGKVWoZLdqDNTOUcCJjse::uZJdHjcMsDcvWQDZlpRZEVOxuzeG)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36F830))(this, );
  }
};
}