// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.yAJfKahKWfXKtBbzTwOyvCtiHBFm.hpp"

namespace ModdingAPI::Exposed::fzpgSVRENRUBXEAHfhvrXptZmJo {
struct __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppObject {
  ModdingAPI::Exposed::yAJfKahKWfXKtBbzTwOyvCtiHBFm haOinktFjwOUowkUTtBOeBvokgz;
  wchar_t gROcawtKZPaLXVlxAuQCQFetRSo;
  wchar_t mNBuitAHhOrJnJzfSOiteCIJfeP;
  wchar_t DvAGXhJQjLIcauRXggiguBQAbCfA;
  wchar_t mdRuVqKHdPYBpKQXCGctVzEFnfh;
  wchar_t VJuOLevNERCGkHFZEAEaOdQDKlS;
  wchar_t kMYkrvupJzEkYrzFOkXbJixEJXR;
  wchar_t tCIjWxcjxTQbtBeLfwYyCUEwiXGE;
  wchar_t BUwFYueSvgRATBDAUzOXnsgeRoip;
  wchar_t KWTDWhlsNTOPPoSFJlxchfXECLJ;
  wchar_t nXXXugmrdWdFpklqIBNVOqNOKiF;
  wchar_t mPIXBCCuDLWcVQaXJBqdRYUrBrT;
  wchar_t QuSCRARQDteCSskOgoNrDZPRWRs;
  wchar_t PbQtamyIwpAYpQFSlluweWBJssL;
  wchar_t fCYrOJBbajhUXEHHXyTdUArPZAKb;
  wchar_t SJiwdiTGDeIAfAjurAHCUyBtCUVB;
  wchar_t FqvqOAjNEfjUwhnCsrxiwyxlhtnK;
  wchar_t gctgNvFJSMSISSBtBCWcaeDfHrcF;
  wchar_t ZPGzXRkKAvZPWBkTUcBbSLOPWIX;
  wchar_t MWHCpLcCyroojaitPkjGoksgtbFk;
  wchar_t msyHrOYZkdlTefMWNFRUvyURCrZ;
  wchar_t DicCQsoaLnVAPXVOFlCnYhxpMEJ;
  wchar_t SVARywoAQdcdSircYlmImSlOvsj;
  wchar_t QIqaFKCNPtJiJevxZoAFqZmTbhZB;
  wchar_t mAWBeFntrHrrhevyakzDZgwLkqE;
  wchar_t yXJiBgJqRfmaSODXVSnjrNChYtz;
  wchar_t NlwdcMkrhnpbEbgPCjpMKpkcqtf;
  wchar_t DMLrDPnfIEyiDOknQJzyTXcgNrM;
  wchar_t aXnItINstfzxHDatjFCthGlGPzi;
  wchar_t PtYzvngxtYmeDqgTVEMgrSHQKrc;
  wchar_t TMxbSkJiasoyjcCxDhtUJsQJycbG;
  wchar_t vxhQjrhJrtqSXXkTkBrXFvDpCvf;
  wchar_t JMZsnkuTfHPfuDWDciBCYIDRqLZ;
  wchar_t AQycNiDQYkUHIXcXcYgOwHMzjGQ;
  wchar_t DQHgsiOtNYpeVpeYLDfgtwzlKKs;
  wchar_t doACRhngzwbQRIMQHjrhnQmsIScX;
  wchar_t zmImCacmzckprFmszecljFkjIgVe;
  wchar_t wHjDrlfnrZIfZxSUjRxKbLpOYTP;
  wchar_t xfqdCGjhQIwhxPJPnFCjVVhGahK;
  wchar_t unkHbtqwMkdQnUrEQyaePRCbSQi;
  wchar_t kkhdCwHhwijXsHALdCZlnyNvreKq;
  wchar_t WXkCjBUUopGMIgAFqZcnOFErnMJ;
  wchar_t XogiAwuZEYhaQcyBsOJuXsLHYeu;
  wchar_t CRlvnYzbFFmQPXzAcUVCcJSeHEL;
  wchar_t MKgaMFHsLpfZfbzHgmmCYDgZDpS;
  wchar_t nnDvxcFDcCTTnfQSavvUlffOeoCf;
  wchar_t hcCrPyLUfCcMFUyZCtXSZxyaPNc;
  wchar_t vBtbvFDTjvgFaqytPMTYoiZBJhnA;
  wchar_t BgxrtWnOtiUbEjeLbWMfdvdHFpb;
  wchar_t HSKqtHSifdOxxSkmSromjTMTWht;
  wchar_t xChGiephSJxNTcvhVNmaWhpZhwm;
  wchar_t sESbEdhoshgVxAFqkjdFMMbcIphf;
  wchar_t OPgbHNtotcUNBvBIlTiCobqvLzh;
  wchar_t uPCeWmimvvtfdAGEgbEAjofhWaTk;
  wchar_t NZMfGgEvZDDMMwPDToeSdIumFLG;
  wchar_t HpZMtfkUDpobXVLfyITaEYzoAVo;
  wchar_t KXoDhuGPKDOBtcOoTwNNWtODYlg;
  wchar_t qdvxMkxztcYKAhhqUekHanqhsuU;
  wchar_t QqaAxACqHuWdiOEDBqXrTXdepgC;
  wchar_t TDrweEInRjyTZUFObjprxemcubz;
  wchar_t qfbfHTFIlFChYmMOCTvgePDLZp;
  wchar_t KJTCmdjyyCOcYLIawIBQjpDxpoPJ;
  wchar_t UQWTcinrRPWuxoQwyEwEYyVhxUj;
  wchar_t wkgksyvpYiGxsEZwQiCKkMrQSuMm;
  wchar_t JiqIbdnAaMCDBZKZXPmcYetmXMp;
  wchar_t PttBhepAbkhrFonAEANQplZFKjT;
  wchar_t zHDbgIehjJKJHpvEIdbVkOrEquFj;
  wchar_t NrxcBqisqGIjOAqUKJWgnbnTujDI;
  wchar_t tWpRMqdaQWKQcaotljzYemmyVjG;
  wchar_t WmvgwHWlCVbLdjviANqfoInwKotD;
  wchar_t FEfizfNJBNNwYuMjTwmceViMpZN;
  wchar_t PCjKJQXztHJpDlzoBVYMrNfXgeU;
  wchar_t WkQAhwFrocUjxVAGjQbSwDLLLUFp;
  wchar_t NNblXaUUlozLprvcVlAWmDdbJcg;
  wchar_t ROyuNHyakzeKhAczedeKWpCUaIr;
  wchar_t dqnRIpixrCjdWjsEpcuAtkuqsvy;
  wchar_t fAFEWohDuKwTAFxuNYadzdYncEHd;
  wchar_t aTkFGoBXqvwFrWaDFumxiRCIUEY;
  wchar_t sghvgPHDmBOnYegmfDSbftrjmitp;
  wchar_t hNycxNdQKAepwRtZkUKBfpGNmUvd;
  wchar_t YxmeOZgJOtakNVpZHdZjqinlufv;
  wchar_t ItcUfXxVvEeqjGOOXbxnABKQRQK;
  wchar_t ZHVayAOlmUHUWwbjygZfPwoJkjQ;
  wchar_t bCVkdtqTUVDvTxvAdsPNcAPOHQjF;
  wchar_t foVlOFqeFKhieyPGkLSxTTuxSwf;
  wchar_t HBxCWcWksshpMiKfywVTtquKDUt;
  wchar_t tBoOzUyqyveYNKJvfBBSSwoREZ;
  wchar_t sxIssqqXlNhddVrqPbVQirYqUxEO;
  wchar_t zckRBZssmpMvcVjzRNSebprkBdI;
  wchar_t IeUnSxgGGxUYXuVBCZFeGHGFTVv;
  wchar_t yJQmkPUEgIOfKGyCcDDGbTrgSTP;
  wchar_t EydrgrRLBLHpIhrPWsPPprjMnri;
  wchar_t hdvwrdVJUypOFMgurFFBubgXSKf;
  wchar_t VhaQbAntFJbdssssnnZIHxIOLHW;
  wchar_t UbXcVUPHiRRbKOMATfeeRwUgRjO;
  wchar_t PdWBWoGcHEdeUhhGKRSEpDmEKv;
  wchar_t eVRvONimXcyFfDTZmtcGmvmsmdv;
  wchar_t iHWhRWfusHJebBBYtKJviueDzmp;
  wchar_t kPslafaJBeXpkQSQSdeGvnTQbnBb;
  wchar_t ezbSMIECJEhqsbloFBfStWbgAEgx;
  wchar_t RmMuWdrUEboijKIeRgHrcJTdLjnu;
  wchar_t GxfzvYBzIPGDZGpkzgedcmXfjgle;
  wchar_t aAgGuaxGnKcLiieghbSQmtkQNPK;
  wchar_t wpWZPJdHdmKUKxXPGmfYEpzYFiob;
  wchar_t UxegAQYVHiePZPxfAJbcUkTldqo;
  wchar_t AgXJEMhPLHtPGrFHYHARKfowvZih;
  wchar_t xdwdFVVcDLAIXrssIwzqTJsWRwP;
  wchar_t yArTSmnJrmHRSoSBHlMiKfoRVSu;
  wchar_t fWxHKwQbNXZsBDwHSIbYqkAJQOG;
  wchar_t BAThQWfCWzkVhDfcgsUVAETRwqZJ;
  wchar_t pVwrQymkIbeyLWTLGAacROvsfLnC;
  wchar_t iyBPHbKAnnnHGZhntKxnMkVREri;
  wchar_t mIDsQvjGYsjQiutArwciuFVruOf;
  wchar_t YzLdycXhjxzJHyaxMFndjpKqTAo;
  wchar_t UdTOcMyiYhubPCOBkbKlvuBiXWF;
  wchar_t oNEUZMajeTQWRZNrHdggGNbOjlOj;
  wchar_t YWBsSgWBSZfjZFjwFCRuQafCjgaX;
  wchar_t veEUqUCERGAgfdnMaqQnLuUdemb;
  wchar_t CLFkltrwUkUWsiLbbswmyKQgPtI;
  wchar_t bKTfoxJqdYqTYlIehOZcNZypRgF;
  wchar_t DIzKsLOnyrlmtEerZuizYitBfHu;
  wchar_t FkmfcngqatZJUlokiFthPwnhOujH;
  wchar_t TabpYBBOOjwkZzrYzRnKHfFNicf;
  wchar_t KXaAnNaSFbVpBeFfJnGVagpycBRk;
  wchar_t TjwXvCahLNFiFxlxnnAutWDBSAI;
  wchar_t iwQGynwREUMrOiVPWdfmylTWQWd;
  wchar_t trCMtXYTveMOBUanFPujjLfGZFH;
  wchar_t xlAOrEzQFdLNNDgRIsmdZJGUIpCh;
  wchar_t vndqEaptxhuUbcfoMNKNFZhnWip;
  wchar_t kngUNtMRqggTKhEcXDEwkyQgCfFi;
  wchar_t IqWPcbUzctBvjPEkMBJFbmjSNePE;
  wchar_t jMXfEOHmqsCEIBHpqblGuHUJymO;
  wchar_t bTMwZPyxvgCjtsbIvgCGhphCsPwh;
  wchar_t LMhCudyHhSCbAekbjHhFeOUfQlQg;
  wchar_t MNdNZoiCEFvchMYxceUsPMLLsPC;
  wchar_t fQzUSjzGcsvqjAighDcdBRTASnt;
  wchar_t ENIbNqBcZSLLaHyKhbzZOIiprEme;
  wchar_t CiKcNuIFFYnDREgdiKjFSbamSrax;
  wchar_t SOiMXyGQMVSGEJwmSuMUKfHCkUH;
  wchar_t QzRYhiuWbKPNUAEODgJzDAsaGGfz;
  wchar_t IQKHIGbXIESvoJeOWncWzNrpfCA;
  wchar_t urowYSLAIONXSmnzHkAOSBRuvrs;
  wchar_t MqFGMUBmYlqQfAAKfNQwFpSBfZDi;
  wchar_t TMhMORsjbAZXyOAYDLFZrxPkRhj;
  wchar_t bljFEFeuPWpHjCpCFYmGktcdGUR;
  wchar_t aNVdfLEsZDaBDFMVAnrmmsoOGULd;
  wchar_t wrQVmmYkTZTpWwNHZOlCTfTrDBvh;
  wchar_t xxtxHVeMhbrTMfFtVBnxHCVvIlRz;
  wchar_t gMJYHNMqlfIdnFmjdKIcTZlLrgO;
  wchar_t EtjwwwCbZqCqUGIoeCFsGGEAIsdQ;
  wchar_t uXIRHhpfkXiVlKRumlXxTuGegoO;
  wchar_t ntZfaUDshuPHtESNcaEuwXfkmsMz;
  wchar_t lNrXABqCfxukZJUepWyXIoxMVY;
  wchar_t HxEgfEccqEHNBfpJNncCbEWDFLmm;
  wchar_t ZnXKrBYcEDYBSAIIetHhOndMWDA;
  wchar_t lNEAWnOkbAvuoBgKGWSkSvTdFBI;
  wchar_t seHTGYlOEyHFUHyckmEjfbrNjxGm;
  wchar_t lsMaLkbUzteerEOVRMNtpFmdoIlH;
  wchar_t WIJEbCJTRXPzBRkZllilnWjHmvC;
  wchar_t MXIskweEITyWIzDLVZbnnXYIkOu;
  wchar_t xTvFfEoljRATagCppYdXwrOHbUp;
  wchar_t FkKeHxMhtDhbAkUwbNtXnHTrWzYE;
  wchar_t ZxQCRnJLguXYsbnnykToolFeQvVU;
  wchar_t TVOUrdafcmfNpdofQIyCtvrbZmdW;
  wchar_t MhmGBVSrNkUAICeihHSoBhXWMgOd;
  wchar_t gzzGEzJSBhovvjWTVYhoQgVXKxfX;
  wchar_t zhzoTMBPaChwZqOscYAVhIFbPCK;
  wchar_t mZaMiVdkOHHSciLDLrLZLfaoyrQ;
  wchar_t ZovIWCiDOpzfIWpeIMZrqpsxnzz;
  wchar_t GeIOTvDnphprqBbFzozWYXbBOfS;
  wchar_t tUKAyHCJcNlLiUfmtVuGgTuLHAU;
  wchar_t GsIAzQmaCJBubbspKXfyBBdKcgF;
  wchar_t XhIiFsYNYtzioigfEbhiHgwgBWUP;
  wchar_t sEBirakWdWAchciMefepcvZtwfEL;
  wchar_t KKUTyLgVaEpnNFAeezteiYKxkGA;
  wchar_t RFHqewxxKBRwwXJnHneuvCLruws;
  wchar_t hnNSylUtuzgkGLjjyfNoQnqzymk;
  wchar_t mFuBVMHRhzJlFjxgiqgIiGeIuomr;
  wchar_t dQklpZzhdbEnRLxAvFgJGDbfjdzG;
  wchar_t CZzftMBWujfuqVrHaIwaDNJfoFhV;
  wchar_t SjWBxTCgfncnUfFjHIPbrZhnLDAA;
  wchar_t svGfecZqKiDqgHhFLTaqkgDTFwm;
  wchar_t vBFfRgywbvfiSfGfqvfxahDswsfU;
  wchar_t BTAEWqyZteSBTEIIVDMKNLqlaqY;
  wchar_t ZmrGoTrkZePhcIRKgXXhEiUSeXk;
  wchar_t PqqZWFcZhsPZuoeNthXKUnwgfxR;
  wchar_t BoWAQHBxlyFxzLXlKZsVilWvGUYF;
  wchar_t sNAFAiEGLGzUVYQDRYHfPHnQcPTE;
  wchar_t pYrIrGmcQKnkFlDcmSIVyARueXb;
  wchar_t iusGVBxKYZnlpKUVZgOcRtgNEoj;
  wchar_t UpFPJWWwbKUTUdaPxHbaEmVGcRcJ;
  wchar_t AfXUKZQxOEpkRqcguivmIrLZFYn;
  wchar_t AFQltTDMAplkaZqzhznQEDevjIG;
  wchar_t wLFcRYaQeoMdDvPlwtUZXkJXlVG;
  wchar_t qPKnCFWayWGtxkjESAOaSoIEgiuf;
  wchar_t frqGiXCvRwhXzcrMkMcpRMDdGzMs;
  wchar_t svLQpPgKyuGTzTsSwfELJnHsrIwA;
  wchar_t NBBXDlyKsDiPQIyuyLKHflMPtSd;
  wchar_t UIOqbScuqQpCbpFHiSWqoethltB;
  wchar_t ALJdovHuXrUrUpJjdnnMioCOOxX;
  wchar_t kFMYdYZpKGpNEAhCcikcSEfLuUP;
  wchar_t JmxIotnSZvleGfSQSTeCIgQfOEv;
  wchar_t BIaccGRwFfYEhOPXYgAwTgNHmyv;
  wchar_t AwjpwPNdysDjHZphjbtHhFydRwn;
  wchar_t uhopOlGjznBcolPhiedoFUskBgKo;
  wchar_t CiktokFCeYXMLqcaHwEAjxGjMxr;
  wchar_t MLJMqonaLcbsRIJbwOXaYcsfLFB;
  wchar_t yaXKYqpCXhVbmDrNkupVUGxXygq;
  wchar_t uDjhfRKHRUuYZlxFqdlaLpAJEco;
  wchar_t gdmCMmwWtsdhuftQjOOALVjBWkl;
  wchar_t SKNgXQDVFNuuHPKrzojktRbBSV;
  wchar_t yMWTjfWtUaxGCUrGJPAdaimRwog;
  wchar_t MCOEPwbWsxnVHGSUuSzxqRqnuJZ;
  wchar_t frZHUxheWDiKzRyIqrOGREDRvCR;
  wchar_t PJSEfxpFNwbdLnhgdVrkMkpeFQn;
  wchar_t sZgvaHCKjUikAdxmvvbPPaMCgEk;
  wchar_t FwuFIMZJhDPhuLuXpUgNTkbuMow;
  wchar_t nlpIUCXLaawwzWpWlhJACrkZDaK;
  wchar_t CyjUqUflPjEeOlHYMdaUUaHUBTj;
  wchar_t mRSQGTjZxxMPPlhEgVNxOdOjyEZ;
  wchar_t TVjGRTitqtYgtlIpOeWALcAnOWKR;
  wchar_t nDEFzAPJrpnjJaTZigTYVSMBCLC;
  wchar_t GGwGQCETpzhNEQbeUZOntmRlifEg;
  wchar_t oSfJAfndNCwEGmYzrYNBywwPgBi;
  wchar_t croCMzTAFkADAFJMGpNlIVzRnGl;
  wchar_t WVxbcXijhjenQilfKyybbQpcrKmL;
  wchar_t uZFahQdfbJtjDZKoShHlvmredcFb;
  wchar_t CxHvuyjveHWOXVdlqCdPYCHGilUD;
  wchar_t QdnHNfbcqGAQRzwOXwHeZFKBikH;
  wchar_t PyyeeLSalTzzLcLVGaUGBbiAVrp;
  wchar_t JkIVsiMxmMNfYwIzTdMbDGROCiO;
  wchar_t wOCEIfVtIwBUEEpKzrWDBfYZfdn;
  wchar_t aEnRQLKGZhJUZSotSftrTVoEidA;
  wchar_t XIOnMFaKzgRnnECtlAgazrgcTP;
  wchar_t YKXxkhRGZzzUwoaULPHWdoIdoNH;
  wchar_t uJKRyCRDghXTchEUZElrJfHRTCtJ;
  wchar_t zCLFERDXoneehyAOredVdmWBLrVe;
  wchar_t vxlbxnAlCPHiGikWzxsmMJetFAzt;
  wchar_t SVrbudeLKZOIXCnymGMleKPhnauq;
  wchar_t oAlhxQGumTgjheiTEkeEvNqiDJnP;
  wchar_t dFxPHNRovjfyVJkPiEFVHjuZeloX;
  wchar_t SfZvVRtNbDWCkSGoOqNRczaMCnW;
  wchar_t MBnDShrWDJnkzDcLBngiwoQoIEg;
  wchar_t gJrVFBikYHfacBjchKOebhuSKHOo;
  wchar_t SqfZkgsYGtsMjLtkLUWKCOJFVPK;
  wchar_t DZgnJLYzqkotEjvoEbRRSkIytda;
  wchar_t TSmqcBBKoOBUEOSZPcJwiPSHIFHV;
  wchar_t gQjUBOddXGwpubImYPBYEQlbaDn;
  wchar_t uFnoldiedCjjVlnybLkiSjubGcm;
  wchar_t ekuLpvfbEBuvjvvqZnErpkHZdyD;
  wchar_t ysFUskLYiwWKSDxUfbcfmYOgint;
  wchar_t JBzNgbcDwlGwOyZdxWclqkEFLkk;
  wchar_t GWcUuMjNoAJtBsfdhhgPnAiemBy;
  wchar_t hshgCqQlTzzLdrQGCYEhUInVDUs;
  wchar_t XlzOObGrfOMoERmFUFSZuJZCWgI;
  wchar_t LIFZquiCdvucVTRGrBLyigfuewtA;
  wchar_t lPCFGHEyuaiUGqvKndXfLkblSVes;
  wchar_t wVvcathpzHAQiPnztvPMcHTdhPW;
  wchar_t rEHQDwrYyAkFObogPIVehJCUMph;
  wchar_t IDyiXpFPXWHyKyfAWyXxGrJkJJl;
  wchar_t HatnkXzFUICRbTGPsKHvLZgtrVD;
};
struct __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppStaticFields {
};

struct __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppClass {
  Il2CppClass_1 _1;
  __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __DVGhYieYaAVEsDSJjUnnMyFiKjy_Il2CppVtbl vtbl;
};

class DVGhYieYaAVEsDSJjUnnMyFiKjy {
public:
  // Member fields:
  ModdingAPI::Exposed::yAJfKahKWfXKtBbzTwOyvCtiHBFm haOinktFjwOUowkUTtBOeBvokgz;
  wchar_t gROcawtKZPaLXVlxAuQCQFetRSo;
  wchar_t mNBuitAHhOrJnJzfSOiteCIJfeP;
  wchar_t DvAGXhJQjLIcauRXggiguBQAbCfA;
  wchar_t mdRuVqKHdPYBpKQXCGctVzEFnfh;
  wchar_t VJuOLevNERCGkHFZEAEaOdQDKlS;
  wchar_t kMYkrvupJzEkYrzFOkXbJixEJXR;
  wchar_t tCIjWxcjxTQbtBeLfwYyCUEwiXGE;
  wchar_t BUwFYueSvgRATBDAUzOXnsgeRoip;
  wchar_t KWTDWhlsNTOPPoSFJlxchfXECLJ;
  wchar_t nXXXugmrdWdFpklqIBNVOqNOKiF;
  wchar_t mPIXBCCuDLWcVQaXJBqdRYUrBrT;
  wchar_t QuSCRARQDteCSskOgoNrDZPRWRs;
  wchar_t PbQtamyIwpAYpQFSlluweWBJssL;
  wchar_t fCYrOJBbajhUXEHHXyTdUArPZAKb;
  wchar_t SJiwdiTGDeIAfAjurAHCUyBtCUVB;
  wchar_t FqvqOAjNEfjUwhnCsrxiwyxlhtnK;
  wchar_t gctgNvFJSMSISSBtBCWcaeDfHrcF;
  wchar_t ZPGzXRkKAvZPWBkTUcBbSLOPWIX;
  wchar_t MWHCpLcCyroojaitPkjGoksgtbFk;
  wchar_t msyHrOYZkdlTefMWNFRUvyURCrZ;
  wchar_t DicCQsoaLnVAPXVOFlCnYhxpMEJ;
  wchar_t SVARywoAQdcdSircYlmImSlOvsj;
  wchar_t QIqaFKCNPtJiJevxZoAFqZmTbhZB;
  wchar_t mAWBeFntrHrrhevyakzDZgwLkqE;
  wchar_t yXJiBgJqRfmaSODXVSnjrNChYtz;
  wchar_t NlwdcMkrhnpbEbgPCjpMKpkcqtf;
  wchar_t DMLrDPnfIEyiDOknQJzyTXcgNrM;
  wchar_t aXnItINstfzxHDatjFCthGlGPzi;
  wchar_t PtYzvngxtYmeDqgTVEMgrSHQKrc;
  wchar_t TMxbSkJiasoyjcCxDhtUJsQJycbG;
  wchar_t vxhQjrhJrtqSXXkTkBrXFvDpCvf;
  wchar_t JMZsnkuTfHPfuDWDciBCYIDRqLZ;
  wchar_t AQycNiDQYkUHIXcXcYgOwHMzjGQ;
  wchar_t DQHgsiOtNYpeVpeYLDfgtwzlKKs;
  wchar_t doACRhngzwbQRIMQHjrhnQmsIScX;
  wchar_t zmImCacmzckprFmszecljFkjIgVe;
  wchar_t wHjDrlfnrZIfZxSUjRxKbLpOYTP;
  wchar_t xfqdCGjhQIwhxPJPnFCjVVhGahK;
  wchar_t unkHbtqwMkdQnUrEQyaePRCbSQi;
  wchar_t kkhdCwHhwijXsHALdCZlnyNvreKq;
  wchar_t WXkCjBUUopGMIgAFqZcnOFErnMJ;
  wchar_t XogiAwuZEYhaQcyBsOJuXsLHYeu;
  wchar_t CRlvnYzbFFmQPXzAcUVCcJSeHEL;
  wchar_t MKgaMFHsLpfZfbzHgmmCYDgZDpS;
  wchar_t nnDvxcFDcCTTnfQSavvUlffOeoCf;
  wchar_t hcCrPyLUfCcMFUyZCtXSZxyaPNc;
  wchar_t vBtbvFDTjvgFaqytPMTYoiZBJhnA;
  wchar_t BgxrtWnOtiUbEjeLbWMfdvdHFpb;
  wchar_t HSKqtHSifdOxxSkmSromjTMTWht;
  wchar_t xChGiephSJxNTcvhVNmaWhpZhwm;
  wchar_t sESbEdhoshgVxAFqkjdFMMbcIphf;
  wchar_t OPgbHNtotcUNBvBIlTiCobqvLzh;
  wchar_t uPCeWmimvvtfdAGEgbEAjofhWaTk;
  wchar_t NZMfGgEvZDDMMwPDToeSdIumFLG;
  wchar_t HpZMtfkUDpobXVLfyITaEYzoAVo;
  wchar_t KXoDhuGPKDOBtcOoTwNNWtODYlg;
  wchar_t qdvxMkxztcYKAhhqUekHanqhsuU;
  wchar_t QqaAxACqHuWdiOEDBqXrTXdepgC;
  wchar_t TDrweEInRjyTZUFObjprxemcubz;
  wchar_t qfbfHTFIlFChYmMOCTvgePDLZp;
  wchar_t KJTCmdjyyCOcYLIawIBQjpDxpoPJ;
  wchar_t UQWTcinrRPWuxoQwyEwEYyVhxUj;
  wchar_t wkgksyvpYiGxsEZwQiCKkMrQSuMm;
  wchar_t JiqIbdnAaMCDBZKZXPmcYetmXMp;
  wchar_t PttBhepAbkhrFonAEANQplZFKjT;
  wchar_t zHDbgIehjJKJHpvEIdbVkOrEquFj;
  wchar_t NrxcBqisqGIjOAqUKJWgnbnTujDI;
  wchar_t tWpRMqdaQWKQcaotljzYemmyVjG;
  wchar_t WmvgwHWlCVbLdjviANqfoInwKotD;
  wchar_t FEfizfNJBNNwYuMjTwmceViMpZN;
  wchar_t PCjKJQXztHJpDlzoBVYMrNfXgeU;
  wchar_t WkQAhwFrocUjxVAGjQbSwDLLLUFp;
  wchar_t NNblXaUUlozLprvcVlAWmDdbJcg;
  wchar_t ROyuNHyakzeKhAczedeKWpCUaIr;
  wchar_t dqnRIpixrCjdWjsEpcuAtkuqsvy;
  wchar_t fAFEWohDuKwTAFxuNYadzdYncEHd;
  wchar_t aTkFGoBXqvwFrWaDFumxiRCIUEY;
  wchar_t sghvgPHDmBOnYegmfDSbftrjmitp;
  wchar_t hNycxNdQKAepwRtZkUKBfpGNmUvd;
  wchar_t YxmeOZgJOtakNVpZHdZjqinlufv;
  wchar_t ItcUfXxVvEeqjGOOXbxnABKQRQK;
  wchar_t ZHVayAOlmUHUWwbjygZfPwoJkjQ;
  wchar_t bCVkdtqTUVDvTxvAdsPNcAPOHQjF;
  wchar_t foVlOFqeFKhieyPGkLSxTTuxSwf;
  wchar_t HBxCWcWksshpMiKfywVTtquKDUt;
  wchar_t tBoOzUyqyveYNKJvfBBSSwoREZ;
  wchar_t sxIssqqXlNhddVrqPbVQirYqUxEO;
  wchar_t zckRBZssmpMvcVjzRNSebprkBdI;
  wchar_t IeUnSxgGGxUYXuVBCZFeGHGFTVv;
  wchar_t yJQmkPUEgIOfKGyCcDDGbTrgSTP;
  wchar_t EydrgrRLBLHpIhrPWsPPprjMnri;
  wchar_t hdvwrdVJUypOFMgurFFBubgXSKf;
  wchar_t VhaQbAntFJbdssssnnZIHxIOLHW;
  wchar_t UbXcVUPHiRRbKOMATfeeRwUgRjO;
  wchar_t PdWBWoGcHEdeUhhGKRSEpDmEKv;
  wchar_t eVRvONimXcyFfDTZmtcGmvmsmdv;
  wchar_t iHWhRWfusHJebBBYtKJviueDzmp;
  wchar_t kPslafaJBeXpkQSQSdeGvnTQbnBb;
  wchar_t ezbSMIECJEhqsbloFBfStWbgAEgx;
  wchar_t RmMuWdrUEboijKIeRgHrcJTdLjnu;
  wchar_t GxfzvYBzIPGDZGpkzgedcmXfjgle;
  wchar_t aAgGuaxGnKcLiieghbSQmtkQNPK;
  wchar_t wpWZPJdHdmKUKxXPGmfYEpzYFiob;
  wchar_t UxegAQYVHiePZPxfAJbcUkTldqo;
  wchar_t AgXJEMhPLHtPGrFHYHARKfowvZih;
  wchar_t xdwdFVVcDLAIXrssIwzqTJsWRwP;
  wchar_t yArTSmnJrmHRSoSBHlMiKfoRVSu;
  wchar_t fWxHKwQbNXZsBDwHSIbYqkAJQOG;
  wchar_t BAThQWfCWzkVhDfcgsUVAETRwqZJ;
  wchar_t pVwrQymkIbeyLWTLGAacROvsfLnC;
  wchar_t iyBPHbKAnnnHGZhntKxnMkVREri;
  wchar_t mIDsQvjGYsjQiutArwciuFVruOf;
  wchar_t YzLdycXhjxzJHyaxMFndjpKqTAo;
  wchar_t UdTOcMyiYhubPCOBkbKlvuBiXWF;
  wchar_t oNEUZMajeTQWRZNrHdggGNbOjlOj;
  wchar_t YWBsSgWBSZfjZFjwFCRuQafCjgaX;
  wchar_t veEUqUCERGAgfdnMaqQnLuUdemb;
  wchar_t CLFkltrwUkUWsiLbbswmyKQgPtI;
  wchar_t bKTfoxJqdYqTYlIehOZcNZypRgF;
  wchar_t DIzKsLOnyrlmtEerZuizYitBfHu;
  wchar_t FkmfcngqatZJUlokiFthPwnhOujH;
  wchar_t TabpYBBOOjwkZzrYzRnKHfFNicf;
  wchar_t KXaAnNaSFbVpBeFfJnGVagpycBRk;
  wchar_t TjwXvCahLNFiFxlxnnAutWDBSAI;
  wchar_t iwQGynwREUMrOiVPWdfmylTWQWd;
  wchar_t trCMtXYTveMOBUanFPujjLfGZFH;
  wchar_t xlAOrEzQFdLNNDgRIsmdZJGUIpCh;
  wchar_t vndqEaptxhuUbcfoMNKNFZhnWip;
  wchar_t kngUNtMRqggTKhEcXDEwkyQgCfFi;
  wchar_t IqWPcbUzctBvjPEkMBJFbmjSNePE;
  wchar_t jMXfEOHmqsCEIBHpqblGuHUJymO;
  wchar_t bTMwZPyxvgCjtsbIvgCGhphCsPwh;
  wchar_t LMhCudyHhSCbAekbjHhFeOUfQlQg;
  wchar_t MNdNZoiCEFvchMYxceUsPMLLsPC;
  wchar_t fQzUSjzGcsvqjAighDcdBRTASnt;
  wchar_t ENIbNqBcZSLLaHyKhbzZOIiprEme;
  wchar_t CiKcNuIFFYnDREgdiKjFSbamSrax;
  wchar_t SOiMXyGQMVSGEJwmSuMUKfHCkUH;
  wchar_t QzRYhiuWbKPNUAEODgJzDAsaGGfz;
  wchar_t IQKHIGbXIESvoJeOWncWzNrpfCA;
  wchar_t urowYSLAIONXSmnzHkAOSBRuvrs;
  wchar_t MqFGMUBmYlqQfAAKfNQwFpSBfZDi;
  wchar_t TMhMORsjbAZXyOAYDLFZrxPkRhj;
  wchar_t bljFEFeuPWpHjCpCFYmGktcdGUR;
  wchar_t aNVdfLEsZDaBDFMVAnrmmsoOGULd;
  wchar_t wrQVmmYkTZTpWwNHZOlCTfTrDBvh;
  wchar_t xxtxHVeMhbrTMfFtVBnxHCVvIlRz;
  wchar_t gMJYHNMqlfIdnFmjdKIcTZlLrgO;
  wchar_t EtjwwwCbZqCqUGIoeCFsGGEAIsdQ;
  wchar_t uXIRHhpfkXiVlKRumlXxTuGegoO;
  wchar_t ntZfaUDshuPHtESNcaEuwXfkmsMz;
  wchar_t lNrXABqCfxukZJUepWyXIoxMVY;
  wchar_t HxEgfEccqEHNBfpJNncCbEWDFLmm;
  wchar_t ZnXKrBYcEDYBSAIIetHhOndMWDA;
  wchar_t lNEAWnOkbAvuoBgKGWSkSvTdFBI;
  wchar_t seHTGYlOEyHFUHyckmEjfbrNjxGm;
  wchar_t lsMaLkbUzteerEOVRMNtpFmdoIlH;
  wchar_t WIJEbCJTRXPzBRkZllilnWjHmvC;
  wchar_t MXIskweEITyWIzDLVZbnnXYIkOu;
  wchar_t xTvFfEoljRATagCppYdXwrOHbUp;
  wchar_t FkKeHxMhtDhbAkUwbNtXnHTrWzYE;
  wchar_t ZxQCRnJLguXYsbnnykToolFeQvVU;
  wchar_t TVOUrdafcmfNpdofQIyCtvrbZmdW;
  wchar_t MhmGBVSrNkUAICeihHSoBhXWMgOd;
  wchar_t gzzGEzJSBhovvjWTVYhoQgVXKxfX;
  wchar_t zhzoTMBPaChwZqOscYAVhIFbPCK;
  wchar_t mZaMiVdkOHHSciLDLrLZLfaoyrQ;
  wchar_t ZovIWCiDOpzfIWpeIMZrqpsxnzz;
  wchar_t GeIOTvDnphprqBbFzozWYXbBOfS;
  wchar_t tUKAyHCJcNlLiUfmtVuGgTuLHAU;
  wchar_t GsIAzQmaCJBubbspKXfyBBdKcgF;
  wchar_t XhIiFsYNYtzioigfEbhiHgwgBWUP;
  wchar_t sEBirakWdWAchciMefepcvZtwfEL;
  wchar_t KKUTyLgVaEpnNFAeezteiYKxkGA;
  wchar_t RFHqewxxKBRwwXJnHneuvCLruws;
  wchar_t hnNSylUtuzgkGLjjyfNoQnqzymk;
  wchar_t mFuBVMHRhzJlFjxgiqgIiGeIuomr;
  wchar_t dQklpZzhdbEnRLxAvFgJGDbfjdzG;
  wchar_t CZzftMBWujfuqVrHaIwaDNJfoFhV;
  wchar_t SjWBxTCgfncnUfFjHIPbrZhnLDAA;
  wchar_t svGfecZqKiDqgHhFLTaqkgDTFwm;
  wchar_t vBFfRgywbvfiSfGfqvfxahDswsfU;
  wchar_t BTAEWqyZteSBTEIIVDMKNLqlaqY;
  wchar_t ZmrGoTrkZePhcIRKgXXhEiUSeXk;
  wchar_t PqqZWFcZhsPZuoeNthXKUnwgfxR;
  wchar_t BoWAQHBxlyFxzLXlKZsVilWvGUYF;
  wchar_t sNAFAiEGLGzUVYQDRYHfPHnQcPTE;
  wchar_t pYrIrGmcQKnkFlDcmSIVyARueXb;
  wchar_t iusGVBxKYZnlpKUVZgOcRtgNEoj;
  wchar_t UpFPJWWwbKUTUdaPxHbaEmVGcRcJ;
  wchar_t AfXUKZQxOEpkRqcguivmIrLZFYn;
  wchar_t AFQltTDMAplkaZqzhznQEDevjIG;
  wchar_t wLFcRYaQeoMdDvPlwtUZXkJXlVG;
  wchar_t qPKnCFWayWGtxkjESAOaSoIEgiuf;
  wchar_t frqGiXCvRwhXzcrMkMcpRMDdGzMs;
  wchar_t svLQpPgKyuGTzTsSwfELJnHsrIwA;
  wchar_t NBBXDlyKsDiPQIyuyLKHflMPtSd;
  wchar_t UIOqbScuqQpCbpFHiSWqoethltB;
  wchar_t ALJdovHuXrUrUpJjdnnMioCOOxX;
  wchar_t kFMYdYZpKGpNEAhCcikcSEfLuUP;
  wchar_t JmxIotnSZvleGfSQSTeCIgQfOEv;
  wchar_t BIaccGRwFfYEhOPXYgAwTgNHmyv;
  wchar_t AwjpwPNdysDjHZphjbtHhFydRwn;
  wchar_t uhopOlGjznBcolPhiedoFUskBgKo;
  wchar_t CiktokFCeYXMLqcaHwEAjxGjMxr;
  wchar_t MLJMqonaLcbsRIJbwOXaYcsfLFB;
  wchar_t yaXKYqpCXhVbmDrNkupVUGxXygq;
  wchar_t uDjhfRKHRUuYZlxFqdlaLpAJEco;
  wchar_t gdmCMmwWtsdhuftQjOOALVjBWkl;
  wchar_t SKNgXQDVFNuuHPKrzojktRbBSV;
  wchar_t yMWTjfWtUaxGCUrGJPAdaimRwog;
  wchar_t MCOEPwbWsxnVHGSUuSzxqRqnuJZ;
  wchar_t frZHUxheWDiKzRyIqrOGREDRvCR;
  wchar_t PJSEfxpFNwbdLnhgdVrkMkpeFQn;
  wchar_t sZgvaHCKjUikAdxmvvbPPaMCgEk;
  wchar_t FwuFIMZJhDPhuLuXpUgNTkbuMow;
  wchar_t nlpIUCXLaawwzWpWlhJACrkZDaK;
  wchar_t CyjUqUflPjEeOlHYMdaUUaHUBTj;
  wchar_t mRSQGTjZxxMPPlhEgVNxOdOjyEZ;
  wchar_t TVjGRTitqtYgtlIpOeWALcAnOWKR;
  wchar_t nDEFzAPJrpnjJaTZigTYVSMBCLC;
  wchar_t GGwGQCETpzhNEQbeUZOntmRlifEg;
  wchar_t oSfJAfndNCwEGmYzrYNBywwPgBi;
  wchar_t croCMzTAFkADAFJMGpNlIVzRnGl;
  wchar_t WVxbcXijhjenQilfKyybbQpcrKmL;
  wchar_t uZFahQdfbJtjDZKoShHlvmredcFb;
  wchar_t CxHvuyjveHWOXVdlqCdPYCHGilUD;
  wchar_t QdnHNfbcqGAQRzwOXwHeZFKBikH;
  wchar_t PyyeeLSalTzzLcLVGaUGBbiAVrp;
  wchar_t JkIVsiMxmMNfYwIzTdMbDGROCiO;
  wchar_t wOCEIfVtIwBUEEpKzrWDBfYZfdn;
  wchar_t aEnRQLKGZhJUZSotSftrTVoEidA;
  wchar_t XIOnMFaKzgRnnECtlAgazrgcTP;
  wchar_t YKXxkhRGZzzUwoaULPHWdoIdoNH;
  wchar_t uJKRyCRDghXTchEUZElrJfHRTCtJ;
  wchar_t zCLFERDXoneehyAOredVdmWBLrVe;
  wchar_t vxlbxnAlCPHiGikWzxsmMJetFAzt;
  wchar_t SVrbudeLKZOIXCnymGMleKPhnauq;
  wchar_t oAlhxQGumTgjheiTEkeEvNqiDJnP;
  wchar_t dFxPHNRovjfyVJkPiEFVHjuZeloX;
  wchar_t SfZvVRtNbDWCkSGoOqNRczaMCnW;
  wchar_t MBnDShrWDJnkzDcLBngiwoQoIEg;
  wchar_t gJrVFBikYHfacBjchKOebhuSKHOo;
  wchar_t SqfZkgsYGtsMjLtkLUWKCOJFVPK;
  wchar_t DZgnJLYzqkotEjvoEbRRSkIytda;
  wchar_t TSmqcBBKoOBUEOSZPcJwiPSHIFHV;
  wchar_t gQjUBOddXGwpubImYPBYEQlbaDn;
  wchar_t uFnoldiedCjjVlnybLkiSjubGcm;
  wchar_t ekuLpvfbEBuvjvvqZnErpkHZdyD;
  wchar_t ysFUskLYiwWKSDxUfbcfmYOgint;
  wchar_t JBzNgbcDwlGwOyZdxWclqkEFLkk;
  wchar_t GWcUuMjNoAJtBsfdhhgPnAiemBy;
  wchar_t hshgCqQlTzzLdrQGCYEhUInVDUs;
  wchar_t XlzOObGrfOMoERmFUFSZuJZCWgI;
  wchar_t LIFZquiCdvucVTRGrBLyigfuewtA;
  wchar_t lPCFGHEyuaiUGqvKndXfLkblSVes;
  wchar_t wVvcathpzHAQiPnztvPMcHTdhPW;
  wchar_t rEHQDwrYyAkFObogPIVehJCUMph;
  wchar_t IDyiXpFPXWHyKyfAWyXxGrJkJJl;
  wchar_t HatnkXzFUICRbTGPsKHvLZgtrVD;

  // Member methods:
  void zZnaqzdFpUKZcFwRCoPJHVxevliD() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::fzpgSVRENRUBXEAHfhvrXptZmJo::DVGhYieYaAVEsDSJjUnnMyFiKjy*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3340))(this);
  }

};
}