// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Holoville::HOTween {
struct __TweenParms_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _TypeToShortString;
};

struct __TweenParms_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __TweenParms_Il2CppClass {
  Il2CppClass_1 _1;
  __TweenParms_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __TweenParms_Il2CppVtbl vtbl;
};

class TweenParms {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C84158;
  static inline    __TweenParms_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __TweenParms_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__TweenParms_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __TweenParms_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* id;
  int32_t intId;
  bool autoKillOnComplete;
  int32_t updateType;
  float timeScale;
  int32_t loops;
  int32_t loopType;
  bool isPaused;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onStart;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onStartWParms;
  ModdingAPI::Exposed::System::Object_array* onStartParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onUpdate;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onUpdateWParms;
  ModdingAPI::Exposed::System::Object_array* onUpdateParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onPluginUpdated;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onPluginUpdatedWParms;
  ModdingAPI::Exposed::System::Object_array* onPluginUpdatedParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onPause;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onPauseWParms;
  ModdingAPI::Exposed::System::Object_array* onPauseParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onPlay;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onPlayWParms;
  ModdingAPI::Exposed::System::Object_array* onPlayParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onRewinded;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onRewindedWParms;
  ModdingAPI::Exposed::System::Object_array* onRewindedParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onStepComplete;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onStepCompleteWParms;
  ModdingAPI::Exposed::System::Object_array* onStepCompleteParms;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onComplete;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onCompleteWParms;
  ModdingAPI::Exposed::System::Object_array* onCompleteParms;
  bool manageBehaviours;
  bool manageGameObjects;
  ModdingAPI::Exposed::UnityEngine::Behaviour_array* managedBehavioursOn;
  ModdingAPI::Exposed::UnityEngine::Behaviour_array* managedBehavioursOff;
  ModdingAPI::Exposed::UnityEngine::GameObject_array* managedGameObjectsOn;
  ModdingAPI::Exposed::UnityEngine::GameObject_array* managedGameObjectsOff;
  bool pixelPerfect;
  bool speedBased;
  bool easeSet;
  int32_t easeType;
  ModdingAPI::Exposed::UnityEngine::AnimationCurve* easeAnimCurve;
  float easeOvershootOrAmplitude;
  float easePeriod;
  float delay;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* propDatas;
  bool isFrom;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* onPluginOverwritten;
  ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallbackWParms* onPluginOverwrittenWParms;
  ModdingAPI::Exposed::System::Object_array* onPluginOverwrittenParms;

  // Member methods:
  void InitializeObject(ModdingAPI::Exposed::Holoville::HOTween::Tweener* p_tweenObj, Il2CppObject* p_target) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, ModdingAPI::Exposed::Holoville::HOTween::Tweener*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153B9B0))(this, p_tweenObj, p_target);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* SpeedBased() {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153D910))(this);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* SpeedBased(bool p_speedBased) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153D920))(this, p_speedBased);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Ease(int32_t p_easeType) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153D930))(this, p_easeType);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Ease(int32_t p_easeType, float p_amplitude, float p_period) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, int32_t, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA10))(this, p_easeType, p_amplitude, p_period);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Ease(ModdingAPI::Exposed::UnityEngine::AnimationCurve* p_easeAnimationCurve) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, ModdingAPI::Exposed::UnityEngine::AnimationCurve*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA40))(this, p_easeAnimationCurve);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Delay(float p_delay) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA60))(this, p_delay);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Pause(bool p_pause) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA70))(this, p_pause);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Prop(System_String* p_propName, ModdingAPI::Exposed::Holoville::HOTween::Plugins::Core::ABSTweenPlugin* p_plugin) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, System_String*, ModdingAPI::Exposed::Holoville::HOTween::Plugins::Core::ABSTweenPlugin*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA80))(this, p_propName, p_plugin);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Prop(System_String* p_propName, Il2CppObject* p_endVal) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, System_String*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DA80))(this, p_propName, p_endVal);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Prop(System_String* p_propName, Il2CppObject* p_endVal, bool p_isRelative) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, System_String*, Il2CppObject*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DAA0))(this, p_propName, p_endVal, p_isRelative);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* AutoKill(bool p_active) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DD10))(this, p_active);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Loops(int32_t p_loops) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DD20))(this, p_loops);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* Loops(int32_t p_loops, int32_t p_loopType) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DDE0))(this, p_loops, p_loopType);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* OnUpdate(ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* p_function) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DDF0))(this, p_function);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* OnComplete(ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback* p_function) {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*, ModdingAPI::Exposed::Holoville::HOTween::Core::TweenDelegate::TweenCallback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DE00))(this, p_function);
  }
  ModdingAPI::Exposed::Holoville::HOTween::TweenParms* IsFrom() {
    return reinterpret_cast<ModdingAPI::Exposed::Holoville::HOTween::TweenParms*(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DE10))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Holoville::HOTween::TweenParms*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DED0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _TypeToShortString = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_TypeToShortString; }
  );

  // Static methods:
  static inline bool ValidateValue(Il2CppObject* p_val, ModdingAPI::Exposed::System::Type_array* p_validVals) {
    return reinterpret_cast<bool(__fastcall*)(Il2CppObject*, ModdingAPI::Exposed::System::Type_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x153DE20))(p_val, p_validVals);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x153E090))();
  }
};
}