// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __iTweenEvent_Il2CppStaticFields {
};

struct __iTweenEvent_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __iTweenEvent_Il2CppClass {
  Il2CppClass_1 _1;
  __iTweenEvent_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __iTweenEvent_Il2CppVtbl vtbl;
};

class iTweenEvent {
public:
  // Il2Cpp fields:
  __iTweenEvent_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  System_String* tweenName;
  bool playAutomatically;
  float delay;
  int32_t type;
  bool showIconInInspector;
  ModdingAPI::Exposed::System::String_array* keys;
  ModdingAPI::Exposed::System::Int32_array* indexes;
  ModdingAPI::Exposed::System::String_array* metadatas;
  ModdingAPI::Exposed::System::Int32_array* ints;
  ModdingAPI::Exposed::System::Single_array* floats;
  ModdingAPI::Exposed::System::Boolean_array* bools;
  ModdingAPI::Exposed::System::String_array* strings;
  ModdingAPI::Exposed::UnityEngine::Vector3_array* vector3s;
  ModdingAPI::Exposed::UnityEngine::Color_array* colors;
  ModdingAPI::Exposed::UnityEngine::Space_array* spaces;
  ModdingAPI::Exposed::iTween::EaseType_array* easeTypes;
  ModdingAPI::Exposed::iTween::LoopType_array* loopTypes;
  ModdingAPI::Exposed::UnityEngine::GameObject_array* gameObjects;
  ModdingAPI::Exposed::UnityEngine::Transform_array* transforms;
  ModdingAPI::Exposed::UnityEngine::AudioClip_array* audioClips;
  ModdingAPI::Exposed::UnityEngine::AudioSource_array* audioSources;
  ModdingAPI::Exposed::ArrayIndexes_array* vector3Arrays;
  ModdingAPI::Exposed::ArrayIndexes_array* transformArrays;
  ModdingAPI::Exposed::iTweenPath_array* paths;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* values;
  bool stopped;
  bool animating;
  ModdingAPI::Exposed::iTween* instantiatedTween;
  System_String* internalName;

  // Member methods:
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* get_Values() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB120))(this);
  }
  void set_Values(ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*, ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB150))(this, value);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB160))(this);
  }
  void Play() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB170))(this);
  }
  void Stop() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB2E0))(this);
  }
  void OnAnimComplete(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB3F0))(this, name);
  }
  bool IsAnimating() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB03DA0))(this);
  }
  void OnDrawGizmos() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB440))(this);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* StartEvent() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB5D0))(this);
  }
  void SerializeValues() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAB720))(this);
  }
  void DeserializeValues() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CADBC0))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::iTweenEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAF300))(this);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::iTweenEvent* GetEvent(ModdingAPI::Exposed::UnityEngine::GameObject* obj, System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::iTweenEvent*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::GameObject*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CAAD30))(obj, name);
  }
};
}