// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Guid.hpp"
#include "ModdingAPI.Exposed.LuVUzCdkMbapUjwzFREcquDmhCC.rTwfhpoWoSJckvOwuotHwxvyAtW.hpp"
#include "ModdingAPI.Exposed.LuVUzCdkMbapUjwzFREcquDmhCC.IovejXTbupgtWfjuSDfLhBjrvgFE.hpp"
#include "ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO.hpp"
#include "ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW.hpp"
#include "ModdingAPI.Exposed.UFkWILAFKVOBxPiMFNYawDjynyh.KFzBeEjWDTKXQnWpJvHusYxcdzA.hpp"
#include "ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::gRTAuDEjjhhAtgAOiOrKmgPWPCRv.hpp"
#include "ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA.hpp"


namespace ModdingAPI::Exposed {
struct __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Guid wrsqTRTJsILdqeiyFASeBJISOoLB;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* xpeGIokhIeMGaIryngNWIDoziWsT;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* rDpgggjgFtIQSNufDDSSzlHdIFh;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* dJWrtmOJFJilIfELssrEfdHLcDfE;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* RNEUdqGiQfVikcDpmbCnKyOLFyg;
  ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW yeeBgjdUCmlvJsRTfCbVilAHvpNN;
  ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::IovejXTbupgtWfjuSDfLhBjrvgFE kRTgUKCylYhVgGOLVAbudgbDQfxr;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Data::NativeBuffer* yTYWjrmtTwQGMMCtUxnYhXiHbCa;
  ModdingAPI::Exposed::System::Func_T__TResult_* AOXDGviFyVKLMQUlMpdkhuyfsOcq;
  ModdingAPI::Exposed::System::Func_T__TResult_* lCTTzahLlcELXCOxXAcaJqKeqEb;
};

struct __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppClass {
  Il2CppClass_1 _1;
  __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppVtbl vtbl;
};

class jKoBDEQKGacnmQPaZDoFxOVlnXe {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C6B3C0;
  static inline    __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __jKoBDEQKGacnmQPaZDoFxOVlnXe_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Guid> wrsqTRTJsILdqeiyFASeBJISOoLB = __CppStaticProperty<ModdingAPI::Exposed::System::Guid>(
   []() { return &GetStaticClassInstance()->pStaticFields->wrsqTRTJsILdqeiyFASeBJISOoLB; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*> xpeGIokhIeMGaIryngNWIDoziWsT = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->xpeGIokhIeMGaIryngNWIDoziWsT; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*> rDpgggjgFtIQSNufDDSSzlHdIFh = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->rDpgggjgFtIQSNufDDSSzlHdIFh; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*> dJWrtmOJFJilIfELssrEfdHLcDfE = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->dJWrtmOJFJilIfELssrEfdHLcDfE; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*> RNEUdqGiQfVikcDpmbCnKyOLFyg = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->RNEUdqGiQfVikcDpmbCnKyOLFyg; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW> yeeBgjdUCmlvJsRTfCbVilAHvpNN = __CppStaticProperty<ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW>(
   []() { return &GetStaticClassInstance()->pStaticFields->yeeBgjdUCmlvJsRTfCbVilAHvpNN; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::IovejXTbupgtWfjuSDfLhBjrvgFE> kRTgUKCylYhVgGOLVAbudgbDQfxr = __CppStaticProperty<ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::IovejXTbupgtWfjuSDfLhBjrvgFE>(
   []() { return &GetStaticClassInstance()->pStaticFields->kRTgUKCylYhVgGOLVAbudgbDQfxr; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::Rewired::Utils::Classes::Data::NativeBuffer*> yTYWjrmtTwQGMMCtUxnYhXiHbCa = __CppStaticProperty<ModdingAPI::Exposed::Rewired::Utils::Classes::Data::NativeBuffer*>(
   []() { return &GetStaticClassInstance()->pStaticFields->yTYWjrmtTwQGMMCtUxnYhXiHbCa; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> AOXDGviFyVKLMQUlMpdkhuyfsOcq = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->AOXDGviFyVKLMQUlMpdkhuyfsOcq; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> lCTTzahLlcELXCOxXAcaJqKeqEb = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->lCTTzahLlcELXCOxXAcaJqKeqEb; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x311990))();
  }
  static inline bool ayiQIKNJxwNmRUlowBVqLZrcAxA(System_String* ) {
    return reinterpret_cast<bool(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3122A0))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IList_T_* XKmKaiUsPhGFFdbltBSOIpJsFzX() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IList_T_*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x3126C0))();
  }
  static inline ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq* tLLbbAKVkPNvpqbhTaKpaeNpxZSO(ModdingAPI::Exposed::System::Collections::Generic::IList_T_* , System_String* , ModdingAPI::Exposed::System::StringComparison ) {
    return reinterpret_cast<ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::IList_T_*, System_String*, ModdingAPI::Exposed::System::StringComparison)>(Helpers::Memory::GetInstance().MakeAbsolute(0x312750))(, , );
  }
  static inline ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq* tKYanbzMsHEzGmRbciabRSToAeX(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO ) {
    return reinterpret_cast<ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq*(__fastcall*)(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO)>(Helpers::Memory::GetInstance().MakeAbsolute(0x312A60))();
  }
  static inline ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq* ZBUdUVNJJYCmdkqyXaNZjHfBnJHW(System_String* ) {
    return reinterpret_cast<ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x312C60))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_* EZCFarClYLcUAWNkldqrCleOCnrI() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x312D10))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_* EZCFarClYLcUAWNkldqrCleOCnrI(System_String* ) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x312F20))();
  }
  static inline bool DCbeBzIVuagoxVZgOSfWcmvBhRi() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x3132F0))();
  }
  static inline int32_t MiWcGhIKSiIhiFsaUutuuzBJJvH() {
    return reinterpret_cast<int32_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x3134D0))();
  }
  static inline int32_t MiWcGhIKSiIhiFsaUutuuzBJJvH(ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW , ModdingAPI::Exposed::Rewired::Utils::Classes::Data::NativeBuffer* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::LuVUzCdkMbapUjwzFREcquDmhCC::rTwfhpoWoSJckvOwuotHwxvyAtW, ModdingAPI::Exposed::Rewired::Utils::Classes::Data::NativeBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x313580))(, );
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IList_T_* vUWfbiRTgifmYQKjSLIWDlPDwDQ() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IList_T_*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x313910))();
  }
  static inline void FYWCFgLbUjjzGImoXmzimnVIBYT(ModdingAPI::Exposed::System::Collections::Generic::List_T_* ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x314110))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* vhEPNLQOXvjuScbCYoRToMdwosu(ModdingAPI::Exposed::System::Collections::Generic::List_T_* ) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x314520))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* NlhaWPlEHyhPGDGDcAyDQfctClUL(uint32_t ) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x314830))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::List_T_* kcQdXFoedquBUbpAyBciecXiQWY(uint32_t ) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x314DD0))();
  }
  static inline System_String* uLtkeHlDAISDvyHAztRnzagCdaL(uint32_t ) {
    return reinterpret_cast<System_String*(__fastcall*)(uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x315220))();
  }
  static inline void YLBLLwmyetICNvUrgDqvXiVbGpIj(uint32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , bool , System_String* ) {
    reinterpret_cast<void(__fastcall*)(uint32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, bool, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x315580))(, , , );
  }
  static inline bool jNivSFIeOokHaQZwySrihDDieuB(uint32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , bool , uint32_t ) {
    return reinterpret_cast<bool(__fastcall*)(uint32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, bool, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3156F0))(, , , );
  }
  static inline bool XPZOcPWdvYefpBmifvOkmaPyCUIX(uint32_t , System_String* , System_String* , uint32_t ) {
    return reinterpret_cast<bool(__fastcall*)(uint32_t, System_String*, System_String*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3158C0))(, , , );
  }
  static inline bool grhwjSoPkpuUZJhaCtWVqjAiaeg(System_String* , System_String* ) {
    return reinterpret_cast<bool(__fastcall*)(System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x315B90))(, );
  }
  static inline bool aABHIfNLqvnsajKHzmhIKthnQMj(uint32_t , System_String* , uint32_t ) {
    return reinterpret_cast<bool(__fastcall*)(uint32_t, System_String*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x315CC0))(, , );
  }
  static inline bool XILYNdLMygNOeXLiUECKvGOHZJE(System_String* , bool ) {
    return reinterpret_cast<bool(__fastcall*)(System_String*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x316070))(, );
  }
  static inline ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA NoHPCgvhWOBdDrKyxXxPsNSuDbI() {
    return reinterpret_cast<ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x316630))();
  }
  static inline System_String* UhWkhPbsPtfXGZeYLfNoNejjAKY(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::gRTAuDEjjhhAtgAOiOrKmgPWPCRv ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::gRTAuDEjjhhAtgAOiOrKmgPWPCRv)>(Helpers::Memory::GetInstance().MakeAbsolute(0x316710))(, );
  }
  static inline System_String* jqhoXvssqfKbzTOxAObLuDGZCVrc(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3169A0))(, );
  }
  static inline ModdingAPI::Exposed::System::Guid get_HidClassGuid() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Guid(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x316C70))();
  }
  static inline System_String* CzVmAMtOmkYETNNAFOxZwrJDtBk(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x316E80))(, );
  }
  static inline System_String* AQCeMOYnVUEknBJPokFNSlFxovv(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x316F30))(, );
  }
  static inline System_String* QPoJkRXHuOBNCPoyEYOyLgotPcP(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x316FE0))(, );
  }
  static inline System_String* VvhAWimMSLnNgzOXVlbQNtBYSCf(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x317090))(, );
  }
  static inline System_String* lNqfIIBAOFUmzZVMxTUrDvFecYn(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA , int32_t ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x317140))(, , );
  }
  static inline System_String* zwPgElXCARySIIwbUeeMmnuouLi(intptr_t , ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA ) {
    return reinterpret_cast<System_String*(__fastcall*)(intptr_t, ModdingAPI::Exposed::UFkWILAFKVOBxPiMFNYawDjynyh::KFzBeEjWDTKXQnWpJvHusYxcdzA)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3173E0))(, );
  }
  static inline ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq* CVIDMZLIueqsOtGMMdoFjboWgca(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO ) {
    return reinterpret_cast<ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq*(__fastcall*)(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO)>(Helpers::Memory::GetInstance().MakeAbsolute(0x317610))();
  }
  static inline ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq* ixZbiPuwZhzSYTOoPavsNWspQfR(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO ) {
    return reinterpret_cast<ModdingAPI::Exposed::mCAMdxhJaeECmAhyzYhXQVVmSyIq*(__fastcall*)(ModdingAPI::Exposed::jKoBDEQKGacnmQPaZDoFxOVlnXe::BFdDRtOUjZDXXysgfgXdUNMOdrO)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3177E0))();
  }
};
}