// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __JumpData_Il2CppStaticFields {
  int32_t DISPLAY_NAME_MAX_LENGTH;
};

struct __JumpData_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __JumpData_Il2CppClass {
  Il2CppClass_1 _1;
  __JumpData_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __JumpData_Il2CppVtbl vtbl;
};

class JumpData {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C4FE80;
  static inline    __JumpData_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __JumpData_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__JumpData_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __JumpData_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* _m_ActiveMissionId_k__BackingField;
  System_String* _m_ActiveMissionLocId_k__BackingField;
  int32_t _m_ExperienceMode_k__BackingField;
  int32_t m_EditorId;
  System_String* _m_FilePath_k__BackingField;
  float _m_HoursSurvived_k__BackingField;
  System_String* _m_Location_k__BackingField;
  ModdingAPI::Exposed::ScreenshotSaveGameFormat* _m_Screenshot_k__BackingField;
  ModdingAPI::Exposed::SlotData* _m_Slot_k__BackingField;

  // Member methods:
  System_String* get_m_ActiveMissionId() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  void set_m_ActiveMissionId(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30D060))(this, value);
  }
  System_String* get_m_ActiveMissionLocId() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  void set_m_ActiveMissionLocId(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A3E0))(this, value);
  }
  int32_t get_m_ExperienceMode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x37AAE0))(this);
  }
  void set_m_ExperienceMode(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3838E0))(this, value);
  }
  System_String* get_m_FilePath() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110B0))(this);
  }
  void set_m_FilePath(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110C0))(this, value);
  }
  float get_m_HoursSurvived() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x581030))(this);
  }
  void set_m_HoursSurvived(float value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x807930))(this, value);
  }
  System_String* get_m_Location() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319970))(this);
  }
  void set_m_Location(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A420))(this, value);
  }
  ModdingAPI::Exposed::ScreenshotSaveGameFormat* get_m_Screenshot() {
    return reinterpret_cast<ModdingAPI::Exposed::ScreenshotSaveGameFormat*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319960))(this);
  }
  void set_m_Screenshot(ModdingAPI::Exposed::ScreenshotSaveGameFormat* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, ModdingAPI::Exposed::ScreenshotSaveGameFormat*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x31F420))(this, value);
  }
  ModdingAPI::Exposed::SlotData* get_m_Slot() {
    return reinterpret_cast<ModdingAPI::Exposed::SlotData*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319980))(this);
  }
  void set_m_Slot(ModdingAPI::Exposed::SlotData* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, ModdingAPI::Exposed::SlotData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A430))(this, value);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18794E0))(this);
  }
  System_String* GetTreePath() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1879AC0))(this);
  }
  bool IsStoryMode() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::JumpData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1879DB0))(this);
  }
  void Rename(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::JumpData*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1879DD0))(this, name);
  }

  // Static fields:
  static inline __CppStaticProperty<int32_t> DISPLAY_NAME_MAX_LENGTH = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->DISPLAY_NAME_MAX_LENGTH; }
  );

  // Static methods:
  static inline ModdingAPI::Exposed::JumpData* LoadFromFile(System_String* path) {
    return reinterpret_cast<ModdingAPI::Exposed::JumpData*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1879F60))(path);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x187A520))();
  }
};
}