// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Quaternion.hpp"


namespace ModdingAPI::Exposed {
struct __LightTracking_Il2CppStaticFields {
  bool s_FadePlayerLightsDurignCinematics;
};

struct __LightTracking_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __LightTracking_Il2CppClass {
  Il2CppClass_1 _1;
  __LightTracking_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __LightTracking_Il2CppVtbl vtbl;
};

class LightTracking {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C412F8;
  static inline    __LightTracking_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __LightTracking_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__LightTracking_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __LightTracking_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::UnityEngine::Light* m_LightComponent;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_WorldPosition;
  bool m_StaticPosition;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_OriginalPosition;
  ModdingAPI::Exposed::UnityEngine::Quaternion m_OriginalRotation;
  bool m_Started;
  ModdingAPI::Exposed::GearItem* m_AssociatedGearItem;
  float m_BaseLightIntensity;
  float m_CinematicFadeStrength;

  // Member methods:
  void Awake() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDA90))(this);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDAA0))(this);
  }
  void OnEnable() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDAB0))(this);
  }
  void MaybeAdd(bool areWeStarting) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDAC0))(this, areWeStarting);
  }
  void OnDisable() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDDE0))(this);
  }
  void StorePositionAndRotation() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EDE80))(this);
  }
  void RestorePositionAndRotation() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE0E0))(this);
  }
  void MaybeUpdateForCinematic(bool isCinematicActive) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE260))(this, isCinematicActive);
  }
  bool IsLightEnabled() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE410))(this);
  }
  void EnableLight(bool state) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE480))(this, state);
  }
  float GetLightIntensity() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE500))(this);
  }
  void SetLightIntensity(float intensity) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE570))(this, intensity);
  }
  void UpdateLightIntensity() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE580))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Light* GetLightComponent() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Light*(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE620))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LightTracking*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18EE6F0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<bool> s_FadePlayerLightsDurignCinematics = __CppStaticProperty<bool>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_FadePlayerLightsDurignCinematics; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))();
  }
};
}