// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"
#include "ModdingAPI.Exposed.UnityEngine.LayerMask.hpp"


namespace ModdingAPI::Exposed {
struct __LocalSpaceRichAI_Il2CppStaticFields {
};

struct __LocalSpaceRichAI_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Start;
  VirtualInvokeData _5_OnEnable;
  VirtualInvokeData _6_UpdatePath;
  VirtualInvokeData _7_OnTargetReached;
  VirtualInvokeData _8_UpdateTarget;
  VirtualInvokeData _9_Update;
  VirtualInvokeData _10_OnDrawGizmos;
};

struct __LocalSpaceRichAI_Il2CppClass {
  Il2CppClass_1 _1;
  __LocalSpaceRichAI_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __LocalSpaceRichAI_Il2CppVtbl vtbl;
};

class LocalSpaceRichAI {
public:
  // Il2Cpp fields:
  __LocalSpaceRichAI_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::UnityEngine::Transform* target;
  ModdingAPI::Exposed::UnityEngine::Vector3 RichAI_lastPathTarget;
  float RichAI_repathTimer;
  bool drawGizmos;
  bool repeatedlySearchPaths;
  float repathRate;
  float maxSpeed;
  float acceleration;
  float slowdownTime;
  float rotationSpeed;
  float rotationSpeedScale;
  float endReachedDistance;
  float wallForce;
  float wallDist;
  ModdingAPI::Exposed::UnityEngine::Vector3 gravity;
  bool raycastingForGroundPlacement;
  ModdingAPI::Exposed::UnityEngine::LayerMask groundMask;
  float centerOffset;
  int32_t funnelSimplification;
  ModdingAPI::Exposed::UnityEngine::Animation* anim;
  bool preciseSlowdown;
  bool slowWhenNotFacingTarget;
  ModdingAPI::Exposed::UnityEngine::Vector3 RichAI_velocity;
  ModdingAPI::Exposed::Pathfinding::RichPath* rp;
  ModdingAPI::Exposed::Seeker* seeker;
  ModdingAPI::Exposed::UnityEngine::Transform* tr;
  ModdingAPI::Exposed::UnityEngine::CharacterController* RichAI_controller;
  ModdingAPI::Exposed::Pathfinding::RVO::RVOController* RichAI_rvoController;
  ModdingAPI::Exposed::UnityEngine::Vector3 RichAI_lastTargetPoint;
  ModdingAPI::Exposed::UnityEngine::Vector3 currentTargetDirection;
  bool waitingForPathCalc;
  bool canSearchPath;
  bool delayUpdatePath;
  bool traversingSpecialPath;
  bool lastCorner;
  float RichAI_distanceToWaypoint;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* buffer;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* wallBuffer;
  float lastRepath;
  ModdingAPI::Exposed::BaseAi* m_BaseAi;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_PreviousTargetHeading;
  ModdingAPI::Exposed::LocalSpaceGraph* graph;

  // Member methods:
  void UpdatePath() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LocalSpaceRichAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18FEA80))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Vector3 UpdateTarget(ModdingAPI::Exposed::Pathfinding::RichFunnel* fn) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector3(__fastcall*)(ModdingAPI::Exposed::LocalSpaceRichAI*, ModdingAPI::Exposed::Pathfinding::RichFunnel*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18FEE00))(this, fn);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::LocalSpaceRichAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x18FFAB0))(this);
  }
};
}