// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Marketplace {
struct __CatalogServiceManager_Il2CppStaticFields {
};

struct __CatalogServiceManager_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __CatalogServiceManager_Il2CppClass {
  Il2CppClass_1 _1;
  __CatalogServiceManager_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __CatalogServiceManager_Il2CppVtbl vtbl;
};

class CatalogServiceManager {
public:
  // Il2Cpp fields:
  __CatalogServiceManager_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Marketplace::CatalogServiceManager*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }

  // Static methods:
  static inline void Create() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))();
  }
  static inline ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_* BrowseCatalogAsync(int32_t userId, System_String* parentId, int32_t parentMediaType, int32_t childMediaType, int32_t orderBy, uint32_t skipItems, uint32_t maxItems, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_* callback) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_*(__fastcall*)(int32_t, System_String*, int32_t, int32_t, int32_t, uint32_t, uint32_t, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x21C9800))(userId, parentId, parentMediaType, childMediaType, orderBy, skipItems, maxItems, callback);
  }
  static inline ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_* BrowseCatalogBundlesAsync(int32_t userId, System_String* parentId, int32_t parentMediaType, System_String* productId, int32_t relationship, uint32_t skipItems, uint32_t maxItems, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_* callback) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_*(__fastcall*)(int32_t, System_String*, int32_t, System_String*, int32_t, uint32_t, uint32_t, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x21C9B90))(userId, parentId, parentMediaType, productId, relationship, skipItems, maxItems, callback);
  }
  static inline ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_* GetCatalogItemDetailsAsync(int32_t userId, ModdingAPI::Exposed::System::String_array* productIds, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_* callback) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp_T_*(__fastcall*)(int32_t, ModdingAPI::Exposed::System::String_array*, ModdingAPI::Exposed::UnityAOT::GetObjectAsyncOp::GetObjectAsyncCallback_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x21C9F30))(userId, productIds, callback);
  }
  static inline void GetCatalogItemDetailsListThunk(uint32_t result, intptr_t lresult, intptr_t userData) {
    reinterpret_cast<void(__fastcall*)(uint32_t, intptr_t, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x21CA1F0))(result, lresult, userData);
  }
  static inline void GetBrowseCatalogResultThunk(uint32_t result, intptr_t lresult, intptr_t userData) {
    reinterpret_cast<void(__fastcall*)(uint32_t, intptr_t, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x21CA2F0))(result, lresult, userData);
  }
};
}