// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Mono::Security::PKCS7 {
struct __ContentInfo_Il2CppStaticFields {
};

struct __ContentInfo_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ContentInfo_Il2CppClass {
  Il2CppClass_1 _1;
  __ContentInfo_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ContentInfo_Il2CppVtbl vtbl;
};

class ContentInfo {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C8F458;
  static inline    __ContentInfo_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ContentInfo_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ContentInfo_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ContentInfo_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* contentType;
  ModdingAPI::Exposed::Mono::Security::ASN1* content;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE807A0))(this);
  }
  void ::ctor(System_String* oid) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE808F0))(this, oid);
  }
  void ::ctor(ModdingAPI::Exposed::System::Byte_array* data) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*, ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE80920))(this, data);
  }
  void ::ctor(ModdingAPI::Exposed::Mono::Security::ASN1* asn1) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*, ModdingAPI::Exposed::Mono::Security::ASN1*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE80A80))(this, asn1);
  }
  ModdingAPI::Exposed::Mono::Security::ASN1* get_ASN1() {
    return reinterpret_cast<ModdingAPI::Exposed::Mono::Security::ASN1*(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE80C90))(this);
  }
  ModdingAPI::Exposed::Mono::Security::ASN1* get_Content() {
    return reinterpret_cast<ModdingAPI::Exposed::Mono::Security::ASN1*(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  void set_Content(ModdingAPI::Exposed::Mono::Security::ASN1* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*, ModdingAPI::Exposed::Mono::Security::ASN1*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A3E0))(this, value);
  }
  System_String* get_ContentType() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  void set_ContentType(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30D060))(this, value);
  }
  ModdingAPI::Exposed::Mono::Security::ASN1* GetASN1() {
    return reinterpret_cast<ModdingAPI::Exposed::Mono::Security::ASN1*(__fastcall*)(ModdingAPI::Exposed::Mono::Security::PKCS7::ContentInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE80CA0))(this);
  }
};
}