// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm {
struct __MessageBase_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Byte_array* header;
};

struct __MessageBase_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Decode;
  VirtualInvokeData _65535__ctor;
};

struct __MessageBase_Il2CppClass {
  Il2CppClass_1 _1;
  __MessageBase_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __MessageBase_Il2CppVtbl vtbl;
};

class MessageBase {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C953F0;
  static inline    __MessageBase_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __MessageBase_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__MessageBase_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __MessageBase_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t _type;
  int32_t _flags;

  // Member methods:
  void ::ctor(int32_t messageType) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311070))(this, messageType);
  }
  int32_t get_Flags() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311080))(this);
  }
  void set_Flags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEBD0))(this, value);
  }
  int32_t get_Type() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311060))(this);
  }
  ModdingAPI::Exposed::System::Byte_array* PrepareMessage(int32_t messageSize) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Byte_array*(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11C6DC0))(this, messageSize);
  }
  void Decode(ModdingAPI::Exposed::System::Byte_array* message) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*, ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11C6F30))(this, message);
  }
  bool CheckHeader(ModdingAPI::Exposed::System::Byte_array* message) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Mono::Security::Protocol::Ntlm::MessageBase*, ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11C7240))(this, message);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Byte_array*> header = __CppStaticProperty<ModdingAPI::Exposed::System::Byte_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->header; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x11C73E0))();
  }
};
}