// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppStaticFields {
};

struct __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_MarshalFrom;
};

struct __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppClass {
  Il2CppClass_1 _1;
  __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppVtbl vtbl;
};

class MwHGXqadpzTBaUlpBgwPIbZdHsSS {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C30B80;
  static inline    __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __MwHGXqadpzTBaUlpBgwPIbZdHsSS_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t uUTeuhXMfnVkoqLDEfTThgUkrw;
  int32_t lutBJgpeyOaDCpCCORNrWMKhPWP;
  int32_t CuaWvhKVQVjrejZygFiFeKXfFkGi;
  int32_t cQyAYbingTlbjdSASOyVymZByfWh;
  int32_t ldhJiKHnmIyTcgRmvFTLGgZukmFK;
  int32_t FGWpwiSDUPdyXhjbmBsmgdFNpyGn;
  ModdingAPI::Exposed::System::Int32_array* JSDfobKsweeidNUXWOmaBIniWui;
  ModdingAPI::Exposed::System::Int32_array* zozcwvKeWGUUjxgVLHAwlhjnZcH;
  ModdingAPI::Exposed::System::Boolean_array* cskvVokjggiNSrJdTDxkdPuWfgj;
  int32_t NeipbxBynpvGRWPPIzFHtQfMiqA;
  int32_t wSvnhjsSmLSiOhcfGDavaQavqxG;
  int32_t inPeGbROCoMWfmJJXfHNiqTePvz;
  int32_t JrQdmgYPyxVNLnNEvmQcrYLiJLj;
  int32_t YbLisaKtzeHAKcdclNphaUgShaXR;
  int32_t OrcHZCkgfGHqxpRhxmfHAZvygLi;
  ModdingAPI::Exposed::System::Int32_array* fPFPfKEOsXIPsohtzbXlDGAAnnIh;
  int32_t qjYOnMeHNgdZYNipaDhafWvobGJ;
  int32_t MwDmnYUjhcDRTcqqhIwpmZWkyAJf;
  int32_t raHlaTGXOfHesUxOTmEkpZRGyVm;
  int32_t hbcAgcKYptkrwoRPCzqScadDGYvH;
  int32_t VlAvrnjpGnpopuiHjcVbApGSlHI;
  int32_t LiCNTUmHNVZAAkUJIEAJGVMfcWZ;
  ModdingAPI::Exposed::System::Int32_array* EEjLQAVnAGqKNmQHtJxSMjouAJ;
  int32_t DoiyTkgqnVIYhfJhMozigPqIIkQi;
  int32_t tWpMPsTFJxKhuVjJrQfnZqUTVcu;
  int32_t LBcJKnwHytZFJTQZkjsGiaxxMyY;
  int32_t QzqBdOMRpAaizuPNRTcxFdERHQmA;
  int32_t HCKxXLPacNExcPggcTDqNDThgVk;
  int32_t IynWGqduEdSLpPKYdeyfsqvKXkB;
  ModdingAPI::Exposed::System::Int32_array* yGfOLDAIPCNTyKEtPPosJvfknJN;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3837E0))(this);
  }
  int32_t get_X() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311060))(this);
  }
  void set_X(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311070))(this, value);
  }
  int32_t get_Y() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311080))(this);
  }
  void set_Y(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEBD0))(this, value);
  }
  int32_t get_Z() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FED20))(this);
  }
  void set_Z(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311090))(this, value);
  }
  int32_t get_RotationX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36E9C0))(this);
  }
  void set_RotationX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36E9D0))(this, value);
  }
  int32_t get_RotationY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x37AAE0))(this);
  }
  void set_RotationY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3838E0))(this, value);
  }
  int32_t get_RotationZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x37AAF0))(this);
  }
  void set_RotationZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3838F0))(this, value);
  }
  ModdingAPI::Exposed::System::Int32_array* get_Sliders() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Int32_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110B0))(this);
  }
  void set_Sliders(ModdingAPI::Exposed::System::Int32_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110C0))(this, value);
  }
  ModdingAPI::Exposed::System::Int32_array* get_PointOfViewControllers() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Int32_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335370))(this);
  }
  void set_PointOfViewControllers(ModdingAPI::Exposed::System::Int32_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A410))(this, value);
  }
  ModdingAPI::Exposed::System::Boolean_array* get_Buttons() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Boolean_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319970))(this);
  }
  void set_Buttons(ModdingAPI::Exposed::System::Boolean_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Boolean_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A420))(this, value);
  }
  int32_t get_VelocityX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D8E0))(this);
  }
  void set_VelocityX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D8F0))(this, value);
  }
  int32_t get_VelocityY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D900))(this);
  }
  void set_VelocityY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D910))(this, value);
  }
  int32_t get_VelocityZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383900))(this);
  }
  void set_VelocityZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383910))(this, value);
  }
  int32_t get_AngularVelocityX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383920))(this);
  }
  void set_AngularVelocityX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383930))(this, value);
  }
  int32_t get_AngularVelocityY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319990))(this);
  }
  void set_AngularVelocityY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383940))(this, value);
  }
  int32_t get_AngularVelocityZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3199A0))(this);
  }
  void set_AngularVelocityZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383950))(this, value);
  }
  ModdingAPI::Exposed::System::Int32_array* get_VelocitySliders() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Int32_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383960))(this);
  }
  void set_VelocitySliders(ModdingAPI::Exposed::System::Int32_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383970))(this, value);
  }
  int32_t get_AccelerationX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383980))(this);
  }
  void set_AccelerationX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383990))(this, value);
  }
  int32_t get_AccelerationY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839A0))(this);
  }
  void set_AccelerationY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839B0))(this, value);
  }
  int32_t get_AccelerationZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839C0))(this);
  }
  void set_AccelerationZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839D0))(this, value);
  }
  int32_t get_AngularAccelerationX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839E0))(this);
  }
  void set_AngularAccelerationX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3839F0))(this, value);
  }
  int32_t get_AngularAccelerationY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A00))(this);
  }
  void set_AngularAccelerationY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A10))(this, value);
  }
  int32_t get_AngularAccelerationZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A20))(this);
  }
  void set_AngularAccelerationZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A30))(this, value);
  }
  ModdingAPI::Exposed::System::Int32_array* get_AccelerationSliders() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Int32_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319950))(this);
  }
  void set_AccelerationSliders(ModdingAPI::Exposed::System::Int32_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A40))(this, value);
  }
  int32_t get_ForceX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x307620))(this);
  }
  void set_ForceX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x308500))(this, value);
  }
  int32_t get_ForceY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x307630))(this);
  }
  void set_ForceY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A50))(this, value);
  }
  int32_t get_ForceZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A60))(this);
  }
  void set_ForceZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A70))(this, value);
  }
  int32_t get_TorqueX() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A80))(this);
  }
  void set_TorqueX(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383A90))(this, value);
  }
  int32_t get_TorqueY() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383AA0))(this);
  }
  void set_TorqueY(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383AB0))(this, value);
  }
  int32_t get_TorqueZ() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383AC0))(this);
  }
  void set_TorqueZ(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383AD0))(this, value);
  }
  ModdingAPI::Exposed::System::Int32_array* get_ForceSliders() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Int32_array*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319850))(this);
  }
  void set_ForceSliders(ModdingAPI::Exposed::System::Int32_array* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319860))(this, value);
  }
  void MarshalFrom(intptr_t ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383AE0))(this, );
  }
  void ImiTvEABohovgrbMFdTXVXuzrfz(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS* ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*, ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383EC0))(this, );
  }
  void gddVFErzcspUTrtpOgUHPGMafbe() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x384380))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::MwHGXqadpzTBaUlpBgwPIbZdHsSS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x384670))(this);
  }
};
}