// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __Panel_IceFishingHoleClear_Il2CppStaticFields {
};

struct __Panel_IceFishingHoleClear_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __Panel_IceFishingHoleClear_Il2CppClass {
  Il2CppClass_1 _1;
  __Panel_IceFishingHoleClear_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Panel_IceFishingHoleClear_Il2CppVtbl vtbl;
};

class Panel_IceFishingHoleClear {
public:
  // Il2Cpp fields:
  __Panel_IceFishingHoleClear_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_UsableToolItems;
  ModdingAPI::Exposed::ButtonLegendContainer* m_ButtonLegendContainer;
  ModdingAPI::Exposed::ScrollList* m_ScrollList;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_ButtonLeft;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_ButtonRight;
  ModdingAPI::Exposed::TweenAlpha* m_LabelTween;
  ModdingAPI::Exposed::UILabel* m_UseLabel;
  ModdingAPI::Exposed::UILabel* m_ToolNameLabel;
  float m_ProgressBarSeconds;
  ModdingAPI::Exposed::GearItem* m_ToolUsed;
  ModdingAPI::Exposed::IceFishingHole* m_IceFishingHole;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_AvailableTools;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_CoverflowItems;
  bool m_IsClearingIce;

  // Member methods:
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994450))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19945B0))(this);
  }
  void NextTool() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994910))(this);
  }
  void PrevTool() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994A90))(this);
  }
  void SelectToolByIndex(int32_t index) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994C10))(this, index);
  }
  void Launch(ModdingAPI::Exposed::IceFishingHole* ifh) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*, ModdingAPI::Exposed::IceFishingHole*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994D70))(this, ifh);
  }
  void Enable(bool enable) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1994DA0))(this, enable);
  }
  bool IsEnabled() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x165DF10))(this);
  }
  void OnBreakIce() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995020))(this);
  }
  void OnCancel() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19950E0))(this);
  }
  void OnBreakIceComplete(bool success, bool playerCancel, float progress) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*, bool, bool, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995190))(this, success, playerCancel, progress);
  }
  bool IsClearingIce() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x7F6490))(this);
  }
  void UseTool(ModdingAPI::Exposed::GearItem* gi) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*, ModdingAPI::Exposed::GearItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995450))(this, gi);
  }
  void RefreshVisuals() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995830))(this);
  }
  void UpdateButtonLegend() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995A90))(this);
  }
  void SetupScrollList() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1995BB0))(this);
  }
  void AddAlternateTools() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x19960C0))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Panel_IceFishingHoleClear*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1996350))(this);
  }
};
}