// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Rect.hpp"
#include "ModdingAPI::Exposed::UnityEngine::Rect.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"
#include "ModdingAPI::Exposed::UnityEngine::Vector2.hpp"


namespace ModdingAPI::Exposed::ParadoxNotion {
struct __RectUtils_Il2CppStaticFields {
};

struct __RectUtils_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __RectUtils_Il2CppClass {
  Il2CppClass_1 _1;
  __RectUtils_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __RectUtils_Il2CppVtbl vtbl;
};

class RectUtils {
public:
  // Il2Cpp fields:
  __RectUtils_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static methods:
  static inline ModdingAPI::Exposed::UnityEngine::Rect GetBoundRect(ModdingAPI::Exposed::UnityEngine::Rect_array* rects) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240C550))(rects);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rect GetBoundRect(ModdingAPI::Exposed::UnityEngine::Vector2_array* positions) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Vector2_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240C740))(positions);
  }
  static inline bool Encapsulates(ModdingAPI::Exposed::UnityEngine::Rect a, ModdingAPI::Exposed::UnityEngine::Rect b) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect, ModdingAPI::Exposed::UnityEngine::Rect)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240C910))(a, b);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rect ExpandBy(ModdingAPI::Exposed::UnityEngine::Rect rect, float margin) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240C960))(rect, margin);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rect ExpandBy(ModdingAPI::Exposed::UnityEngine::Rect rect, float xMargin, float yMargin) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240C9D0))(rect, xMargin, yMargin);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rect ExpandBy(ModdingAPI::Exposed::UnityEngine::Rect rect, float left, float top, float right, float bottom) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect, float, float, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240CA50))(rect, left, top, right, bottom);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rect TransformSpace(ModdingAPI::Exposed::UnityEngine::Rect rect, ModdingAPI::Exposed::UnityEngine::Rect oldContainer, ModdingAPI::Exposed::UnityEngine::Rect newContainer) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rect(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rect, ModdingAPI::Exposed::UnityEngine::Rect, ModdingAPI::Exposed::UnityEngine::Rect)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240CAB0))(rect, oldContainer, newContainer);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Vector2 TransformSpace(ModdingAPI::Exposed::UnityEngine::Vector2 vector, ModdingAPI::Exposed::UnityEngine::Rect oldContainer, ModdingAPI::Exposed::UnityEngine::Rect newContainer) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector2(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Rect, ModdingAPI::Exposed::UnityEngine::Rect)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240CCE0))(vector, oldContainer, newContainer);
  }
};
}