// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::ParadoxNotion {
struct __ReflectionTools_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Reflection::Assembly_array* _loadedAssemblies;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* typeMap;
  ModdingAPI::Exposed::System::Type_array* _allTypes;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _subTypesMap;
  ModdingAPI::Exposed::System::Object_array* _tempArgs;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* op_FriendlyNamesLong;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* op_FriendlyNamesShort;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* op_CSharpAliases;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* cacheSignatures;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeConstructors;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeMethods;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeFields;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeProperties;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeEvents;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeAttributes;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _memberAttributes;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* _typeExtensions;
};

struct __ReflectionTools_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ReflectionTools_Il2CppClass {
  Il2CppClass_1 _1;
  __ReflectionTools_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ReflectionTools_Il2CppVtbl vtbl;
};

class ReflectionTools {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C274C0;
  static inline    __ReflectionTools_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ReflectionTools_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ReflectionTools_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ReflectionTools_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Reflection::Assembly_array*> _loadedAssemblies = __CppStaticProperty<ModdingAPI::Exposed::System::Reflection::Assembly_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_loadedAssemblies; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> typeMap = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->typeMap; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Type_array*> _allTypes = __CppStaticProperty<ModdingAPI::Exposed::System::Type_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_allTypes; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _subTypesMap = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_subTypesMap; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Object_array*> _tempArgs = __CppStaticProperty<ModdingAPI::Exposed::System::Object_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_tempArgs; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> op_FriendlyNamesLong = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->op_FriendlyNamesLong; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> op_FriendlyNamesShort = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->op_FriendlyNamesShort; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> op_CSharpAliases = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->op_CSharpAliases; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> cacheSignatures = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->cacheSignatures; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeConstructors = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeConstructors; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeMethods = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeMethods; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeFields = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeFields; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeProperties = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeProperties; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeEvents = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeEvents; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeAttributes = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeAttributes; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _memberAttributes = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_memberAttributes; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> _typeExtensions = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_typeExtensions; }
  );

  // Static methods:
  static inline ModdingAPI::Exposed::System::Reflection::Assembly_array* get_loadedAssemblies() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::Assembly_array*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x240CE20))();
  }
  static inline ModdingAPI::Exposed::System::Type* GetType(System_String* typeFullName) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240D030))(typeFullName);
  }
  static inline ModdingAPI::Exposed::System::Type* GetType(System_String* typeFullName, ModdingAPI::Exposed::System::Type* fallbackAssignable) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240D0D0))(typeFullName, fallbackAssignable);
  }
  static inline ModdingAPI::Exposed::System::Type* GetType(System_String* typeFullName, bool fallbackNoNamespace, ModdingAPI::Exposed::System::Type* fallbackAssignable) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*, bool, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240D180))(typeFullName, fallbackNoNamespace, fallbackAssignable);
  }
  static inline ModdingAPI::Exposed::System::Type* GetTypeDirect(System_String* typeFullName) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240D630))(typeFullName);
  }
  static inline ModdingAPI::Exposed::System::Type* TryResolveGenericType(System_String* typeFullName, bool fallbackNoNamespace, ModdingAPI::Exposed::System::Type* fallbackAssignable) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*, bool, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240D810))(typeFullName, fallbackNoNamespace, fallbackAssignable);
  }
  static inline ModdingAPI::Exposed::System::Type* TryResolveDeserializeFromAttribute(System_String* typeName) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240DF30))(typeName);
  }
  static inline ModdingAPI::Exposed::System::Type* TryResolveWithoutNamespace(System_String* typeName, ModdingAPI::Exposed::System::Type* fallbackAssignable) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240E250))(typeName, fallbackAssignable);
  }
  static inline ModdingAPI::Exposed::System::Type_array* GetAllTypes(bool includeObsolete) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)(bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240E670))(includeObsolete);
  }
  static inline ModdingAPI::Exposed::System::Type_array* GetImplementationsOf(ModdingAPI::Exposed::System::Type* baseType) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240EFE0))(baseType);
  }
  static inline ModdingAPI::Exposed::System::Object_array* SingleTempArgsArray(Il2CppObject* arg) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Object_array*(__fastcall*)(Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240F390))(arg);
  }
  static inline int32_t GetMethodSpecialType(ModdingAPI::Exposed::System::Reflection::MethodBase* method) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240F4A0))(method);
  }
  static inline System_String* FriendlyName(ModdingAPI::Exposed::System::Type* t, bool compileSafe) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Type*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240F610))(t, compileSafe);
  }
  static inline System_String* FriendlyName(ModdingAPI::Exposed::System::Reflection::MemberInfo* info) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MemberInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240FAA0))(info);
  }
  static inline System_String* FriendlyName(ModdingAPI::Exposed::System::Reflection::MethodBase* method) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240FCB0))(method);
  }
  static inline System_String* FriendlyName(ModdingAPI::Exposed::System::Reflection::MethodBase* method, int32_t specialNameType) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodBase*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x240FD60))(method, specialNameType);
  }
  static inline System_String* SignatureName(ModdingAPI::Exposed::System::Reflection::MethodBase* method) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodBase*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410120))(method);
  }
  static inline ModdingAPI::Exposed::System::Type* RTReflectedOrDeclaredType(ModdingAPI::Exposed::System::Reflection::MemberInfo* member) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MemberInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24106B0))(member);
  }
  static inline bool RTIsAssignableFrom(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type* other) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24107A0))(type, other);
  }
  static inline bool RTIsAssignableTo(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type* other) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24107D0))(type, other);
  }
  static inline bool RTIsAbstract(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xDA6A30))(type);
  }
  static inline bool RTIsValueType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x649930))(type);
  }
  static inline bool RTIsArray(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xA17CC0))(type);
  }
  static inline bool RTIsInterface(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x142FF20))(type);
  }
  static inline bool RTIsSubclassOf(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type* other) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410890))(type, other);
  }
  static inline bool RTIsGenericParameter(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24108C0))(type);
  }
  static inline bool RTIsGenericType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x142FF40))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo* RTGetGetMethod(ModdingAPI::Exposed::System::Reflection::PropertyInfo* prop) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6499C0))(prop);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo* RTGetSetMethod(ModdingAPI::Exposed::System::Reflection::PropertyInfo* prop) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24108F0))(prop);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo* RTGetDelegateMethodInfo(ModdingAPI::Exposed::System::Delegate* del) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Delegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x14DD5B0))(del);
  }
  static inline ModdingAPI::Exposed::System::Type* RTMakeGenericType(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type_array* typeArgs) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410920))(type, typeArgs);
  }
  static inline ModdingAPI::Exposed::System::Type_array* RTGetGenericArguments(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x649A50))(type);
  }
  static inline ModdingAPI::Exposed::System::Type_array* RTGetEmptyTypes() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410950))();
  }
  static inline ModdingAPI::Exposed::System::Type* RTGetElementType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24109F0))(type);
  }
  static inline bool RTIsByRef(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410AA0))(type);
  }
  static inline Il2CppObject* CreateObject(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410B50))(type);
  }
  static inline Il2CppObject* CreateObjectUninitialized(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410C00))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::ConstructorInfo* RTGetDefaultConstructor(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::ConstructorInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410CD0))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::ConstructorInfo* RTGetConstructor(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type_array* paramTypes) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::ConstructorInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2410E10))(type, paramTypes);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo* RTGetMethod(ModdingAPI::Exposed::System::Type* type, System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411020))(type, name);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo* RTGetMethod(ModdingAPI::Exposed::System::Type* type, System_String* name, ModdingAPI::Exposed::System::Type_array* paramTypes) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, System_String*, ModdingAPI::Exposed::System::Type_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411180))(type, name, paramTypes);
  }
  static inline ModdingAPI::Exposed::System::Reflection::FieldInfo* RTGetField(ModdingAPI::Exposed::System::Type* type, System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::FieldInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24113E0))(type, name);
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo* RTGetProperty(ModdingAPI::Exposed::System::Type* type, System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411540))(type, name);
  }
  static inline ModdingAPI::Exposed::System::Reflection::EventInfo* RTGetEvent(ModdingAPI::Exposed::System::Type* type, System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::EventInfo*(__fastcall*)(ModdingAPI::Exposed::System::Type*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24116A0))(type, name);
  }
  static inline ModdingAPI::Exposed::System::Reflection::ConstructorInfo_array* RTGetConstructors(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::ConstructorInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411800))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo_array* RTGetMethods(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24119C0))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::FieldInfo_array* RTGetFields(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::FieldInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411B80))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo_array* RTGetProperties(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411D40))(type);
  }
  static inline ModdingAPI::Exposed::System::Reflection::EventInfo_array* RTGetEvents(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::EventInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2411F00))(type);
  }
  static inline bool RTIsDefined(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type* attributeType, bool inherited) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24120C0))(type, attributeType, inherited);
  }
  static inline bool RTIsDefined(ModdingAPI::Exposed::System::Reflection::MemberInfo* member, ModdingAPI::Exposed::System::Type* attributeType, bool inherited) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MemberInfo*, ModdingAPI::Exposed::System::Type*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24120C0))(member, attributeType, inherited);
  }
  static inline ModdingAPI::Exposed::System::Reflection::ParameterInfo_array* RTGetDelegateTypeParameters(ModdingAPI::Exposed::System::Type* delegateType) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::ParameterInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24120F0))(delegateType);
  }
  static inline ModdingAPI::Exposed::System::Delegate* RTCreateDelegate(ModdingAPI::Exposed::System::Reflection::MethodInfo* method, ModdingAPI::Exposed::System::Type* type, Il2CppObject* instance) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Delegate*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*, ModdingAPI::Exposed::System::Type*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412270))(method, type, instance);
  }
  static inline ModdingAPI::Exposed::System::Delegate* ConvertDelegate(ModdingAPI::Exposed::System::Delegate* originalDelegate, ModdingAPI::Exposed::System::Type* targetDelegateType) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Delegate*(__fastcall*)(ModdingAPI::Exposed::System::Delegate*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412570))(originalDelegate, targetDelegateType);
  }
  static inline bool IsReadOnly(ModdingAPI::Exposed::System::Reflection::FieldInfo* field) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::FieldInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24125D0))(field);
  }
  static inline bool IsConstant(ModdingAPI::Exposed::System::Reflection::FieldInfo* field) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::FieldInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412620))(field);
  }
  static inline bool IsStatic(ModdingAPI::Exposed::System::Reflection::EventInfo* info) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::EventInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412710))(info);
  }
  static inline bool IsParams(ModdingAPI::Exposed::System::Reflection::ParameterInfo* parameter, ModdingAPI::Exposed::System::Reflection::ParameterInfo_array* parameters) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::ParameterInfo*, ModdingAPI::Exposed::System::Reflection::ParameterInfo_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412790))(parameter, parameters);
  }
  static inline bool IsObsolete(ModdingAPI::Exposed::System::Reflection::MemberInfo* member, bool inherited) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MemberInfo*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24128A0))(member, inherited);
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo* GetBaseDefinition(ModdingAPI::Exposed::System::Reflection::PropertyInfo* propertyInfo) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412B40))(propertyInfo);
  }
  static inline ModdingAPI::Exposed::System::Reflection::FieldInfo* GetBaseDefinition(ModdingAPI::Exposed::System::Reflection::FieldInfo* fieldInfo) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::FieldInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::FieldInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412EB0))(fieldInfo);
  }
  static inline ModdingAPI::Exposed::System::Reflection::MethodInfo_array* GetExtensionMethods(ModdingAPI::Exposed::System::Type* targetType) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2412F90))(targetType);
  }
  static inline bool IsExtensionMethod(ModdingAPI::Exposed::System::Reflection::MethodInfo* method) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24134B0))(method);
  }
  static inline bool IsPropertyAccessor(ModdingAPI::Exposed::System::Reflection::MethodInfo* method) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413550))(method);
  }
  static inline bool IsIndexerProperty(ModdingAPI::Exposed::System::Reflection::PropertyInfo* property) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413720))(property);
  }
  static inline bool IsAutoProperty(ModdingAPI::Exposed::System::Reflection::PropertyInfo* property) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413760))(property);
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo* GetAccessorProperty(ModdingAPI::Exposed::System::Reflection::MethodInfo* method) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24138D0))(method);
  }
  static inline bool IsEnumerableCollection(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413A00))(type);
  }
  static inline ModdingAPI::Exposed::System::Type* GetEnumerableElementType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413BA0))(type);
  }
  static inline ModdingAPI::Exposed::System::Type* GetFirstGenericParameterConstraintType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413DD0))(type);
  }
  static inline ModdingAPI::Exposed::System::Type* GetFirstGenericParameterConstraintType(ModdingAPI::Exposed::System::Reflection::MethodInfo* method) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2413F80))(method);
  }
  static inline bool CanBeMadeGenericWith(ModdingAPI::Exposed::System::Type* def, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2414160))(def, type);
  }
  static inline bool CanBeMadeGenericWith(ModdingAPI::Exposed::System::Reflection::MethodInfo* def, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::MethodInfo*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24142C0))(def, type);
  }
  static inline bool IsAllowedByGenericArgument(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Type* genericArgument) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2414440))(type, genericArgument);
  }
  static inline ModdingAPI::Exposed::System::Array* Resize(ModdingAPI::Exposed::System::Array* array, int32_t newSize) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Array*(__fastcall*)(ModdingAPI::Exposed::System::Array*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2414880))(array, newSize);
  }
  static inline bool CanConvert(ModdingAPI::Exposed::System::Type* fromType, ModdingAPI::Exposed::System::Type* toType, ModdingAPI::Exposed::System::Linq::Expressions::UnaryExpression* exp) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Linq::Expressions::UnaryExpression*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24149A0))(fromType, toType, exp);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x2414B00))();
  }
};
}