// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"


namespace ModdingAPI::Exposed::Pathfinding {
struct __MineBotAI_Il2CppStaticFields {
};

struct __MineBotAI_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Awake;
  VirtualInvokeData _5_Start;
  VirtualInvokeData _6_OnEnable;
  VirtualInvokeData _7_SearchPath;
  VirtualInvokeData _8_OnTargetReached;
  VirtualInvokeData _9_OnPathComplete;
  VirtualInvokeData _10_GetFeetPosition;
  VirtualInvokeData _11_Update;
  VirtualInvokeData _12_RotateTowards;
};

struct __MineBotAI_Il2CppClass {
  Il2CppClass_1 _1;
  __MineBotAI_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __MineBotAI_Il2CppVtbl vtbl;
};

class MineBotAI {
public:
  // Il2Cpp fields:
  __MineBotAI_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  float repathRate;
  ModdingAPI::Exposed::UnityEngine::Transform* target;
  bool canSearch;
  bool canMove;
  float speed;
  float turningSpeed;
  float slowdownDistance;
  float pickNextWaypointDist;
  float forwardLook;
  float endReachedDistance;
  bool closestOnPathCheck;
  float minMoveScale;
  ModdingAPI::Exposed::Seeker* seeker;
  ModdingAPI::Exposed::UnityEngine::Transform* tr;
  float lastRepath;
  ModdingAPI::Exposed::Pathfinding::Path* path;
  ModdingAPI::Exposed::UnityEngine::CharacterController* controller;
  ModdingAPI::Exposed::Pathfinding::RVO::RVOController* rvoController;
  ModdingAPI::Exposed::UnityEngine::Rigidbody* rigid;
  int32_t currentWaypointIndex;
  bool targetReached;
  bool canSearchAgain;
  ModdingAPI::Exposed::UnityEngine::Vector3 lastFoundWaypointPosition;
  float lastFoundWaypointTime;
  bool AIPath_startHasRun;
  ModdingAPI::Exposed::UnityEngine::Vector3 targetPoint;
  ModdingAPI::Exposed::UnityEngine::Vector3 targetDirection;
  ModdingAPI::Exposed::UnityEngine::Animation* anim;
  float sleepVelocity;
  float animationSpeed;
  ModdingAPI::Exposed::UnityEngine::GameObject* endOfPathEffect;
  ModdingAPI::Exposed::UnityEngine::Vector3 lastTarget;

  // Member methods:
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::MineBotAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25C51B0))(this);
  }
  void OnTargetReached() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::MineBotAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25C55A0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Vector3 GetFeetPosition() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector3(__fastcall*)(ModdingAPI::Exposed::Pathfinding::MineBotAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25C58E0))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::MineBotAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25C5970))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::MineBotAI*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25C5EF0))(this);
  }
};
}