// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.Pathfinding.Int3.hpp"


namespace ModdingAPI::Exposed::Pathfinding {
struct __PointNode_Il2CppStaticFields {
};

struct __PointNode_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_UpdateRecursiveG;
  VirtualInvokeData _5_FloodFill;
  VirtualInvokeData _6_GetConnections;
  VirtualInvokeData _7_AddConnection;
  VirtualInvokeData _8_RemoveConnection;
  VirtualInvokeData _9_ClearConnections;
  VirtualInvokeData _10_ContainsConnection;
  VirtualInvokeData _11_RecalculateConnectionCosts;
  VirtualInvokeData _12_GetPortal;
  VirtualInvokeData _13_Open;
  VirtualInvokeData _14_SerializeNode;
  VirtualInvokeData _15_DeserializeNode;
  VirtualInvokeData _16_SerializeReferences;
  VirtualInvokeData _17_DeserializeReferences;
};

struct __PointNode_Il2CppClass {
  Il2CppClass_1 _1;
  __PointNode_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __PointNode_Il2CppVtbl vtbl;
};

class PointNode {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C86448;
  static inline    __PointNode_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __PointNode_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__PointNode_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __PointNode_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t GraphNode_nodeIndex;
  uint32_t flags;
  uint32_t GraphNode_penalty;
  ModdingAPI::Exposed::Pathfinding::Int3 position;
  ModdingAPI::Exposed::Pathfinding::GraphNode_array* connections;
  ModdingAPI::Exposed::System::UInt32_array* connectionCosts;
  ModdingAPI::Exposed::UnityEngine::GameObject* gameObject;
  ModdingAPI::Exposed::Pathfinding::PointNode* next;

  // Member methods:
  void SetPosition(ModdingAPI::Exposed::Pathfinding::Int3 value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Int3)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550720))(this, value);
  }
  void ::ctor(ModdingAPI::Exposed::AstarPath* astar) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::AstarPath*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x24432F0))(this, astar);
  }
  void GetConnections(ModdingAPI::Exposed::Pathfinding::GraphNodeDelegate* del) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::GraphNodeDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550730))(this, del);
  }
  void ClearConnections(bool alsoReverse) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25507D0))(this, alsoReverse);
  }
  void UpdateRecursiveG(ModdingAPI::Exposed::Pathfinding::Path* path, ModdingAPI::Exposed::Pathfinding::PathNode* pathNode, ModdingAPI::Exposed::Pathfinding::PathHandler* handler) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Path*, ModdingAPI::Exposed::Pathfinding::PathNode*, ModdingAPI::Exposed::Pathfinding::PathHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550870))(this, path, pathNode, handler);
  }
  bool ContainsConnection(ModdingAPI::Exposed::Pathfinding::GraphNode* node) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::GraphNode*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550A00))(this, node);
  }
  void AddConnection(ModdingAPI::Exposed::Pathfinding::GraphNode* node, uint32_t cost) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::GraphNode*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550A60))(this, node, cost);
  }
  void RemoveConnection(ModdingAPI::Exposed::Pathfinding::GraphNode* node) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::GraphNode*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2550D50))(this, node);
  }
  void Open(ModdingAPI::Exposed::Pathfinding::Path* path, ModdingAPI::Exposed::Pathfinding::PathNode* pathNode, ModdingAPI::Exposed::Pathfinding::PathHandler* handler) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Path*, ModdingAPI::Exposed::Pathfinding::PathNode*, ModdingAPI::Exposed::Pathfinding::PathHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2551030))(this, path, pathNode, handler);
  }
  void SerializeNode(ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext* ctx) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2551300))(this, ctx);
  }
  void DeserializeNode(ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext* ctx) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x25513A0))(this, ctx);
  }
  void SerializeReferences(ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext* ctx) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2551460))(this, ctx);
  }
  void DeserializeReferences(ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext* ctx) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Pathfinding::PointNode*, ModdingAPI::Exposed::Pathfinding::Serialization::GraphSerializationContext*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2551600))(this, ctx);
  }
};
}