// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Quaternion.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"


namespace ModdingAPI::Exposed {
struct __PlayerInVehicle_Il2CppStaticFields {
};

struct __PlayerInVehicle_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __PlayerInVehicle_Il2CppClass {
  Il2CppClass_1 _1;
  __PlayerInVehicle_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __PlayerInVehicle_Il2CppVtbl vtbl;
};

class PlayerInVehicle {
public:
  // Il2Cpp fields:
  __PlayerInVehicle_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  float m_TempIncrease;
  float m_FOV;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_PitchLimitDegrees;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_YawLimitDegrees;
  float m_FadeOutSeconds;
  float m_FadeInSeconds;
  float m_StartCameraFOV;
  ModdingAPI::Exposed::UnityEngine::Quaternion m_StartCameraRotation;
  bool m_InVehicle;
  bool m_EnteringVehicle;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_StartPitchLimit;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_StartYawLimit;
  float m_TimeLastVehicleInteraction;
  ModdingAPI::Exposed::VehicleDoor* m_VehicleDoorUsed;

  // Member methods:
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  bool BlockSavingWhileInside() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF1A40))(this);
  }
  void EnterVehicle(ModdingAPI::Exposed::VehicleDoor* vd) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, ModdingAPI::Exposed::VehicleDoor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF1B20))(this, vd);
  }
  void ExitVehicle(ModdingAPI::Exposed::VehicleDoor* vd) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, ModdingAPI::Exposed::VehicleDoor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF1DD0))(this, vd);
  }
  bool IsInside() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5DE510))(this);
  }
  bool IsEntering() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5DE5F0))(this);
  }
  float GetTempIncrease() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF2080))(this);
  }
  void OnBedroll(ModdingAPI::Exposed::GearItem* gi) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, ModdingAPI::Exposed::GearItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF2090))(this, gi);
  }
  bool HasInteractedWithVehicleSince(float seconds) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF21F0))(this, seconds);
  }
  void ForceIntoVehicleSilent(ModdingAPI::Exposed::UnityEngine::Vector3 cameraPos) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, ModdingAPI::Exposed::UnityEngine::Vector3)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF2260))(this, cameraPos);
  }
  ModdingAPI::Exposed::UnityEngine::Vector3 GetDropItemLocationForLastDoor() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector3(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF25E0))(this);
  }
  bool HasDropLocationForLastDoor() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF28B0))(this);
  }
  void EnterVehicleAfterFadeOut() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF29A0))(this);
  }
  void EnterVehicleCommon() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF2C60))(this);
  }
  void ExitVehicleAfterFadeOut() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF3870))(this);
  }
  ModdingAPI::Exposed::VehicleDoor* GetVehicleDoorFromCollider(ModdingAPI::Exposed::UnityEngine::Collider* c) {
    return reinterpret_cast<ModdingAPI::Exposed::VehicleDoor*(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*, ModdingAPI::Exposed::UnityEngine::Collider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1DF4540))(this, c);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::PlayerInVehicle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }
};
}