// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Quaternion.hpp"


namespace ModdingAPI::Exposed::ProceduralWorld {
struct __ProceduralTile_Il2CppStaticFields {
};

struct __ProceduralTile_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ProceduralTile_Il2CppClass {
  Il2CppClass_1 _1;
  __ProceduralTile_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ProceduralTile_Il2CppVtbl vtbl;
};

class ProceduralTile {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C5E398;
  static inline    __ProceduralTile_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ProceduralTile_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ProceduralTile_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ProceduralTile_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t x;
  int32_t z;
  ModdingAPI::Exposed::System::Random* rnd;
  bool staticBatching;
  ModdingAPI::Exposed::ProceduralWorld* world;
  bool _destroyed_k__BackingField;
  ModdingAPI::Exposed::UnityEngine::Transform* root;
  ModdingAPI::Exposed::System::Collections::IEnumerator* ie;

  // Member methods:
  bool get_destroyed() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x57C620))(this);
  }
  void set_destroyed(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x57C630))(this, value);
  }
  void ::ctor(ModdingAPI::Exposed::ProceduralWorld* world, int32_t x, int32_t z) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*, ModdingAPI::Exposed::ProceduralWorld*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4800))(this, world, x, z);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* Generate() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4980))(this);
  }
  void ForceFinish() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4AD0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Vector3 RandomInside() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector3(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4C20))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Vector3 RandomInside(float px, float pz) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector3(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4D10))(this, px, pz);
  }
  ModdingAPI::Exposed::UnityEngine::Quaternion RandomYRot() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Quaternion(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4E10))(this);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* InternalGenerate() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D4F50))(this);
  }
  void Destroy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::ProceduralWorld::ProceduralTile*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x17D50A0))(this);
  }
};
}