// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.NTkstniLFIzMdUGpyZGDZKjDmRM.hpp"
#include "ModdingAPI.Exposed.System.Guid.hpp"


namespace ModdingAPI::Exposed {
struct __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppStaticFields {
};

struct __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_get_deviceCount;
  VirtualInvokeData _5_get_primaryInputManager;
  VirtualInvokeData _6_get_inputSource;
  VirtualInvokeData _7_get_inputSourceType;
  VirtualInvokeData _8_Initialize;
  VirtualInvokeData _9_Update;
  VirtualInvokeData _10_OnDestroy;
  VirtualInvokeData _11_SystemDeviceConnected;
  VirtualInvokeData _12_SystemDeviceDisconnected;
  VirtualInvokeData _13_UpdateControllerData;
  VirtualInvokeData _14_GetInputDataUpdateDelegate;
  VirtualInvokeData _15_SetUnityJoystickId;
  VirtualInvokeData _16_GetUnifiedMouseSource;
  VirtualInvokeData _17_GetUnifiedKeyboardSource;
  VirtualInvokeData _18_set_useXInput;
};

struct __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppClass {
  Il2CppClass_1 _1;
  __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppVtbl vtbl;
};

class QILIXnPfYBCIYlmZfHBCAbuhLEX {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C91330;
  static inline    __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __QILIXnPfYBCIYlmZfHBCAbuhLEX_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Action_T_* _DeviceConnectedEvent;
  ModdingAPI::Exposed::System::Action_T_* _DeviceDisconnectedEvent;
  ModdingAPI::Exposed::System::Action_T_* _UpdateControllerInfoEvent;
  ModdingAPI::Exposed::System::Action* _SystemDeviceConnectedEvent;
  ModdingAPI::Exposed::System::Action* _SystemDeviceDisconnectedEvent;
  ModdingAPI::Exposed::IPLfZnTSTkygfnjIgIXYuPzZoHQ* zhfbAVXUDnfyNfFHInCkDjtwcaCy;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* TFARBsdzfNTRwBLWCuCUbXiOVev;
  int32_t oTXRbKtUyrIUYACiKgyPrGZlYy;
  ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX::rnNweevrnKfNfNBbqdBuzNaHsUi* AmJUYHoZwPxwSICeUnfMiLaUafg;
  bool xsHuWlcZkmEcjdAiUVpUYCAbKub;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Utility::TimerRealTime* ewNMEDxPnzNnpduSBNrzUYrlCEL;
  ModdingAPI::Exposed::YlogsubuAoaRmtkUViTKiwPBVTo_T_* xcUbaWvhnsjhKjqTUUERGNGRwec;
  int32_t exMUnYdYdVIhxkAkThmAgFpfbnuo;
  ModdingAPI::Exposed::YlogsubuAoaRmtkUViTKiwPBVTo_T_* qexuPJcZpRVmAkIzLaPDzOksOgq;
  ModdingAPI::Exposed::Rewired::Data::ConfigVars* DcDnLoMHAmLcEuHaTSOZBzjvXof;
  bool hCjPQHTarJJPCYShMVjrIkSeakf;
  ModdingAPI::Exposed::System::Action_T1__T2_* ZLpuTQLcMckdKcfdownLInDlDrD;
  ModdingAPI::Exposed::Rewired::PlatformInputManager* LgTsMjyGwQUeotlNMAhnupqKtcQ;
  ModdingAPI::Exposed::AKkseKZlZfbZcaUNANPHdOEaDoz* LXEKvxUdEDopjUxoVZMRadrlAEQ;
  ModdingAPI::Exposed::cIrXRhsnfMaCVjOyFbhPGXoYiSSE* UYfnZcpToNtDvRIGwBdKwSoAnSV;
  bool afHWRsMGQWJeovoQEpAMFVhRXlR;
  bool KGDZXEkMsDEUDWsIsMYiFCdTETK;
  bool zpalIovjZybIRTCNJrIwVlujRdE;
  ModdingAPI::Exposed::System::Func_T__TResult_* uTfmOacRsvJPZmrnUFIcMmGNmjA;
  ModdingAPI::Exposed::System::Func_TResult_* htQaqZACjFCrGHfRVbKQlehAkMuW;

  // Member methods:
  void set_useXInput(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BAF60))(this, value);
  }
  void ::ctor(ModdingAPI::Exposed::Rewired::Data::ConfigVars* configVars, bool useXInput, ModdingAPI::Exposed::System::Func_T__TResult_* getHardwareJoystickMap_InputManager, ModdingAPI::Exposed::System::Func_TResult_* getNewJoystickId, bool handleJoysticks, bool handleUnifiedMouse, bool handleUnifiedKeyboard, bool useCustomDrivers) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::Rewired::Data::ConfigVars*, bool, ModdingAPI::Exposed::System::Func_T__TResult_*, ModdingAPI::Exposed::System::Func_TResult_*, bool, bool, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BAF70))(this, configVars, useXInput, getHardwareJoystickMap_InputManager, getNewJoystickId, handleJoysticks, handleUnifiedMouse, handleUnifiedKeyboard, useCustomDrivers);
  }
  int32_t get_deviceCount() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383900))(this);
  }
  ModdingAPI::Exposed::Rewired::PlatformInputManager* get_primaryInputManager() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::PlatformInputManager*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319850))(this);
  }
  ModdingAPI::Exposed::Rewired::Interfaces::IInputSource* get_inputSource() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::Interfaces::IInputSource*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319970))(this);
  }
  int32_t get_inputSourceType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3029E0))(this);
  }
  void Initialize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BB7C0))(this);
  }
  void Update(int32_t updateLoop) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BBB50))(this, updateLoop);
  }
  void OnDestroy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC0F0))(this);
  }
  ModdingAPI::Exposed::System::Action_T1__T2_* GetInputDataUpdateDelegate() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Action_T1__T2_*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC530))(this);
  }
  void UpdateControllerData(int32_t inputManagerId, ModdingAPI::Exposed::Rewired::ControllerDataUpdater* data) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t, ModdingAPI::Exposed::Rewired::ControllerDataUpdater*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC540))(this, inputManagerId, data);
  }
  void SystemDeviceConnected() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC740))(this);
  }
  void SystemDeviceDisconnected() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC7D0))(this);
  }
  void SetUnityJoystickId(int32_t joystickId, int32_t unityJoystickId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this, joystickId, unityJoystickId);
  }
  ModdingAPI::Exposed::Rewired::Interfaces::IUnifiedMouseSource* GetUnifiedMouseSource() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::Interfaces::IUnifiedMouseSource*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC850))(this);
  }
  ModdingAPI::Exposed::Rewired::Interfaces::IUnifiedKeyboardSource* GetUnifiedKeyboardSource() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::Interfaces::IUnifiedKeyboardSource*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30F140))(this);
  }
  void GwqqVTBkaTtikGZzkqCrgUtwEHr(ModdingAPI::Exposed::NTkstniLFIzMdUGpyZGDZKjDmRM , int32_t ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::NTkstniLFIzMdUGpyZGDZKjDmRM, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this, , );
  }
  void pUexBqoMGZfddKxhwFuZdrUGpCya() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC860))(this);
  }
  void RzXevFQjCKyPEAMcirIVIEbSsUq() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BCAB0))(this);
  }
  void RzXevFQjCKyPEAMcirIVIEbSsUq(ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BCAE0))(this, );
  }
  void yBoFpSaFFtZckmScnhbZoIHikCrj() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BE1A0))(this);
  }
  ModdingAPI::Exposed::System::Collections::Generic::IList_T_* GVHfoSDXjnreXkJPabKWFrBTdSGi() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IList_T_*(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BE330))(this);
  }
  void DkKjGZYbTaaABkrGQJRHqKaWeJYd(int32_t , int32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , ModdingAPI::Exposed::System::Collections::Generic::List_T_* ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BE3F0))(this, , , , );
  }
  bool kXIZuUVbphdhbyVRBDOYGAHewiGe(ModdingAPI::Exposed::System::Collections::Generic::List_T_* , int32_t ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BE930))(this, , );
  }
  int32_t sHgHvNUlNDEtgiccEUJQezkxDeET(ModdingAPI::Exposed::System::Collections::Generic::List_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BEA40))(this, );
  }
  bool eGPNxmWSxYREqQniCWhGYdIodTf(ModdingAPI::Exposed::System::Collections::Generic::List_T_* , int32_t ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BEBC0))(this, , );
  }
  void BRUmSEnluwfqbBXDRHtjDZBCEYq(int32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , int32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , int32_t ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BECE0))(this, , , , , );
  }
  void BEKyypDXfJoHglzxwudprhZNBJz(int32_t , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , int32_t ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, int32_t, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BEF80))(this, , , );
  }
  void qNLNTeiuZEFNIZFwcFaJRaUjbRMJ() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BF200))(this);
  }
  void aIQxPNRqfrJJOCgBhQIOMtMpVWX() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BF440))(this);
  }
  void JUJAbGkAQZpkUpLwNbXbkKNxkSUq() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BF520))(this);
  }
  bool otYgrfBoVLKzVrjdVoLuhuzguZpF(ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BF590))(this, );
  }
  bool jZnCRoYAGnCHnfHgOpnweoeHTRQ(ModdingAPI::Exposed::System::Guid ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Guid)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BF950))(this, );
  }
  bool EQvetRgIsBrPPETTbxXCHgYppLbc(ModdingAPI::Exposed::System::Collections::Generic::IList_T_* , ModdingAPI::Exposed::System::Guid ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*, ModdingAPI::Exposed::System::Guid)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BFB40))(this, , );
  }
  void SRBeCMdHVOrGvUhqoeVfvKtCVyd(ModdingAPI::Exposed::System::Collections::Generic::List_T_* , ModdingAPI::Exposed::System::Collections::Generic::List_T_* , bool ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BFCE0))(this, , , );
  }
  void uXjFPmfdWSGeyzFLPmoaFfYhRWv(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX::BKgcynLpjwPDFnnfQbHQvuawDtl* , bool ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX::BKgcynLpjwPDFnnfQbHQvuawDtl*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3C0010))(this, , );
  }
  void hUwbOzAOJFzvaofqCZEjNnaJOqMh(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX::BKgcynLpjwPDFnnfQbHQvuawDtl* ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX*, ModdingAPI::Exposed::QILIXnPfYBCIYlmZfHBCAbuhLEX::BKgcynLpjwPDFnnfQbHQvuawDtl*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3C0290))(this, );
  }
};
}