// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Guid.hpp"


namespace ModdingAPI::Exposed::Rewired {
struct __FlightYokeTemplate_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Guid typeGuid;
};

struct __FlightYokeTemplate_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Rewired_IControllerTemplate_get_controller;
  VirtualInvokeData _5_Rewired_IControllerTemplate_get_name;
  VirtualInvokeData _6_Rewired_IControllerTemplate_get_typeGuid;
  VirtualInvokeData _7_Rewired_IControllerTemplate_get_elements;
  VirtualInvokeData _8_Rewired_IControllerTemplate_get_elementCount;
  VirtualInvokeData _9_Rewired_IControllerTemplate_GetElement;
  VirtualInvokeData _10_Rewired_IControllerTemplate_GetElement;
  VirtualInvokeData _11_Rewired_IControllerTemplate_GetElementTargets;
  VirtualInvokeData _12_Rewired_IFlightYokeTemplate_get_leftPaddle;
  VirtualInvokeData _13_Rewired_IFlightYokeTemplate_get_rightPaddle;
  VirtualInvokeData _14_Rewired_IFlightYokeTemplate_get_leftGripButton1;
  VirtualInvokeData _15_Rewired_IFlightYokeTemplate_get_leftGripButton2;
  VirtualInvokeData _16_Rewired_IFlightYokeTemplate_get_leftGripButton3;
  VirtualInvokeData _17_Rewired_IFlightYokeTemplate_get_leftGripButton4;
  VirtualInvokeData _18_Rewired_IFlightYokeTemplate_get_leftGripButton5;
  VirtualInvokeData _19_Rewired_IFlightYokeTemplate_get_leftGripButton6;
  VirtualInvokeData _20_Rewired_IFlightYokeTemplate_get_rightGripButton1;
  VirtualInvokeData _21_Rewired_IFlightYokeTemplate_get_rightGripButton2;
  VirtualInvokeData _22_Rewired_IFlightYokeTemplate_get_rightGripButton3;
  VirtualInvokeData _23_Rewired_IFlightYokeTemplate_get_rightGripButton4;
  VirtualInvokeData _24_Rewired_IFlightYokeTemplate_get_rightGripButton5;
  VirtualInvokeData _25_Rewired_IFlightYokeTemplate_get_rightGripButton6;
  VirtualInvokeData _26_Rewired_IFlightYokeTemplate_get_centerButton1;
  VirtualInvokeData _27_Rewired_IFlightYokeTemplate_get_centerButton2;
  VirtualInvokeData _28_Rewired_IFlightYokeTemplate_get_centerButton3;
  VirtualInvokeData _29_Rewired_IFlightYokeTemplate_get_centerButton4;
  VirtualInvokeData _30_Rewired_IFlightYokeTemplate_get_centerButton5;
  VirtualInvokeData _31_Rewired_IFlightYokeTemplate_get_centerButton6;
  VirtualInvokeData _32_Rewired_IFlightYokeTemplate_get_centerButton7;
  VirtualInvokeData _33_Rewired_IFlightYokeTemplate_get_centerButton8;
  VirtualInvokeData _34_Rewired_IFlightYokeTemplate_get_wheel1Up;
  VirtualInvokeData _35_Rewired_IFlightYokeTemplate_get_wheel1Down;
  VirtualInvokeData _36_Rewired_IFlightYokeTemplate_get_wheel1Press;
  VirtualInvokeData _37_Rewired_IFlightYokeTemplate_get_wheel2Up;
  VirtualInvokeData _38_Rewired_IFlightYokeTemplate_get_wheel2Down;
  VirtualInvokeData _39_Rewired_IFlightYokeTemplate_get_wheel2Press;
  VirtualInvokeData _40_Rewired_IFlightYokeTemplate_get_consoleButton1;
  VirtualInvokeData _41_Rewired_IFlightYokeTemplate_get_consoleButton2;
  VirtualInvokeData _42_Rewired_IFlightYokeTemplate_get_consoleButton3;
  VirtualInvokeData _43_Rewired_IFlightYokeTemplate_get_consoleButton4;
  VirtualInvokeData _44_Rewired_IFlightYokeTemplate_get_consoleButton5;
  VirtualInvokeData _45_Rewired_IFlightYokeTemplate_get_consoleButton6;
  VirtualInvokeData _46_Rewired_IFlightYokeTemplate_get_consoleButton7;
  VirtualInvokeData _47_Rewired_IFlightYokeTemplate_get_consoleButton8;
  VirtualInvokeData _48_Rewired_IFlightYokeTemplate_get_consoleButton9;
  VirtualInvokeData _49_Rewired_IFlightYokeTemplate_get_consoleButton10;
  VirtualInvokeData _50_Rewired_IFlightYokeTemplate_get_mode1;
  VirtualInvokeData _51_Rewired_IFlightYokeTemplate_get_mode2;
  VirtualInvokeData _52_Rewired_IFlightYokeTemplate_get_mode3;
  VirtualInvokeData _53_Rewired_IFlightYokeTemplate_get_yoke;
  VirtualInvokeData _54_Rewired_IFlightYokeTemplate_get_lever1;
  VirtualInvokeData _55_Rewired_IFlightYokeTemplate_get_lever2;
  VirtualInvokeData _56_Rewired_IFlightYokeTemplate_get_lever3;
  VirtualInvokeData _57_Rewired_IFlightYokeTemplate_get_lever4;
  VirtualInvokeData _58_Rewired_IFlightYokeTemplate_get_lever5;
  VirtualInvokeData _59_Rewired_IFlightYokeTemplate_get_leftGripHat;
  VirtualInvokeData _60_Rewired_IFlightYokeTemplate_get_rightGripHat;
};

struct __FlightYokeTemplate_Il2CppClass {
  Il2CppClass_1 _1;
  __FlightYokeTemplate_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __FlightYokeTemplate_Il2CppVtbl vtbl;
};

class FlightYokeTemplate {
  static constexpr uint64_t         _rvaObjectInstance     = 0x3C77AA8;
  static inline    FlightYokeTemplate* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t                     _rvaClassInstance     = 0x3C2B820;
  static inline    __FlightYokeTemplate_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Singleton object getter:
  static inline FlightYokeTemplate* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (FlightYokeTemplate**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

// Static class getter:
  static inline __FlightYokeTemplate_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__FlightYokeTemplate_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __FlightYokeTemplate_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* ControllerTemplate_pouvrAGzgKKMJngewwBnCpncoOj;
  ModdingAPI::Exposed::System::Guid ControllerTemplate_GjfpwUriGOXMaXGAzhlhesewsIN;
  ModdingAPI::Exposed::Rewired::Controller* ControllerTemplate_eRiZsSFDNrFJxnreKaUhJBCLIKi;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Data::ADictionary_TKey__TValue_* ControllerTemplate_TasGtNGolxdwTnhzvFQqMpiZKfX;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Data::ADictionary_TKey__TValue_* ControllerTemplate_bFXUWuvECAwBpnwZCEyyPsnMldo;
  ModdingAPI::Exposed::Rewired::IControllerTemplateElement_array* ControllerTemplate_zDYSoPuWRIUrndraUwJpaRdSJEG;
  ModdingAPI::Exposed::System::Collections::ObjectModel::ReadOnlyCollection_T_* ControllerTemplate_BOLhTANJNrAyZcBkNpOGdedkKspm;
  int32_t ControllerTemplate_CtWHpgOaCVZYpcBzymhejPsalLW;

  // Member methods:
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftPaddle() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D040))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightPaddle() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D0D0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D160))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D1F0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D280))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton4() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D310))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton5() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D3A0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_leftGripButton6() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D430))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D4C0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D550))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D5E0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton4() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D670))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton5() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D700))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_rightGripButton6() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D790))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D820))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D8B0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D940))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton4() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216D9D0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton5() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DA60))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton6() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DAF0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton7() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DB80))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_centerButton8() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DC10))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel1Up() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DCA0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel1Down() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DD30))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel1Press() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DDC0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel2Up() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DE50))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel2Down() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DEE0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_wheel2Press() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216DF70))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E000))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E090))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E120))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton4() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E1B0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton5() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E240))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton6() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E2D0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton7() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E360))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton8() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E3F0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton9() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E480))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_consoleButton10() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E510))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_mode1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E5A0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_mode2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E630))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateButton* Rewired::IFlightYokeTemplate::get_mode3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateButton*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E6C0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateYoke* Rewired::IFlightYokeTemplate::get_yoke() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateYoke*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E750))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle* Rewired::IFlightYokeTemplate::get_lever1() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E7E0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle* Rewired::IFlightYokeTemplate::get_lever2() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E870))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle* Rewired::IFlightYokeTemplate::get_lever3() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E900))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle* Rewired::IFlightYokeTemplate::get_lever4() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216E990))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle* Rewired::IFlightYokeTemplate::get_lever5() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateThrottle*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216EA20))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateHat* Rewired::IFlightYokeTemplate::get_leftGripHat() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateHat*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216EAB0))(this);
  }
  ModdingAPI::Exposed::Rewired::IControllerTemplateHat* Rewired::IFlightYokeTemplate::get_rightGripHat() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::IControllerTemplateHat*(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216EB40))(this);
  }
  void ::ctor(Il2CppObject* payload) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::FlightYokeTemplate*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x216CF90))(this, payload);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Guid> typeGuid = __CppStaticProperty<ModdingAPI::Exposed::System::Guid>(
   []() { return &GetStaticClassInstance()->pStaticFields->typeGuid; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x216EBD0))();
  }
};
}