// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Rewired::Utils::Classes::Data {
struct __IndexedDictionary_TKey__TValue__Il2CppStaticFields {
  bool zxNfbxHzCZrMKWjvhdiRLMDiCot;
  bool VdXiOyJQHMJvHmsTFobVroLqaxMg;
};

struct __IndexedDictionary_TKey__TValue__Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_System_Collections_IEnumerable_GetEnumerator;
  VirtualInvokeData _5_System_Collections_IDictionary_get_Item;
  VirtualInvokeData _6_System_Collections_IDictionary_set_Item;
  VirtualInvokeData _7_System_Collections_IDictionary_get_Keys;
  VirtualInvokeData _8_System_Collections_IDictionary_get_Values;
  VirtualInvokeData _9_System_Collections_IDictionary_Contains;
  VirtualInvokeData _10_System_Collections_IDictionary_Add;
  VirtualInvokeData _12_System_Collections_IDictionary_get_IsReadOnly;
  VirtualInvokeData _13_System_Collections_IDictionary_get_IsFixedSize;
  VirtualInvokeData _14_System_Collections_IDictionary_GetEnumerator;
  VirtualInvokeData _15_System_Collections_IDictionary_Remove;
  VirtualInvokeData _16_System_Collections_ICollection_CopyTo;
  VirtualInvokeData _18_System_Collections_ICollection_get_SyncRoot;
  VirtualInvokeData _19_System_Collections_ICollection_get_IsSynchronized;
  VirtualInvokeData _20_System_Collections_Generic_IDictionary_TKey_TValue__get_Item;
  VirtualInvokeData _21_System_Collections_Generic_IDictionary_TKey_TValue__set_Item;
  VirtualInvokeData _22_get_Keys;
  VirtualInvokeData _23_get_Values;
  VirtualInvokeData _24_ContainsKey;
  VirtualInvokeData _25_Add;
  VirtualInvokeData _26_Remove;
  VirtualInvokeData _27_TryGetValue;
  VirtualInvokeData _28_get_Count;
  VirtualInvokeData _29_System_Collections_Generic_ICollection_System_Collections_Generic_KeyValuePair_TKey_TValue___get_IsReadOnly;
  VirtualInvokeData _30_System_Collections_Generic_ICollection_System_Collections_Generic_KeyValuePair_TKey_TValue___Add;
  VirtualInvokeData _31_Clear;
  VirtualInvokeData _32_System_Collections_Generic_ICollection_System_Collections_Generic_KeyValuePair_TKey_TValue___Contains;
  VirtualInvokeData _33_System_Collections_Generic_ICollection_System_Collections_Generic_KeyValuePair_TKey_TValue___CopyTo;
  VirtualInvokeData _34_System_Collections_Generic_ICollection_System_Collections_Generic_KeyValuePair_TKey_TValue___Remove;
  VirtualInvokeData _35_GetEnumerator;
  VirtualInvokeData _36_Rewired_Utils_Interfaces_IReadOnlyList_TValue__get_Item;
  VirtualInvokeData _37_Rewired_Utils_Interfaces_IReadOnlyList_TValue__IndexOf;
  VirtualInvokeData _38_Rewired_Utils_Interfaces_IReadOnlyList_TValue__Contains;
  VirtualInvokeData _39_Rewired_Utils_Interfaces_IReadOnlyList_get_Count;
  VirtualInvokeData _40_Rewired_Utils_Interfaces_IReadOnlyList_get_Item;
  VirtualInvokeData _41_Rewired_Utils_Interfaces_IReadOnlyList_IndexOf;
  VirtualInvokeData _42_Rewired_Utils_Interfaces_IReadOnlyList_Contains;
};

struct __IndexedDictionary_TKey__TValue__Il2CppClass {
  Il2CppClass_1 _1;
  __IndexedDictionary_TKey__TValue__Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __IndexedDictionary_TKey__TValue__Il2CppVtbl vtbl;
};

class IndexedDictionary_TKey__TValue_ {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C91D38;
  static inline    __IndexedDictionary_TKey__TValue__Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __IndexedDictionary_TKey__TValue__Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__IndexedDictionary_TKey__TValue__Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __IndexedDictionary_TKey__TValue__Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Collections::Generic::IEqualityComparer_T_* rfyQAKJTQhgGNCNfTCnIyWJlDDR;
  ModdingAPI::Exposed::System::Collections::Generic::IEqualityComparer_T_* FwloncpAVvCWmkXiQNqRhKYIdfbe;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Data::AList_T_* nSvFWhtVcKTiLbWdjWHDWStzhXJ;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Data::ADictionary_TKey__TValue_* BCfKEaMvJFVNOroPdnijJCvDISB;
  bool kCWPckcCSkEPyEfVgCmtFQqybEXj;

  // Static fields:
  static inline __CppStaticProperty<bool> zxNfbxHzCZrMKWjvhdiRLMDiCot = __CppStaticProperty<bool>(
   []() { return &GetStaticClassInstance()->pStaticFields->zxNfbxHzCZrMKWjvhdiRLMDiCot; }
  );
  static inline __CppStaticProperty<bool> VdXiOyJQHMJvHmsTFobVroLqaxMg = __CppStaticProperty<bool>(
   []() { return &GetStaticClassInstance()->pStaticFields->VdXiOyJQHMJvHmsTFobVroLqaxMg; }
  );
};
}