// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.KeyCode.hpp"
#include "ModdingAPI.Exposed.Rewired.ElementAssignmentConflictCheck.hpp"
#include "ModdingAPI.Exposed.Rewired.ElementAssignment.hpp"

namespace ModdingAPI::Exposed::Rewired {
struct __ElementAssignmentConflictCheck_Il2CppObject {
  int32_t BgHbApPCqaUTJFuEgAENTUSmDdz;
  int32_t RQvCtWMSaXdtWuElfcQyltnGehm;
  int32_t UKHPEgpfEMgaxeIYmcUTCbzFPYYc;
  int32_t OrRbFrDDytBuoavptrdUDRQWhpXD;
  int32_t qjofBqEGqOdfMkYvGjVwAMWFcbAe;
  int32_t nLbKjIdDtbZtehFzsMdUrKXbNVg;
  int32_t ZlpCwTgkPZmHQfJpqpQGdSdWaLqE;
  int32_t HDTmQvJrpXCrFCutlEbuBDHfGOZb;
  int32_t dHdbVWFfXobbpJwQnmBdUBIMAb;
  ModdingAPI::Exposed::UnityEngine::KeyCode OqPaEbuzaGIUyCcsAgfPfjtpFfhB;
  int32_t jJMHMrmuCMlMrgWbBjtMPstYHOO;
  int32_t BXlRCANxPIHqvgTtMSzGnnLdTcg;
  int32_t wOLdwMDzwrXydteMNpINAwsGtxVf;
  bool MUOJDaRhwFeOjqBWQMXSXvDHuym;
};
struct __ElementAssignmentConflictCheck_Il2CppStaticFields {
};

struct __ElementAssignmentConflictCheck_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ElementAssignmentConflictCheck_Il2CppClass {
  Il2CppClass_1 _1;
  __ElementAssignmentConflictCheck_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ElementAssignmentConflictCheck_Il2CppVtbl vtbl;
};

class ElementAssignmentConflictCheck {
public:
  // Member fields:
  int32_t BgHbApPCqaUTJFuEgAENTUSmDdz;
  int32_t RQvCtWMSaXdtWuElfcQyltnGehm;
  int32_t UKHPEgpfEMgaxeIYmcUTCbzFPYYc;
  int32_t OrRbFrDDytBuoavptrdUDRQWhpXD;
  int32_t qjofBqEGqOdfMkYvGjVwAMWFcbAe;
  int32_t nLbKjIdDtbZtehFzsMdUrKXbNVg;
  int32_t ZlpCwTgkPZmHQfJpqpQGdSdWaLqE;
  int32_t HDTmQvJrpXCrFCutlEbuBDHfGOZb;
  int32_t dHdbVWFfXobbpJwQnmBdUBIMAb;
  ModdingAPI::Exposed::UnityEngine::KeyCode OqPaEbuzaGIUyCcsAgfPfjtpFfhB;
  int32_t jJMHMrmuCMlMrgWbBjtMPstYHOO;
  int32_t BXlRCANxPIHqvgTtMSzGnnLdTcg;
  int32_t wOLdwMDzwrXydteMNpINAwsGtxVf;
  bool MUOJDaRhwFeOjqBWQMXSXvDHuym;

  // Member methods:
  int32_t get_elementAssignmentType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3030))(this);
  }
  void set_elementAssignmentType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3020))(this, value);
  }
  int32_t get_playerId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5A20))(this);
  }
  void set_playerId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE720))(this, value);
  }
  int32_t get_controllerType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5020))(this);
  }
  void set_controllerType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF170))(this, value);
  }
  int32_t get_controllerId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5A30))(this);
  }
  void set_controllerId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A670))(this, value);
  }
  int32_t get_controllerMapId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3380))(this);
  }
  void set_controllerMapId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x121E0))(this, value);
  }
  int32_t get_controllerMapCategoryId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A680))(this);
  }
  void set_controllerMapCategoryId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x121F0))(this, value);
  }
  int32_t get_elementMapId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF1D0))(this);
  }
  void set_elementMapId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF1E0))(this, value);
  }
  int32_t get_elementIdentifierId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x8490))(this);
  }
  void set_elementIdentifierId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A690))(this, value);
  }
  int32_t get_axisRange() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6A0))(this);
  }
  void set_axisRange(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6B0))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::KeyCode get_keyboardKey() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::KeyCode(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x13170))(this);
  }
  void set_keyboardKey(ModdingAPI::Exposed::UnityEngine::KeyCode value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, ModdingAPI::Exposed::UnityEngine::KeyCode)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6C0))(this, value);
  }
  int32_t get_modifierKeyFlags() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6880))(this);
  }
  void set_modifierKeyFlags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xA5A0))(this, value);
  }
  int32_t get_actionId() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6D0))(this);
  }
  void set_actionId(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6E0))(this, value);
  }
  int32_t get_axisContribution() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x132B0))(this);
  }
  void set_axisContribution(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A6F0))(this, value);
  }
  bool get_invert() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A700))(this);
  }
  void set_invert(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A710))(this, value);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementAssignmentType, int32_t elementIdentifierId, int32_t axisRange, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution, bool invert) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A720))(this, playerId, controllerType, controllerId, controllerMapId, elementAssignmentType, elementIdentifierId, axisRange, keyboardKey, modifierKeyFlags, actionId, axisContribution, invert);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementAssignmentType, int32_t elementIdentifierId, int32_t axisRange, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution, bool invert, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A780))(this, playerId, controllerType, controllerId, controllerMapId, elementAssignmentType, elementIdentifierId, axisRange, keyboardKey, modifierKeyFlags, actionId, axisContribution, invert, elementMapId);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementType, int32_t elementIdentifierId, int32_t axisRange, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution, bool invert) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A7F0))(this, playerId, controllerType, controllerId, controllerMapId, elementType, elementIdentifierId, axisRange, keyboardKey, modifierKeyFlags, actionId, axisContribution, invert);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementType, int32_t elementIdentifierId, int32_t axisRange, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution, bool invert, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A880))(this, playerId, controllerType, controllerId, controllerMapId, elementType, elementIdentifierId, axisRange, keyboardKey, modifierKeyFlags, actionId, axisContribution, invert, elementMapId);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t actionId, bool invert) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A950))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, actionId, invert);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t actionId, bool invert, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1A9A0))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, actionId, invert, elementMapId);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t axisRange, int32_t actionId, int32_t axisContribution) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AA00))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, axisRange, actionId, axisContribution);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t axisRange, int32_t actionId, int32_t axisContribution, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AA50))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, axisRange, actionId, axisContribution, elementMapId);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t actionId, int32_t axisContribution) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AAB0))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, actionId, axisContribution);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, int32_t elementIdentifierId, int32_t actionId, int32_t axisContribution, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AB00))(this, playerId, controllerType, controllerId, controllerMapId, elementIdentifierId, actionId, axisContribution, elementMapId);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AB60))(this, playerId, controllerType, controllerId, controllerMapId, keyboardKey, modifierKeyFlags, actionId, axisContribution);
  }
  void ::ctor(int32_t playerId, int32_t controllerType, int32_t controllerId, int32_t controllerMapId, ModdingAPI::Exposed::UnityEngine::KeyCode keyboardKey, int32_t modifierKeyFlags, int32_t actionId, int32_t axisContribution, int32_t elementMapId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::KeyCode, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1ABC0))(this, playerId, controllerType, controllerId, controllerMapId, keyboardKey, modifierKeyFlags, actionId, axisContribution, elementMapId);
  }
  void ::ctor(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*, ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AC20))(this, source);
  }
  ModdingAPI::Exposed::Rewired::ElementAssignment ToElementAssignment() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::ElementAssignment(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1ACE0))(this);
  }
  ModdingAPI::Exposed::Rewired::ElementAssignment ToFullAxisAssignment() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::ElementAssignment(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AD70))(this);
  }
  ModdingAPI::Exposed::Rewired::ElementAssignment ToSplitAxisAssignment() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::ElementAssignment(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1ADE0))(this);
  }
  ModdingAPI::Exposed::Rewired::ElementAssignment ToButtonAssignment() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::ElementAssignment(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AE50))(this);
  }
  ModdingAPI::Exposed::Rewired::ElementAssignment ToKeyboardKeyAssignment() {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::ElementAssignment(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AEE0))(this);
  }
  void IEHCVTVbAiSJohjjDuBQMdTmsuK() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::ElementAssignmentConflictCheck*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1AF70))(this);
  }

};
}