// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base {
struct __MatchingCriteria_Il2CppStaticFields {
};

struct __MatchingCriteria_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _5_get_hasData;
  VirtualInvokeData _6_get_isAllowed;
  VirtualInvokeData _7_Matches;
  VirtualInvokeData _8_get_alternateElementCount;
  VirtualInvokeData _9_GetAlternateElementCount;
  VirtualInvokeData _10_ElementCountsMatch;
  VirtualInvokeData _11_CopyVars;
  VirtualInvokeData _12_DeepClone;
};

struct __MatchingCriteria_Il2CppClass {
  Il2CppClass_1 _1;
  __MatchingCriteria_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __MatchingCriteria_Il2CppVtbl vtbl;
};

class MatchingCriteria {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C58280;
  static inline    __MatchingCriteria_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __MatchingCriteria_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__MatchingCriteria_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __MatchingCriteria_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t axisCount;
  int32_t buttonCount;
  bool disabled;
  System_String* tag;
  bool alwaysMatch;
  bool productName_useRegex;
  ModdingAPI::Exposed::System::String_array* productName;

  // Member methods:
  bool get_hasData() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x333C10))(this);
  }
  bool get_isAllowed() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3244C0))(this);
  }
  bool Matches(ModdingAPI::Exposed::Rewired::BridgedControllerHWInfo* bridgedControllerHWInfo, bool strictMatch) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*, ModdingAPI::Exposed::Rewired::BridgedControllerHWInfo*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10CEFC0))(this, bridgedControllerHWInfo, strictMatch);
  }
  Il2CppObject* DeepClone() {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10CF210))(this);
  }
  void CopyVars(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::MatchingCriteria_Base* destination) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*, ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::MatchingCriteria_Base*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10CF370))(this, destination);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::HardwareJoystickMap::Platform_Stadia_Base::MatchingCriteria*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
};
}