// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Rewired::Data::UserData {
struct __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Func_T__TResult_* AjUCLDifDAKxqrtsFOtDRDgfJhFI;
  ModdingAPI::Exposed::System::Func_T__TResult_* YvLqHWMCOHcELizHcMGogttFqjGh;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* NQJZewJDFaqLUkyIJCOjmSTFqzE;
  ModdingAPI::Exposed::System::Func_T__TResult_* URphARrrRajAqYdgigBEEIUkUpf;
  ModdingAPI::Exposed::System::Func_T__TResult_* mZMLpEukCmreGDkDIdvzIasdEPED;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* pdoUQksneqjuKeZyJnoUhHOHydG;
  ModdingAPI::Exposed::System::Func_T__TResult_* sWDVbwxjtNpkXanpFVDwoyYWQIa;
  ModdingAPI::Exposed::System::Func_T__TResult_* fIcaHpEKfvKFxGuWfCSHZZrFNpiO;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* WKiEnXSZtdjBNUuVVKfnXKeOQej;
  ModdingAPI::Exposed::System::Func_T__TResult_* CWiRRGvOuFudxSpIMogaiQExrhk;
  ModdingAPI::Exposed::System::Func_T__TResult_* cfXOwAmzHHsWhAnWKakJZvbVTYv;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* cFnvBifgBzcflGrVAqOYcsWkCSGA;
  ModdingAPI::Exposed::System::Func_T__TResult_* IFdNKgEJrLaiRESNCCAfPSnMDuuf;
  ModdingAPI::Exposed::System::Func_T__TResult_* WAtNhzThDGMDlPCodarlacWCTnfa;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* KmBmHKwFDbqbfnAqkXrEWrnhYIR;
  ModdingAPI::Exposed::System::Func_T__TResult_* aClBnRFKXuGJhMaSkcCQFymBuw;
  ModdingAPI::Exposed::System::Func_T__TResult_* NCjhTeKXopRzgLyAPryOhShnJLG;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* EFDutODzVtILyDUeHurFAmbyoiM;
  ModdingAPI::Exposed::System::Func_T__TResult_* NpQBrabQvgEHUZYrToXspauHssw;
  ModdingAPI::Exposed::System::Func_T__TResult_* AbccOMJhkNUbmgBUZIbpZQHxjTLe;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* yAxbHHpEOWrwSAGoRPMXGqXDGGqe;
  ModdingAPI::Exposed::System::Func_T__TResult_* YufoPSjyeqQyflEcBhOzjaJNZKc;
  ModdingAPI::Exposed::System::Func_T__TResult_* IwjhtXwkkqCDuWEuWvVwkTkcCqK;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* EXpgsfHVhEqvIsBhTgHxbemdjn;
  ModdingAPI::Exposed::System::Func_T__TResult_* kiiHVSCDbPgPJIOThatQzKoHqBr;
  ModdingAPI::Exposed::System::Func_T__TResult_* PLLUuGUlylnjslcKkjRIykEsBHd;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* aUofsAvqeQMngYeLiOJxdsVpQIX;
  ModdingAPI::Exposed::System::Func_T__TResult_* THpeHXaXGyWFzkgmOOSEBerBIjbj;
  ModdingAPI::Exposed::System::Func_T__TResult_* pePNobCtmmkEDNmzaIBcGTMroVA;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* bitgurHQulLiXSIRwGmejNXlqCbO;
  ModdingAPI::Exposed::System::Func_T__TResult_* QzKWEPMVEiFnArpjwKHIVqsWZSg;
  ModdingAPI::Exposed::System::Func_T__TResult_* dHKbNTcNEOrRCyPEfevOBfnbAqmg;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* blkmifQsTdOUqCGKZaNBSyONTAQ;
  ModdingAPI::Exposed::System::Func_T__TResult_* BrymtNBESbXRMpONooqrxvHJjRs;
  ModdingAPI::Exposed::System::Func_T__TResult_* xFfLuwBnWbVrnrWRXjakrasyBCx;
  ModdingAPI::Exposed::System::Func_T1__T2__TResult_* jmFdbckSbUvFlZvPZuvSUmlFbRS;
  ModdingAPI::Exposed::System::Func_T__TResult_* UBndCgApuvJCCDFZFKRRmdoiaBFn;
  ModdingAPI::Exposed::System::Func_T__TResult_* yglRhfmZPSovRsYBuOQmIVuvfOh;
  ModdingAPI::Exposed::System::Func_T__TResult_* VWFgkylRGgoMFAPlXmYuvfRJHnc;
  ModdingAPI::Exposed::System::Func_T__TResult_* xdlxpuqpbWvUrrEfqPuOTCSUAtD;
  ModdingAPI::Exposed::System::Func_T__TResult_* HzAmpBKaJElzuOfbMfAlierIYjY;
  ModdingAPI::Exposed::System::Func_T__TResult_* MUtIxlxtOZfYrerDrbJOUEXLjCK;
  ModdingAPI::Exposed::System::Func_T__TResult_* dwXIPtgCtuJbLInOMWJYRqPbWKt;
  ModdingAPI::Exposed::System::Func_T__TResult_* phvZjSdPZfaupHnuUuFIcIqyWnLg;
};

struct __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppClass {
  Il2CppClass_1 _1;
  __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppVtbl vtbl;
};

class hQOGfiKTixQWUIGbsOgmkZIJYnU {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C35568;
  static inline    __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __hQOGfiKTixQWUIGbsOgmkZIJYnU_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> AjUCLDifDAKxqrtsFOtDRDgfJhFI = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->AjUCLDifDAKxqrtsFOtDRDgfJhFI; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> YvLqHWMCOHcELizHcMGogttFqjGh = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->YvLqHWMCOHcELizHcMGogttFqjGh; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> NQJZewJDFaqLUkyIJCOjmSTFqzE = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->NQJZewJDFaqLUkyIJCOjmSTFqzE; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> URphARrrRajAqYdgigBEEIUkUpf = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->URphARrrRajAqYdgigBEEIUkUpf; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> mZMLpEukCmreGDkDIdvzIasdEPED = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->mZMLpEukCmreGDkDIdvzIasdEPED; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> pdoUQksneqjuKeZyJnoUhHOHydG = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->pdoUQksneqjuKeZyJnoUhHOHydG; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> sWDVbwxjtNpkXanpFVDwoyYWQIa = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->sWDVbwxjtNpkXanpFVDwoyYWQIa; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> fIcaHpEKfvKFxGuWfCSHZZrFNpiO = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->fIcaHpEKfvKFxGuWfCSHZZrFNpiO; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> WKiEnXSZtdjBNUuVVKfnXKeOQej = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->WKiEnXSZtdjBNUuVVKfnXKeOQej; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> CWiRRGvOuFudxSpIMogaiQExrhk = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->CWiRRGvOuFudxSpIMogaiQExrhk; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> cfXOwAmzHHsWhAnWKakJZvbVTYv = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->cfXOwAmzHHsWhAnWKakJZvbVTYv; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> cFnvBifgBzcflGrVAqOYcsWkCSGA = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->cFnvBifgBzcflGrVAqOYcsWkCSGA; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> IFdNKgEJrLaiRESNCCAfPSnMDuuf = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->IFdNKgEJrLaiRESNCCAfPSnMDuuf; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> WAtNhzThDGMDlPCodarlacWCTnfa = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->WAtNhzThDGMDlPCodarlacWCTnfa; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> KmBmHKwFDbqbfnAqkXrEWrnhYIR = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->KmBmHKwFDbqbfnAqkXrEWrnhYIR; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> aClBnRFKXuGJhMaSkcCQFymBuw = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->aClBnRFKXuGJhMaSkcCQFymBuw; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> NCjhTeKXopRzgLyAPryOhShnJLG = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->NCjhTeKXopRzgLyAPryOhShnJLG; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> EFDutODzVtILyDUeHurFAmbyoiM = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->EFDutODzVtILyDUeHurFAmbyoiM; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> NpQBrabQvgEHUZYrToXspauHssw = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->NpQBrabQvgEHUZYrToXspauHssw; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> AbccOMJhkNUbmgBUZIbpZQHxjTLe = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->AbccOMJhkNUbmgBUZIbpZQHxjTLe; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> yAxbHHpEOWrwSAGoRPMXGqXDGGqe = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->yAxbHHpEOWrwSAGoRPMXGqXDGGqe; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> YufoPSjyeqQyflEcBhOzjaJNZKc = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->YufoPSjyeqQyflEcBhOzjaJNZKc; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> IwjhtXwkkqCDuWEuWvVwkTkcCqK = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->IwjhtXwkkqCDuWEuWvVwkTkcCqK; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> EXpgsfHVhEqvIsBhTgHxbemdjn = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->EXpgsfHVhEqvIsBhTgHxbemdjn; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> kiiHVSCDbPgPJIOThatQzKoHqBr = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->kiiHVSCDbPgPJIOThatQzKoHqBr; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> PLLUuGUlylnjslcKkjRIykEsBHd = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->PLLUuGUlylnjslcKkjRIykEsBHd; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> aUofsAvqeQMngYeLiOJxdsVpQIX = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->aUofsAvqeQMngYeLiOJxdsVpQIX; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> THpeHXaXGyWFzkgmOOSEBerBIjbj = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->THpeHXaXGyWFzkgmOOSEBerBIjbj; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> pePNobCtmmkEDNmzaIBcGTMroVA = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->pePNobCtmmkEDNmzaIBcGTMroVA; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> bitgurHQulLiXSIRwGmejNXlqCbO = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->bitgurHQulLiXSIRwGmejNXlqCbO; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> QzKWEPMVEiFnArpjwKHIVqsWZSg = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->QzKWEPMVEiFnArpjwKHIVqsWZSg; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> dHKbNTcNEOrRCyPEfevOBfnbAqmg = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->dHKbNTcNEOrRCyPEfevOBfnbAqmg; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> blkmifQsTdOUqCGKZaNBSyONTAQ = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->blkmifQsTdOUqCGKZaNBSyONTAQ; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> BrymtNBESbXRMpONooqrxvHJjRs = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->BrymtNBESbXRMpONooqrxvHJjRs; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> xFfLuwBnWbVrnrWRXjakrasyBCx = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->xFfLuwBnWbVrnrWRXjakrasyBCx; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*> jmFdbckSbUvFlZvPZuvSUmlFbRS = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T1__T2__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->jmFdbckSbUvFlZvPZuvSUmlFbRS; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> UBndCgApuvJCCDFZFKRRmdoiaBFn = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->UBndCgApuvJCCDFZFKRRmdoiaBFn; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> yglRhfmZPSovRsYBuOQmIVuvfOh = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->yglRhfmZPSovRsYBuOQmIVuvfOh; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> VWFgkylRGgoMFAPlXmYuvfRJHnc = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->VWFgkylRGgoMFAPlXmYuvfRJHnc; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> xdlxpuqpbWvUrrEfqPuOTCSUAtD = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->xdlxpuqpbWvUrrEfqPuOTCSUAtD; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> HzAmpBKaJElzuOfbMfAlierIYjY = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->HzAmpBKaJElzuOfbMfAlierIYjY; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> MUtIxlxtOZfYrerDrbJOUEXLjCK = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->MUtIxlxtOZfYrerDrbJOUEXLjCK; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> dwXIPtgCtuJbLInOMWJYRqPbWKt = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->dwXIPtgCtuJbLInOMWJYRqPbWKt; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*> phvZjSdPZfaupHnuUuFIcIqyWnLg = __CppStaticProperty<ModdingAPI::Exposed::System::Func_T__TResult_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->phvZjSdPZfaupHnuUuFIcIqyWnLg; }
  );

  // Static methods:
  static inline ModdingAPI::Exposed::Rewired::Data::UserData* gmctudUdWYPnIAQFVHofqAPuKTR(ModdingAPI::Exposed::Rewired::Data::UserData* , ModdingAPI::Exposed::Rewired::Data::UserData* , bool ) {
    return reinterpret_cast<ModdingAPI::Exposed::Rewired::Data::UserData*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::UserData*, ModdingAPI::Exposed::Rewired::Data::UserData*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4416C0))(, , );
  }
  static inline void xJMpGmwotJBeiBalFqRjLYCdtZV(Il2CppObject* ) {
    reinterpret_cast<void(__fastcall*)(Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4441B0))();
  }
  static inline int32_t zpzobiPtwcqOPlDgJoFvaTTDaKi(ModdingAPI::Exposed::Rewired::InputCategory* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputCategory*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444240))();
  }
  static inline System_String* QnLSiWlYoJGIvNbsKtasoUVePeL(ModdingAPI::Exposed::Rewired::InputCategory* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputCategory*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t UCRTeiaKRRlBrsAuwhosxhLIauT(ModdingAPI::Exposed::Rewired::InputCategory* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputCategory*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444260))(, );
  }
  static inline int32_t gFkRBvObKffRgBumlsapirSiiWN(ModdingAPI::Exposed::Rewired::InputBehavior* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputBehavior*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* gCPdruHfqLKnGbamycikiWMGJKit(ModdingAPI::Exposed::Rewired::InputBehavior* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputBehavior*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444D0))();
  }
  static inline int32_t XKRpdaSRwXRQMtWjMzjPEnwVFDc(ModdingAPI::Exposed::Rewired::InputBehavior* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputBehavior*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444F0))(, );
  }
  static inline int32_t CHcXMvVlobmuGaDRVjTJkPppFTbK(ModdingAPI::Exposed::Rewired::InputAction* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputAction*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* EwxKfGWpLfjDjYFLaQrimrJYJJi(ModdingAPI::Exposed::Rewired::InputAction* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputAction*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444D0))();
  }
  static inline int32_t ZZDvMWlhXDbIuRgwYxozVZrrSaL(ModdingAPI::Exposed::Rewired::InputAction* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputAction*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444730))(, );
  }
  static inline int32_t HqlaWBUZZAbcGvkQnvhCQCtxcAv(ModdingAPI::Exposed::Rewired::InputMapCategory* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputMapCategory*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444240))();
  }
  static inline System_String* NcTWNgzTcUoPAJMcYGZxftwBQMnB(ModdingAPI::Exposed::Rewired::InputMapCategory* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputMapCategory*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t klOhmecsRvRWElbCFXQOCEHwpA(ModdingAPI::Exposed::Rewired::InputMapCategory* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputMapCategory*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444990))(, );
  }
  static inline int32_t iGrctIJfmmKXgGPwCrOzZdarPRJ(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BC0))();
  }
  static inline System_String* rwEwanuEfzAKAgRPTHyzEzhOXZa(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t PvWpzGxBwOdHeUkXDACrYVwVNTN(ModdingAPI::Exposed::Rewired::InputLayout* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BE0))(, );
  }
  static inline int32_t HFMaSFxEvtUtMnJJIxraoYjUGMU(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BC0))();
  }
  static inline System_String* yWcQfilzyQJtilPPgfQzsACKrCt(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t CEiFNUeLLRyglehGdDItBonnrvpb(ModdingAPI::Exposed::Rewired::InputLayout* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444E10))(, );
  }
  static inline int32_t HPqzhbUgqTVxawcxxcdgOoRKewa(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BC0))();
  }
  static inline System_String* pLnffwcNlyeJpYYTiQSYsZvNNutf(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t gOkPiGMHcdzxVctuprbsSGKYEsL(ModdingAPI::Exposed::Rewired::InputLayout* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445060))(, );
  }
  static inline int32_t DIYOOCakMnbrJAMGYTrDSTqaIsk(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BC0))();
  }
  static inline System_String* BGHTtIgWvmNJDGZYplZoZZoNUQA(ModdingAPI::Exposed::Rewired::InputLayout* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t nSBOkxZIAGpnrKBjDbzLiLrKqiI(ModdingAPI::Exposed::Rewired::InputLayout* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::InputLayout*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445300))(, );
  }
  static inline int32_t ScJaliJcAEMdIAphSohrgzTWipHp(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x444BC0))();
  }
  static inline System_String* YAMIYjfwRTPsJRcRjrwpwlAzGgHe(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8910))();
  }
  static inline int32_t QFhKDgOnOeecCndyLSfkrEqPeXaf(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::CustomController_Editor*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445530))(, );
  }
  static inline int32_t hnRsHBlfmHBdyiJIFfNxWNnhiNDc(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* AgApAEWjnrmWRzGRBuSRFkWzGNM(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444D0))();
  }
  static inline int32_t NeAgKCFKCPwLVYlIYTqmThCZfFHd(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapLayoutManager_RuleSet_Editor*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445760))(, );
  }
  static inline int32_t rwCffiNwESccIUBmRazjysGKVpF(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* FBpPYicDnEfDfzTKoiQbtRnnBnd(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444D0))();
  }
  static inline int32_t mYKGqYsTYtUnOvwBLmiEpACOzzI(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::ControllerMapEnabler_RuleSet_Editor*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445A00))(, );
  }
  static inline int32_t MEVBeBApptGyILhbwmIutUocLup(ModdingAPI::Exposed::Rewired::Data::Player_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Player_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* gTufnxoXgeEgNpWGEbJgfzCyfkzR(ModdingAPI::Exposed::Rewired::Data::Player_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Player_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444D0))();
  }
  static inline int32_t wNMrSxSxiBatxHPXJoqpZGefnty(ModdingAPI::Exposed::Rewired::Data::Player_Editor* , ModdingAPI::Exposed::System::Collections::Generic::IList_T_* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Player_Editor*, ModdingAPI::Exposed::System::Collections::Generic::IList_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445C30))(, );
  }
  static inline int32_t xlXuNjmUfscSUpMPzieWZdqxWrG(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* CqJxGukLBhwtccqkJjmSKCkZDDTl(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445E80))();
  }
  static inline int32_t vNDePvnZczxosvZrvLQOvNhyZIR(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* eYaarfJIpXfhbdRBbHSkLYCWfjJG(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445E80))();
  }
  static inline int32_t IzRFigbCfgzJTLJZmDgnKroTWpO(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* mEPbhTYlGTanrIFabSMeyoYafXY(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445E80))();
  }
  static inline int32_t AOeXEnnKkyJglndKTgUwDpIuuIi(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4444B0))();
  }
  static inline System_String* JtPqvXNSLXIiXMIVZgXeHidNRxOi(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor* ) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Rewired::Data::Mapping::ControllerMap_Editor*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x445E80))();
  }
};
}