// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::Rewired::Player::ControllerHelper {
struct __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppStaticFields {
};

struct __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Rewired_Player_ControllerHelper_IControllerSet_get_Item;
  VirtualInvokeData _5_get_controllerType;
  VirtualInvokeData _6_get_Count;
  VirtualInvokeData _7_Rewired_Player_ControllerHelper_IControllerSet_Contains;
  VirtualInvokeData _8_Contains;
  VirtualInvokeData _9_RemoveController;
  VirtualInvokeData _10_Rewired_Player_ControllerHelper_IControllerSet_RemoveController;
  VirtualInvokeData _11_RemoveAt;
  VirtualInvokeData _12_Rewired_Player_ControllerHelper_IControllerSet_GetController;
  VirtualInvokeData _13_Rewired_Player_ControllerHelper_IControllerSet_GetControllerWithTag;
  VirtualInvokeData _14_Rewired_Player_ControllerHelper_IControllerSet_IndexOf;
  VirtualInvokeData _15_IndexOf;
  VirtualInvokeData _16_IndexOfTag;
  VirtualInvokeData _17_Clear;
  VirtualInvokeData _18_Rewired_Player_ControllerHelper_IControllerSet_GetEntry;
  VirtualInvokeData _19_Rewired_Player_ControllerHelper_IControllerSet_GetEntry;
  VirtualInvokeData _20_Rewired_Player_ControllerHelper_IControllerSet_AddEntry;
};

struct __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppClass {
  Il2CppClass_1 _1;
  __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppVtbl vtbl;
};

class VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap_ {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C58DB8;
  static inline    __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __VflKPPbPcYyaXZmcpAIyLtEJCOY_TController__TMap__Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* sFilOtAJPbEKLKPIXiEXlUdrGaU;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* FdEdjywEGuFZTzBwigXWkrejGQT;
  ModdingAPI::Exposed::System::Collections::ObjectModel::ReadOnlyCollection_T_* mlLUTfjzyyRyUSdQegvBoEYvRfy;
  int32_t UKHPEgpfEMgaxeIYmcUTCbzFPYYc;
};
}