// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector4.hpp"


namespace ModdingAPI::Exposed {
struct __SceneWeatherOverride_Il2CppStaticFields {
};

struct __SceneWeatherOverride_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __SceneWeatherOverride_Il2CppClass {
  Il2CppClass_1 _1;
  __SceneWeatherOverride_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SceneWeatherOverride_Il2CppVtbl vtbl;
};

class SceneWeatherOverride {
public:
  // Il2Cpp fields:
  __SceneWeatherOverride_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  float m_IndoorTemperatureCelsius;
  float m_HighTempMinCelsius;
  float m_HighTempMaxCelsius;
  float m_LowTempMinCelsius;
  float m_LowTempMaxCelsius;
  float m_BlizzardDegreesDrop;
  float m_BlizzardDegreesChangePerSecond;
  int32_t m_HourWarmingBegins;
  int32_t m_HourCoolingBegins;
  int32_t m_AuroraEarlyWindowProbability;
  int32_t m_AuroraLateWindowProbability;
  float m_DegreesPerSecondChangeLow;
  float m_DegreesPerSecondChangeMedium;
  float m_DegreesPerSecondChangeHigh;
  float m_TimeToDisplayTempWhenChanged;
  float m_MinWindSpeedForBlowingSnow;
  float m_BlowingSnowTransitionSeconds;
  float m_MinimumFogDensityScale;
  ModdingAPI::Exposed::UnityEngine::Vector4 m_SkyboxHorizonAdjust;
  ModdingAPI::Exposed::WeatherSet_array* m_WeatherSetOverrides;
  float m_OcclusionTestRange;
  float m_OcclusionTestFOV;
  float m_OcclusionReduceWindchillPercent;
  int32_t m_OcclusionAudioLevel;
  bool m_NeverCalmWind;
  float m_HoursBetweenWindChangeMin;
  float m_HoursBetweenWindChangeMax;
  float m_SlightlyWindyMPHThreshold;
  float m_WindyMPHThreshold;
  float m_VeryWindyMPHThreshold;
  float m_MaxWindMPH;
  float m_MinimumBlizzardWindSpeed;

  // Member methods:
  void Awake() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SceneWeatherOverride*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C378B0))(this);
  }
  void DoWeatherOverride() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SceneWeatherOverride*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C379F0))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SceneWeatherOverride*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C37BE0))(this);
  }
};
}