// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __SnareItem_Il2CppStaticFields {
  ModdingAPI::Exposed::SnareItemSaveDataProxy* m_SnareItemSaveDataProxy;
};

struct __SnareItem_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __SnareItem_Il2CppClass {
  Il2CppClass_1 _1;
  __SnareItem_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SnareItem_Il2CppVtbl vtbl;
};

class SnareItem {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C6C818;
  static inline    __SnareItem_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __SnareItem_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__SnareItem_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __SnareItem_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_TrapDefaultMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_TrapSetMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_TrapBrokenMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_TrapWithRabbitMesh;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_RabbitPrefab;
  ModdingAPI::Exposed::UnityEngine::GameObject* m_RabbitSpawnPoint;
  int32_t m_State;
  float m_HoursBeforeRoll;
  float m_ChanceSpawnCarcassOnRoll;
  float m_ChanceBreakOnRoll;
  float m_HoursAtLastRoll;
  int32_t m_RestoreStateWhenLeaveInspection;
  ModdingAPI::Exposed::GearItem* m_GearItem;

  // Member methods:
  void Awake() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C55E10))(this);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C55E20))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C55EB0))(this);
  }
  System_String* Serialize() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C560A0))(this);
  }
  void Deserialize(System_String* text) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56230))(this, text);
  }
  void OnSnarePlaced() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C563A0))(this);
  }
  void EnableAllMeshes() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56480))(this);
  }
  void RefreshMeshes() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56600))(this);
  }
  int32_t GetState() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x383900))(this);
  }
  void SetState(int32_t state) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56610))(this, state);
  }
  System_String* GetHoverText() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56CC0))(this);
  }
  void EnterInspectMode() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56DC0))(this);
  }
  void LeaveInspectMode() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56DD0))(this);
  }
  bool SkipCheckDueToPlayerProximity() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C56DE0))(this);
  }
  void CheckForCatch() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C573C0))(this);
  }
  void DoRoll() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C574C0))(this);
  }
  void SpawnDeadRabbitOnSnare(ModdingAPI::Exposed::UnityEngine::GameObject* rabbitPrefab) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*, ModdingAPI::Exposed::UnityEngine::GameObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C578B0))(this, rabbitPrefab);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnareItem*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::SnareItemSaveDataProxy*> m_SnareItemSaveDataProxy = __CppStaticProperty<ModdingAPI::Exposed::SnareItemSaveDataProxy*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_SnareItemSaveDataProxy; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C57D20))();
  }
};
}