// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Bounds.hpp"


namespace ModdingAPI::Exposed {
struct __SnowImprintCustom_Il2CppStaticFields {
};

struct __SnowImprintCustom_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __SnowImprintCustom_Il2CppClass {
  Il2CppClass_1 _1;
  __SnowImprintCustom_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SnowImprintCustom_Il2CppVtbl vtbl;
};

class SnowImprintCustom {
public:
  // Il2Cpp fields:
  __SnowImprintCustom_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_Dimensions;
  float m_InsetDepth;
  float m_InsetPower;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_NormalStep;
  float m_DrawDistance;
  float m_ShadeByZ;
  float m_ShadeByZBand;
  float m_ShadeByZPower;
  bool m_CastShadows;
  bool m_ReceiveShadows;
  ModdingAPI::Exposed::UnityEngine::Mesh* m_FinalPassMesh;
  ModdingAPI::Exposed::UnityEngine::Mesh* m_DepthResetMesh;
  ModdingAPI::Exposed::UnityEngine::Material* m_DepthResetMaterial;
  ModdingAPI::Exposed::UnityEngine::Vector2 m_DepthResetTiltMinMax;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_DepthResetOffsetMin;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_DepthResetOffsetMax;
  ModdingAPI::Exposed::UnityEngine::Material* m_ImprintMaterial;
  ModdingAPI::Exposed::UnityEngine::Shader* m_ImprintExteriorShader;
  ModdingAPI::Exposed::UnityEngine::Shader* m_ImprintInteriorShader;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_MinPos;
  ModdingAPI::Exposed::UnityEngine::Vector3 m_MaxPos;
  ModdingAPI::Exposed::UnityEngine::Vector3_array* m_HermiteCoefficients;
  ModdingAPI::Exposed::System::Int32_array* m_CoeffIds;
  int32_t m_NormalStepId;
  int32_t m_ShadeByZId;
  int32_t m_MaxInsetId;
  int32_t m_InsetPowId;
  int32_t m_FadeDistanceId;
  int32_t m_VisibleDistanceId;
  ModdingAPI::Exposed::UnityEngine::Bounds m_LocalBounds;
  ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* m_MaterialPropertyBlock1;

  // Member methods:
  void Awake() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CDF870))(this);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CDFBB0))(this);
  }
  void Reposition() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CDFBC0))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  void LateUpdate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CE07B0))(this);
  }
  void BuildMaterialPropertyBlocks() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CE1270))(this);
  }
  void SetInterior(bool interior) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1CE2060))(this, interior);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SnowImprintCustom*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }
};
}