// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector3.hpp"


namespace ModdingAPI::Exposed {
struct __SpawnRegionManager_Il2CppStaticFields {
  float m_NoPredatorSpawningInVoyageurHours;
};

struct __SpawnRegionManager_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __SpawnRegionManager_Il2CppClass {
  Il2CppClass_1 _1;
  __SpawnRegionManager_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SpawnRegionManager_Il2CppVtbl vtbl;
};

class SpawnRegionManager {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C4A6F0;
  static inline    __SpawnRegionManager_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __SpawnRegionManager_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__SpawnRegionManager_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __SpawnRegionManager_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  float m_NoPredatorSpawningInVoyageurHoursMin;
  float m_NoPredatorSpawningInVoyageurHoursMax;
  float m_RandomizeRestoredSpawnsAfterHoursInside;
  float m_SpawnRegionDisableDistance;
  float m_DisallowDespawnBelowDistance;
  float m_ClosestSpawnDistanceToPlayer;
  float m_ClosestSpawnDistanceToPlayerAfterSceneTransition;
  float m_AllowSpawnOnscreenDistance;
  float m_AllowDespawnOnscreenDistance;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_SpawnRegions;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_NoSpawnRegions;
  int32_t m_NextSpawnRegionIndexToUpdate;

  // Member methods:
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D027E0))(this);
  }
  void OnAuroraEnabled(bool enabled) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D02890))(this, enabled);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D02990))(this);
  }
  void Add(ModdingAPI::Exposed::SpawnRegion* sr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::SpawnRegion*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03420))(this, sr);
  }
  void Remove(ModdingAPI::Exposed::SpawnRegion* sr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::SpawnRegion*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D034E0))(this, sr);
  }
  void Add(ModdingAPI::Exposed::NoSpawnRegion* nsr) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::NoSpawnRegion*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D035A0))(this, nsr);
  }
  ModdingAPI::Exposed::UnityEngine::GameObject* GetClosestActiveSpawn(ModdingAPI::Exposed::UnityEngine::Vector3 pos, System_String* filterSpawnablePrefabName) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::GameObject*(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::UnityEngine::Vector3, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03640))(this, pos, filterSpawnablePrefabName);
  }
  ModdingAPI::Exposed::SpawnRegion* PointInsideSpawnRegion(ModdingAPI::Exposed::UnityEngine::Vector3 pos, System_String* filterSpawnablePrefabName) {
    return reinterpret_cast<ModdingAPI::Exposed::SpawnRegion*(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::UnityEngine::Vector3, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03760))(this, pos, filterSpawnablePrefabName);
  }
  ModdingAPI::Exposed::SpawnRegion* PointInsideActiveSpawnRegion(ModdingAPI::Exposed::UnityEngine::Vector3 pos, System_String* filterSpawnablePrefabName) {
    return reinterpret_cast<ModdingAPI::Exposed::SpawnRegion*(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::UnityEngine::Vector3, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03980))(this, pos, filterSpawnablePrefabName);
  }
  bool PointInsideNoSpawnRegion(ModdingAPI::Exposed::UnityEngine::Vector3 pos) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*, ModdingAPI::Exposed::UnityEngine::Vector3)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03C00))(this, pos);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SpawnRegionManager*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D04180))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<float> m_NoPredatorSpawningInVoyageurHours = __CppStaticProperty<float>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_NoPredatorSpawningInVoyageurHours; }
  );

  // Static methods:
  static inline System_String* Serialize() {
    return reinterpret_cast<System_String*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D02C10))();
  }
  static inline void Deserialize(System_String* text) {
    reinterpret_cast<void(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03120))(text);
  }
  static inline ModdingAPI::Exposed::SpawnRegion* FindSpawnRegionByPosition(ModdingAPI::Exposed::SpawnRegionSaveData* saveData) {
    return reinterpret_cast<ModdingAPI::Exposed::SpawnRegion*(__fastcall*)(ModdingAPI::Exposed::SpawnRegionSaveData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D03E50))(saveData);
  }
  static inline ModdingAPI::Exposed::SpawnRegion* FindSpawnRegionByGuid(System_String* guid) {
    return reinterpret_cast<ModdingAPI::Exposed::SpawnRegion*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1D04090))(guid);
  }
};
}