// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.Steamworks.CGameID.hpp"
#include "ModdingAPI.Exposed.Steamworks.UserStatsReceived_t.hpp"
#include "ModdingAPI.Exposed.Steamworks.UserStatsStored_t.hpp"
#include "ModdingAPI.Exposed.Steamworks.UserAchievementStored_t.hpp"


namespace ModdingAPI::Exposed {
struct __SteamStatsAndAchievements_Il2CppStaticFields {
  bool m_DidRegisterAchievements;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* m_Achievements;
};

struct __SteamStatsAndAchievements_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __SteamStatsAndAchievements_Il2CppClass {
  Il2CppClass_1 _1;
  __SteamStatsAndAchievements_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SteamStatsAndAchievements_Il2CppVtbl vtbl;
};

class SteamStatsAndAchievements {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C30B18;
  static inline    __SteamStatsAndAchievements_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __SteamStatsAndAchievements_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__SteamStatsAndAchievements_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __SteamStatsAndAchievements_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  bool m_HasInitted;
  ModdingAPI::Exposed::Steamworks::CGameID m_GameID;
  bool m_bRequestedStats;
  bool m_bStatsValid;
  bool m_bStoreStats;
  int32_t m_nTotalGamesPlayed;

  // Member methods:
  void Init() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C71E20))(this);
  }
  void OnDestroy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C727C0))(this);
  }
  void Update() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C72B30))(this);
  }
  void UnlockAchievement(int32_t achievementId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C72D90))(this, achievementId);
  }
  bool HasUnlocked(int32_t achievementId) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C72F00))(this, achievementId);
  }
  void UnlockAchievement(ModdingAPI::Exposed::SteamStatsAndAchievements::Achievement_t* achievement) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, ModdingAPI::Exposed::SteamStatsAndAchievements::Achievement_t*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C73060))(this, achievement);
  }
  void OnUserStatsReceived(ModdingAPI::Exposed::Steamworks::UserStatsReceived_t pCallback) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, ModdingAPI::Exposed::Steamworks::UserStatsReceived_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C73090))(this, pCallback);
  }
  void OnUserStatsStored(ModdingAPI::Exposed::Steamworks::UserStatsStored_t pCallback) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, ModdingAPI::Exposed::Steamworks::UserStatsStored_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C73390))(this, pCallback);
  }
  void OnAchievementStored(ModdingAPI::Exposed::Steamworks::UserAchievementStored_t pCallback) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*, ModdingAPI::Exposed::Steamworks::UserAchievementStored_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C73550))(this, pCallback);
  }
  void ResetAllAchievements() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C73920))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::SteamStatsAndAchievements*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x389390))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<bool> m_DidRegisterAchievements = __CppStaticProperty<bool>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_DidRegisterAchievements; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*> m_Achievements = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::List_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_Achievements; }
  );

  // Static methods:
  static inline void RegisterAchievement(int32_t achievementId, System_String* achievementStringId, System_String* name, System_String* desc) {
    reinterpret_cast<void(__fastcall*)(int32_t, System_String*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C72600))(achievementId, achievementStringId, name, desc);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1C739D0))();
  }
};
}