// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.DateTime.hpp"


namespace ModdingAPI::Exposed::Storage {
struct __ContainerInfoQuery_Il2CppStaticFields {
};

struct __ContainerInfoQuery_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Dispose;
  VirtualInvokeData _5_GetEnumerator;
  VirtualInvokeData _6_System_Collections_IEnumerable_GetEnumerator;
};

struct __ContainerInfoQuery_Il2CppClass {
  Il2CppClass_1 _1;
  __ContainerInfoQuery_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ContainerInfoQuery_Il2CppVtbl vtbl;
};

class ContainerInfoQuery {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C3ADA8;
  static inline    __ContainerInfoQuery_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ContainerInfoQuery_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ContainerInfoQuery_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ContainerInfoQuery_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  uint32_t Length;
  intptr_t m_Self;

  // Member methods:
  uint64_t TotalSize(uint32_t idx) {
    return reinterpret_cast<uint64_t(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EA9A20))(this, idx);
  }
  System_String* Name(uint32_t idx) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EA9AE0))(this, idx);
  }
  System_String* DisplayName(uint32_t idx) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EA9C70))(this, idx);
  }
  ModdingAPI::Exposed::System::DateTime LastModifiedTime(uint32_t idx) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EA9E00))(this, idx);
  }
  bool NeedsSync(uint32_t idx) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA090))(this, idx);
  }
  ModdingAPI::Exposed::System::Collections::Generic::IEnumerator_T_* GetEnumerator() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IEnumerator_T_*(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA150))(this);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* System::Collections::IEnumerable::GetEnumerator() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA150))(this);
  }
  ModdingAPI::Exposed::Storage::ContainerInfo* get_Item(uint32_t i) {
    return reinterpret_cast<ModdingAPI::Exposed::Storage::ContainerInfo*(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA2A0))(this, i);
  }
  void MarshalContainerInfo(ModdingAPI::Exposed::Storage::ContainerInfo* ci, uint32_t i) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, ModdingAPI::Exposed::Storage::ContainerInfo*, uint32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA400))(this, ci, i);
  }
  void Dispose() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1EAA830))(this);
  }
  void ::ctor(uint32_t totalResults, intptr_t queryHandle) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::Storage::ContainerInfoQuery*, uint32_t, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33D7A0))(this, totalResults, queryHandle);
  }
};
}