// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Diagnostics {
struct __StackFrame_Il2CppStaticFields {
};

struct __StackFrame_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_GetFileLineNumber;
  VirtualInvokeData _5_GetFileColumnNumber;
  VirtualInvokeData _6_GetFileName;
  VirtualInvokeData _7_GetILOffset;
  VirtualInvokeData _8_GetMethod;
  VirtualInvokeData _9_GetNativeOffset;
};

struct __StackFrame_Il2CppClass {
  Il2CppClass_1 _1;
  __StackFrame_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __StackFrame_Il2CppVtbl vtbl;
};

class StackFrame {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C42EC0;
  static inline    __StackFrame_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __StackFrame_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__StackFrame_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __StackFrame_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t ilOffset;
  int32_t nativeOffset;
  int64_t methodAddress;
  uint32_t methodIndex;
  ModdingAPI::Exposed::System::Reflection::MethodBase* methodBase;
  System_String* fileName;
  int32_t lineNumber;
  int32_t columnNumber;
  System_String* internalMethodName;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6E3370))(this);
  }
  void ::ctor(int32_t skipFrames, bool fNeedFileInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6E33C0))(this, skipFrames, fNeedFileInfo);
  }
  int32_t GetFileLineNumber() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D8A0))(this);
  }
  int32_t GetFileColumnNumber() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x36D8C0))(this);
  }
  System_String* GetFileName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335370))(this);
  }
  System_String* GetSecureFileName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6E3420))(this);
  }
  int32_t GetILOffset() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311060))(this);
  }
  ModdingAPI::Exposed::System::Reflection::MethodBase* GetMethod() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodBase*(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110B0))(this);
  }
  int32_t GetNativeOffset() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311080))(this);
  }
  int64_t GetMethodAddress() {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  uint32_t GetMethodIndex() {
    return reinterpret_cast<uint32_t(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x37AAE0))(this);
  }
  System_String* GetInternalMethodName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319960))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Diagnostics::StackFrame*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6E34E0))(this);
  }

  // Static methods:
  static inline bool get_frame_info(int32_t skip, bool needFileInfo, ModdingAPI::Exposed::System::Reflection::MethodBase* method, int32_t iloffset, int32_t native_offset, System_String* file, int32_t line, int32_t column) {
    return reinterpret_cast<bool(__fastcall*)(int32_t, bool, ModdingAPI::Exposed::System::Reflection::MethodBase*, int32_t, int32_t, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6E3360))(skip, needFileInfo, method, iloffset, native_offset, file, line, column);
  }
};
}