// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates {
struct __PublicKey_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Byte_array* Empty;
};

struct __PublicKey_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __PublicKey_Il2CppClass {
  Il2CppClass_1 _1;
  __PublicKey_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __PublicKey_Il2CppVtbl vtbl;
};

class PublicKey {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C342E8;
  static inline    __PublicKey_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __PublicKey_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__PublicKey_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __PublicKey_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Security::Cryptography::AsymmetricAlgorithm* _key;
  ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData* _keyValue;
  ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData* _params;
  ModdingAPI::Exposed::System::Security::Cryptography::Oid* _oid;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::Mono::Security::X509::X509Certificate_Duplicate1* certificate) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::PublicKey*, ModdingAPI::Exposed::Mono::Security::X509::X509Certificate_Duplicate1*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB10710))(this, certificate);
  }
  ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData* get_EncodedKeyValue() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData*(__fastcall*)(ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::PublicKey*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData* get_EncodedParameters() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::AsnEncodedData*(__fastcall*)(ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::PublicKey*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110A0))(this);
  }
  ModdingAPI::Exposed::System::Security::Cryptography::AsymmetricAlgorithm* get_Key() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::AsymmetricAlgorithm*(__fastcall*)(ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::PublicKey*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB10E80))(this);
  }
  ModdingAPI::Exposed::System::Security::Cryptography::Oid* get_Oid() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::Oid*(__fastcall*)(ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::PublicKey*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110B0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Byte_array*> Empty = __CppStaticProperty<ModdingAPI::Exposed::System::Byte_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->Empty; }
  );

  // Static methods:
  static inline ModdingAPI::Exposed::System::Byte_array* GetUnsignedBigInteger(ModdingAPI::Exposed::System::Byte_array* integer) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Byte_array*(__fastcall*)(ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB110D0))(integer);
  }
  static inline ModdingAPI::Exposed::System::Security::Cryptography::DSA* DecodeDSA(ModdingAPI::Exposed::System::Byte_array* rawPublicKey, ModdingAPI::Exposed::System::Byte_array* rawParameters) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::DSA*(__fastcall*)(ModdingAPI::Exposed::System::Byte_array*, ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB111C0))(rawPublicKey, rawParameters);
  }
  static inline ModdingAPI::Exposed::System::Security::Cryptography::RSA* DecodeRSA(ModdingAPI::Exposed::System::Byte_array* rawPublicKey) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::RSA*(__fastcall*)(ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB11810))(rawPublicKey);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xB11C80))();
  }
};
}