// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Xml {
struct __XmlAsyncCheckReader_Il2CppStaticFields {
};

struct __XmlAsyncCheckReader_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Dispose;
  VirtualInvokeData _5_get_Settings;
  VirtualInvokeData _6_get_NodeType;
  VirtualInvokeData _7_get_Name;
  VirtualInvokeData _8_get_LocalName;
  VirtualInvokeData _9_get_NamespaceURI;
  VirtualInvokeData _10_get_Prefix;
  VirtualInvokeData _11_get_HasValue;
  VirtualInvokeData _12_get_Value;
  VirtualInvokeData _13_get_Depth;
  VirtualInvokeData _14_get_BaseURI;
  VirtualInvokeData _15_get_IsEmptyElement;
  VirtualInvokeData _16_get_IsDefault;
  VirtualInvokeData _17_get_SchemaInfo;
  VirtualInvokeData _18_ReadContentAsString;
  VirtualInvokeData _19_get_AttributeCount;
  VirtualInvokeData _20_MoveToAttribute;
  VirtualInvokeData _21_MoveToAttribute;
  VirtualInvokeData _22_MoveToFirstAttribute;
  VirtualInvokeData _23_MoveToNextAttribute;
  VirtualInvokeData _24_MoveToElement;
  VirtualInvokeData _25_ReadAttributeValue;
  VirtualInvokeData _26_Read;
  VirtualInvokeData _27_get_EOF;
  VirtualInvokeData _28_Close;
  VirtualInvokeData _29_get_ReadState;
  VirtualInvokeData _30_get_NameTable;
  VirtualInvokeData _31_LookupNamespace;
  VirtualInvokeData _32_get_CanResolveEntity;
  VirtualInvokeData _33_ResolveEntity;
  VirtualInvokeData _34_MoveToContent;
  VirtualInvokeData _35_ReadStartElement;
  VirtualInvokeData _36_ReadEndElement;
  VirtualInvokeData _37_IsStartElement;
  VirtualInvokeData _38_Dispose;
  VirtualInvokeData _39_get_NamespaceManager;
  VirtualInvokeData _40_get_DtdInfo;
};

struct __XmlAsyncCheckReader_Il2CppClass {
  Il2CppClass_1 _1;
  __XmlAsyncCheckReader_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __XmlAsyncCheckReader_Il2CppVtbl vtbl;
};

class XmlAsyncCheckReader {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C81388;
  static inline    __XmlAsyncCheckReader_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __XmlAsyncCheckReader_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__XmlAsyncCheckReader_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __XmlAsyncCheckReader_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Xml::XmlReader* coreReader;
  ModdingAPI::Exposed::System::Threading::Tasks::Task* lastTask;

  // Member methods:
  ModdingAPI::Exposed::System::Xml::XmlReader* get_CoreReader() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::XmlReader*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  void ::ctor(ModdingAPI::Exposed::System::Xml::XmlReader* reader) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, ModdingAPI::Exposed::System::Xml::XmlReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BB880))(this, reader);
  }
  void CheckAsync() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BB960))(this);
  }
  ModdingAPI::Exposed::System::Xml::XmlReaderSettings* get_Settings() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::XmlReaderSettings*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBA40))(this);
  }
  int32_t get_NodeType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBC50))(this);
  }
  System_String* get_Name() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBC90))(this);
  }
  System_String* get_LocalName() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBCD0))(this);
  }
  System_String* get_NamespaceURI() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBD10))(this);
  }
  System_String* get_Prefix() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBD50))(this);
  }
  bool get_HasValue() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBD90))(this);
  }
  System_String* get_Value() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBDD0))(this);
  }
  int32_t get_Depth() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBE10))(this);
  }
  System_String* get_BaseURI() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBE50))(this);
  }
  bool get_IsEmptyElement() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBE90))(this);
  }
  bool get_IsDefault() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBED0))(this);
  }
  ModdingAPI::Exposed::System::Xml::Schema::IXmlSchemaInfo* get_SchemaInfo() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::Schema::IXmlSchemaInfo*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBF10))(this);
  }
  System_String* ReadContentAsString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBF50))(this);
  }
  int32_t get_AttributeCount() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBF90))(this);
  }
  bool MoveToAttribute(System_String* name) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BBFD0))(this, name);
  }
  void MoveToAttribute(int32_t i) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC020))(this, i);
  }
  bool MoveToFirstAttribute() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC070))(this);
  }
  bool MoveToNextAttribute() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC0B0))(this);
  }
  bool MoveToElement() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC0F0))(this);
  }
  bool ReadAttributeValue() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC130))(this);
  }
  bool Read() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC170))(this);
  }
  bool get_EOF() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC1B0))(this);
  }
  void Close() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC1F0))(this);
  }
  int32_t get_ReadState() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC230))(this);
  }
  ModdingAPI::Exposed::System::Xml::XmlNameTable* get_NameTable() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::XmlNameTable*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC270))(this);
  }
  System_String* LookupNamespace(System_String* prefix) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC2B0))(this, prefix);
  }
  bool get_CanResolveEntity() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC300))(this);
  }
  void ResolveEntity() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC340))(this);
  }
  int32_t MoveToContent() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC380))(this);
  }
  void ReadStartElement(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC3C0))(this, name);
  }
  void ReadEndElement() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC410))(this);
  }
  bool IsStartElement() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC450))(this);
  }
  void Dispose(bool disposing) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC490))(this, disposing);
  }
  ModdingAPI::Exposed::System::Xml::XmlNamespaceManager* get_NamespaceManager() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::XmlNamespaceManager*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC4D0))(this);
  }
  ModdingAPI::Exposed::System::Xml::IDtdInfo* get_DtdInfo() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::IDtdInfo*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BC510))(this);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader* CreateAsyncCheckWrapper(ModdingAPI::Exposed::System::Xml::XmlReader* reader) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::XmlAsyncCheckReader*(__fastcall*)(ModdingAPI::Exposed::System::Xml::XmlReader*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9BB260))(reader);
  }
};
}