// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Security::Permissions {
struct __SecurityPermission_Il2CppStaticFields {
};

struct __SecurityPermission_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_System_Security_IPermission_Demand;
  VirtualInvokeData _7_Demand;
  VirtualInvokeData _8_IsSubsetOf;
  VirtualInvokeData _9_ToXml;
  VirtualInvokeData _10_IsUnrestricted;
};

struct __SecurityPermission_Il2CppClass {
  Il2CppClass_1 _1;
  __SecurityPermission_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SecurityPermission_Il2CppVtbl vtbl;
};

class SecurityPermission {
  static constexpr uint64_t         _rvaObjectInstance     = 0x3C4A3F8;
  static inline    SecurityPermission* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t                     _rvaClassInstance     = 0x3C4A3B0;
  static inline    __SecurityPermission_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Singleton object getter:
  static inline SecurityPermission* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (SecurityPermission**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

// Static class getter:
  static inline __SecurityPermission_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__SecurityPermission_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __SecurityPermission_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  int32_t flags;

  // Member methods:
  void ::ctor(int32_t state) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948C30))(this, state);
  }
  void ::ctor(int32_t flag) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948C60))(this, flag);
  }
  void set_Flags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948C60))(this, value);
  }
  bool IsUnrestricted() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948D60))(this);
  }
  bool IsSubsetOf(ModdingAPI::Exposed::System::Security::IPermission* target) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*, ModdingAPI::Exposed::System::Security::IPermission*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948D70))(this, target);
  }
  ModdingAPI::Exposed::System::Security::SecurityElement* ToXml() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::SecurityElement*(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948EA0))(this);
  }
  bool IsEmpty() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948FC0))(this);
  }
  ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission* Cast(ModdingAPI::Exposed::System::Security::IPermission* target) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*(__fastcall*)(ModdingAPI::Exposed::System::Security::Permissions::SecurityPermission*, ModdingAPI::Exposed::System::Security::IPermission*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x948FD0))(this, target);
  }
};
}