// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::IO::Stream {
struct __SynchronousAsyncResult_Il2CppStaticFields {
};

struct __SynchronousAsyncResult_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_get_IsCompleted;
  VirtualInvokeData _5_get_AsyncWaitHandle;
  VirtualInvokeData _6_get_AsyncState;
  VirtualInvokeData _7_get_CompletedSynchronously;
};

struct __SynchronousAsyncResult_Il2CppClass {
  Il2CppClass_1 _1;
  __SynchronousAsyncResult_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __SynchronousAsyncResult_Il2CppVtbl vtbl;
};

class SynchronousAsyncResult {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C96210;
  static inline    __SynchronousAsyncResult_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __SynchronousAsyncResult_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__SynchronousAsyncResult_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __SynchronousAsyncResult_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  Il2CppObject* _stateObject;
  bool _isWrite;
  ModdingAPI::Exposed::System::Threading::ManualResetEvent* _waitHandle;
  ModdingAPI::Exposed::System::Runtime::ExceptionServices::ExceptionDispatchInfo* _exceptionInfo;
  bool _endXxxCalled;
  int32_t _bytesRead;

  // Member methods:
  void ::ctor(int32_t bytesRead, Il2CppObject* asyncStateObject) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*, int32_t, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA5040))(this, bytesRead, asyncStateObject);
  }
  void ::ctor(Il2CppObject* asyncStateObject) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA5050))(this, asyncStateObject);
  }
  void ::ctor(ModdingAPI::Exposed::System::Exception* ex, Il2CppObject* asyncStateObject, bool isWrite) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*, ModdingAPI::Exposed::System::Exception*, Il2CppObject*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA5060))(this, ex, asyncStateObject, isWrite);
  }
  bool get_IsCompleted() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x403F70))(this);
  }
  ModdingAPI::Exposed::System::Threading::WaitHandle* get_AsyncWaitHandle() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Threading::WaitHandle*(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA50B0))(this);
  }
  Il2CppObject* get_AsyncState() {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  bool get_CompletedSynchronously() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x403F70))(this);
  }
  void ThrowIfError() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::IO::Stream::SynchronousAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA52B0))(this);
  }

  // Static methods:
  static inline int32_t EndRead(ModdingAPI::Exposed::System::IAsyncResult* asyncResult) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::IAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA3880))(asyncResult);
  }
  static inline void EndWrite(ModdingAPI::Exposed::System::IAsyncResult* asyncResult) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::IAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xCA3BE0))(asyncResult);
  }
};
}