// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.DateTime.hpp"
#include "ModdingAPI.Exposed.System.DateTimeOffset.hpp"
#include "ModdingAPI.Exposed.System.Decimal.hpp"


namespace ModdingAPI::Exposed::System::Xml::Schema {
struct __XmlUntypedConverter_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter* Untyped;
  ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter* UntypedList;
};

struct __XmlUntypedConverter_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_ToBoolean;
  VirtualInvokeData _5_ToBoolean;
  VirtualInvokeData _6_ToBoolean;
  VirtualInvokeData _7_ToBoolean;
  VirtualInvokeData _8_ToBoolean;
  VirtualInvokeData _9_ToBoolean;
  VirtualInvokeData _10_ToInt32;
  VirtualInvokeData _11_ToInt32;
  VirtualInvokeData _12_ToInt32;
  VirtualInvokeData _13_ToInt32;
  VirtualInvokeData _14_ToInt32;
  VirtualInvokeData _15_ToInt32;
  VirtualInvokeData _16_ToInt64;
  VirtualInvokeData _17_ToInt64;
  VirtualInvokeData _18_ToInt64;
  VirtualInvokeData _19_ToInt64;
  VirtualInvokeData _20_ToInt64;
  VirtualInvokeData _21_ToInt64;
  VirtualInvokeData _22_ToDecimal;
  VirtualInvokeData _23_ToDecimal;
  VirtualInvokeData _24_ToDouble;
  VirtualInvokeData _25_ToDouble;
  VirtualInvokeData _26_ToDouble;
  VirtualInvokeData _27_ToDouble;
  VirtualInvokeData _28_ToDouble;
  VirtualInvokeData _29_ToDouble;
  VirtualInvokeData _30_ToSingle;
  VirtualInvokeData _31_ToSingle;
  VirtualInvokeData _32_ToSingle;
  VirtualInvokeData _33_ToDateTime;
  VirtualInvokeData _34_ToDateTime;
  VirtualInvokeData _35_ToDateTime;
  VirtualInvokeData _36_ToDateTime;
  VirtualInvokeData _37_ToDateTime;
  VirtualInvokeData _38_ToDateTime;
  VirtualInvokeData _39_ToDateTime;
  VirtualInvokeData _40_ToDateTimeOffset;
  VirtualInvokeData _41_ToDateTimeOffset;
  VirtualInvokeData _42_ToDateTimeOffset;
  VirtualInvokeData _43_ToString;
  VirtualInvokeData _44_ToString;
  VirtualInvokeData _45_ToString;
  VirtualInvokeData _46_ToString;
  VirtualInvokeData _47_ToString;
  VirtualInvokeData _48_ToString;
  VirtualInvokeData _49_ToString;
  VirtualInvokeData _50_ToString;
  VirtualInvokeData _51_ToString;
  VirtualInvokeData _52_ToString;
  VirtualInvokeData _53_ChangeType;
  VirtualInvokeData _54_ChangeType;
  VirtualInvokeData _55_ChangeType;
  VirtualInvokeData _56_ChangeType;
  VirtualInvokeData _57_ChangeType;
  VirtualInvokeData _58_ChangeType;
  VirtualInvokeData _59_ChangeType;
  VirtualInvokeData _60_ChangeType;
  VirtualInvokeData _61_ChangeType;
  VirtualInvokeData _62_ChangeListType;
};

struct __XmlUntypedConverter_Il2CppClass {
  Il2CppClass_1 _1;
  __XmlUntypedConverter_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __XmlUntypedConverter_Il2CppVtbl vtbl;
};

class XmlUntypedConverter {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C80040;
  static inline    __XmlUntypedConverter_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __XmlUntypedConverter_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__XmlUntypedConverter_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __XmlUntypedConverter_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaType* XmlBaseConverter_schemaType;
  int32_t XmlBaseConverter_typeCode;
  ModdingAPI::Exposed::System::Type* XmlBaseConverter_clrTypeDefault;
  ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter* atomicConverter;
  bool allowListToList;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC75D60))(this);
  }
  void ::ctor(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter* atomicConverter, bool allowListToList) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC75F20))(this, atomicConverter, allowListToList);
  }
  bool ToBoolean(System_String* value) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC760D0))(this, value);
  }
  bool ToBoolean(Il2CppObject* value) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC761A0))(this, value);
  }
  ModdingAPI::Exposed::System::DateTime ToDateTime(System_String* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC763A0))(this, value);
  }
  ModdingAPI::Exposed::System::DateTime ToDateTime(Il2CppObject* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76470))(this, value);
  }
  ModdingAPI::Exposed::System::DateTimeOffset ToDateTimeOffset(System_String* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTimeOffset(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76670))(this, value);
  }
  ModdingAPI::Exposed::System::DateTimeOffset ToDateTimeOffset(Il2CppObject* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTimeOffset(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76760))(this, value);
  }
  ModdingAPI::Exposed::System::Decimal ToDecimal(System_String* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Decimal(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76970))(this, value);
  }
  ModdingAPI::Exposed::System::Decimal ToDecimal(Il2CppObject* value) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Decimal(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76A60))(this, value);
  }
  double ToDouble(System_String* value) {
    return reinterpret_cast<double(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76C70))(this, value);
  }
  double ToDouble(Il2CppObject* value) {
    return reinterpret_cast<double(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76D40))(this, value);
  }
  int32_t ToInt32(System_String* value) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC76F50))(this, value);
  }
  int32_t ToInt32(Il2CppObject* value) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77050))(this, value);
  }
  int64_t ToInt64(System_String* value) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77270))(this, value);
  }
  int64_t ToInt64(Il2CppObject* value) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77370))(this, value);
  }
  float ToSingle(System_String* value) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77590))(this, value);
  }
  float ToSingle(Il2CppObject* value) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77660))(this, value);
  }
  System_String* ToString(bool value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77870))(this, value);
  }
  System_String* ToString(ModdingAPI::Exposed::System::DateTime value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::DateTime)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77910))(this, value);
  }
  System_String* ToString(ModdingAPI::Exposed::System::DateTimeOffset value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::DateTimeOffset)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC779D0))(this, value);
  }
  System_String* ToString(ModdingAPI::Exposed::System::Decimal value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::Decimal)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77AA0))(this, value);
  }
  System_String* ToString(double value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77B60))(this, value);
  }
  System_String* ToString(int32_t value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77C00))(this, value);
  }
  System_String* ToString(int64_t value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77CB0))(this, value);
  }
  System_String* ToString(float value) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77D60))(this, value);
  }
  System_String* ToString(Il2CppObject* value, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC77E00))(this, value, nsResolver);
  }
  Il2CppObject* ChangeType(bool value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, bool, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC78DF0))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(ModdingAPI::Exposed::System::DateTime value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::DateTime, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79000))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(ModdingAPI::Exposed::System::Decimal value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::Decimal, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79230))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(double value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, double, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79460))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(int32_t value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, int32_t, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79670))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(int64_t value, ModdingAPI::Exposed::System::Type* destinationType) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, int64_t, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79890))(this, value, destinationType);
  }
  Il2CppObject* ChangeType(System_String* value, ModdingAPI::Exposed::System::Type* destinationType, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, System_String*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC79AB0))(this, value, destinationType, nsResolver);
  }
  Il2CppObject* ChangeType(Il2CppObject* value, ModdingAPI::Exposed::System::Type* destinationType, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7AAB0))(this, value, destinationType, nsResolver);
  }
  Il2CppObject* ChangeTypeWildcardDestination(Il2CppObject* value, ModdingAPI::Exposed::System::Type* destinationType, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7C650))(this, value, destinationType, nsResolver);
  }
  Il2CppObject* ChangeTypeWildcardSource(Il2CppObject* value, ModdingAPI::Exposed::System::Type* destinationType, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7C7C0))(this, value, destinationType, nsResolver);
  }
  Il2CppObject* ChangeListType(Il2CppObject* value, ModdingAPI::Exposed::System::Type* destinationType, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver* nsResolver) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, Il2CppObject*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Xml::IXmlNamespaceResolver*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7CAA0))(this, value, destinationType, nsResolver);
  }
  bool SupportsType(ModdingAPI::Exposed::System::Type* clrType) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlUntypedConverter*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7CE10))(this, clrType);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter*> Untyped = __CppStaticProperty<ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter*>(
   []() { return &GetStaticClassInstance()->pStaticFields->Untyped; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter*> UntypedList = __CppStaticProperty<ModdingAPI::Exposed::System::Xml::Schema::XmlValueConverter*>(
   []() { return &GetStaticClassInstance()->pStaticFields->UntypedList; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xC7D580))();
  }
};
}