// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Globalization {
struct __IdnMapping_Il2CppStaticFields {
};

struct __IdnMapping_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __IdnMapping_Il2CppClass {
  Il2CppClass_1 _1;
  __IdnMapping_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __IdnMapping_Il2CppVtbl vtbl;
};

class IdnMapping {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C78990;
  static inline    __IdnMapping_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __IdnMapping_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__IdnMapping_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __IdnMapping_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  bool allow_unassigned;
  bool use_std3;
  ModdingAPI::Exposed::System::Globalization::Punycode* puny;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9F930))(this);
  }
  bool Equals(Il2CppObject* obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9FAB0))(this, obj);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9FB70))(this);
  }
  System_String* GetAscii(System_String* unicode) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9FB90))(this, unicode);
  }
  System_String* GetAscii(System_String* unicode, int32_t index, int32_t count) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9FD10))(this, unicode, index, count);
  }
  System_String* Convert(System_String* input, int32_t index, int32_t count, bool toAscii) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF9FE80))(this, input, index, count, toAscii);
  }
  System_String* ToAscii(System_String* s, int32_t offset) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA0120))(this, s, offset);
  }
  void VerifyLength(System_String* s, int32_t offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA05A0))(this, s, offset);
  }
  System_String* NamePrep(System_String* s, int32_t offset) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA06F0))(this, s, offset);
  }
  void VerifyProhibitedCharacters(System_String* s, int32_t offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA0870))(this, s, offset);
  }
  void VerifyStd3AsciiRules(System_String* s, int32_t offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA0AB0))(this, s, offset);
  }
  System_String* GetUnicode(System_String* ascii) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA0D10))(this, ascii);
  }
  System_String* GetUnicode(System_String* ascii, int32_t index, int32_t count) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA0E90))(this, ascii, index, count);
  }
  System_String* ToUnicode(System_String* s, int32_t offset) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Globalization::IdnMapping*, System_String*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA1000))(this, s, offset);
  }
};
}