// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Net.HttpWebRequest.AuthorizationState.hpp"
#include "ModdingAPI.Exposed.System.Runtime.Serialization.StreamingContext.hpp"


namespace ModdingAPI::Exposed::System::Net {
struct __HttpWebRequest_Il2CppStaticFields {
  int32_t defaultMaxResponseHeadersLength;
};

struct __HttpWebRequest_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_CreateObjRef;
  VirtualInvokeData _5_InitializeLifetimeService;
  VirtualInvokeData _6_System_Runtime_Serialization_ISerializable_GetObjectData;
  VirtualInvokeData _7_GetObjectData;
  VirtualInvokeData _8_set_CachePolicy;
  VirtualInvokeData _9_get_Method;
  VirtualInvokeData _10_set_Method;
  VirtualInvokeData _11_get_RequestUri;
  VirtualInvokeData _12_get_Headers;
  VirtualInvokeData _13_get_ContentLength;
  VirtualInvokeData _14_get_Credentials;
  VirtualInvokeData _15_set_Credentials;
  VirtualInvokeData _16_get_Proxy;
  VirtualInvokeData _17_set_Proxy;
  VirtualInvokeData _18_get_Timeout;
  VirtualInvokeData _19_GetResponse;
  VirtualInvokeData _20_BeginGetResponse;
  VirtualInvokeData _21_EndGetResponse;
  VirtualInvokeData _22_Abort;
  VirtualInvokeData _23_get_AllowWriteStreamBuffering;
};

struct __HttpWebRequest_Il2CppClass {
  Il2CppClass_1 _1;
  __HttpWebRequest_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __HttpWebRequest_Il2CppVtbl vtbl;
};

class HttpWebRequest {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C32468;
  static inline    __HttpWebRequest_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __HttpWebRequest_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__HttpWebRequest_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __HttpWebRequest_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  Il2CppObject* MarshalByRefObject__identity;
  int32_t WebRequest_m_AuthenticationLevel;
  int32_t WebRequest_m_ImpersonationLevel;
  ModdingAPI::Exposed::System::Net::Cache::RequestCachePolicy* WebRequest_m_CachePolicy;
  ModdingAPI::Exposed::System::Net::Cache::RequestCacheProtocol* WebRequest_m_CacheProtocol;
  ModdingAPI::Exposed::System::Net::Cache::RequestCacheBinding* WebRequest_m_CacheBinding;
  ModdingAPI::Exposed::System::Uri* requestUri;
  ModdingAPI::Exposed::System::Uri* actualUri;
  bool hostChanged;
  bool allowAutoRedirect;
  bool allowBuffering;
  ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::X509CertificateCollection* certificates;
  System_String* connectionGroup;
  bool haveContentLength;
  int64_t contentLength;
  ModdingAPI::Exposed::System::Net::HttpContinueDelegate* continueDelegate;
  ModdingAPI::Exposed::System::Net::CookieContainer* cookieContainer;
  ModdingAPI::Exposed::System::Net::ICredentials* credentials;
  bool haveResponse;
  bool haveRequest;
  bool requestSent;
  ModdingAPI::Exposed::System::Net::WebHeaderCollection* webHeaders;
  bool keepAlive;
  int32_t maxAutoRedirect;
  System_String* mediaType;
  System_String* method;
  System_String* initialMethod;
  bool pipelined;
  bool preAuthenticate;
  bool usedPreAuth;
  ModdingAPI::Exposed::System::Version* version;
  bool force_version;
  ModdingAPI::Exposed::System::Version* actualVersion;
  ModdingAPI::Exposed::System::Net::IWebProxy* proxy;
  bool sendChunked;
  ModdingAPI::Exposed::System::Net::ServicePoint* servicePoint;
  int32_t timeout;
  ModdingAPI::Exposed::System::Net::WebConnectionStream* writeStream;
  ModdingAPI::Exposed::System::Net::HttpWebResponse* webResponse;
  ModdingAPI::Exposed::System::Net::WebAsyncResult* asyncWrite;
  ModdingAPI::Exposed::System::Net::WebAsyncResult* asyncRead;
  ModdingAPI::Exposed::System::EventHandler* abortHandler;
  int32_t aborted;
  bool gotRequestStream;
  int32_t redirects;
  bool expectContinue;
  ModdingAPI::Exposed::System::Byte_array* bodyBuffer;
  int32_t bodyBufferLength;
  bool getResponseCalled;
  ModdingAPI::Exposed::System::Exception* saved_exc;
  Il2CppObject* locker;
  bool finished_reading;
  ModdingAPI::Exposed::System::Net::WebConnection* WebConnection;
  int32_t auto_decomp;
  int32_t readWriteTimeout;
  ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsProvider* tlsProvider;
  ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsSettings* tlsSettings;
  ModdingAPI::Exposed::System::Net::ServerCertValidationCallback* certValidationCallback;
  ModdingAPI::Exposed::System::Net::HttpWebRequest::AuthorizationState auth_state;
  ModdingAPI::Exposed::System::Net::HttpWebRequest::AuthorizationState proxy_auth_state;
  System_String* host;
  ModdingAPI::Exposed::System::Action_T_* ResendContentFactory;
  bool _ThrowOnError_k__BackingField;
  bool unsafe_auth_blah;
  bool _ReuseConnection_k__BackingField;
  ModdingAPI::Exposed::System::Net::WebConnection* StoredConnection;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Uri* uri) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Uri*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931120))(this, uri);
  }
  void ::ctor(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931460))(this, serializationInfo, streamingContext);
  }
  void ResetAuthorization() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931AE0))(this);
  }
  ModdingAPI::Exposed::System::Uri* get_Address() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Uri*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319960))(this);
  }
  void set_Address(ModdingAPI::Exposed::System::Uri* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Uri*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x31F420))(this, value);
  }
  bool get_AllowWriteStreamBuffering() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931B20))(this);
  }
  int32_t get_AutomaticDecompression() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x79CBA0))(this);
  }
  bool get_InternalAllowBuffering() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931B30))(this);
  }
  bool get_MethodWithBuffer() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931B40))(this);
  }
  ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsProvider* get_TlsProvider() {
    return reinterpret_cast<ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsProvider*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4001D0))(this);
  }
  ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsSettings* get_TlsSettings() {
    return reinterpret_cast<ModdingAPI::Exposed::Mono::Security::Interface::MonoTlsSettings*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4002A0))(this);
  }
  ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::X509CertificateCollection* get_ClientCertificates() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Security::Cryptography::X509Certificates::X509CertificateCollection*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931CA0))(this);
  }
  int64_t get_ContentLength() {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319930))(this);
  }
  void set_InternalContentLength(int64_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x33A4C0))(this, value);
  }
  bool get_ThrowOnError() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E00))(this);
  }
  void set_ThrowOnError(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E10))(this, value);
  }
  ModdingAPI::Exposed::System::Net::ICredentials* get_Credentials() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::ICredentials*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x321390))(this);
  }
  void set_Credentials(ModdingAPI::Exposed::System::Net::ICredentials* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::ICredentials*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x47E020))(this, value);
  }
  ModdingAPI::Exposed::System::Net::WebHeaderCollection* get_Headers() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::WebHeaderCollection*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC530))(this);
  }
  System_String* get_Host() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E20))(this);
  }
  bool get_KeepAlive() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E50))(this);
  }
  int32_t get_ReadWriteTimeout() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E60))(this);
  }
  System_String* get_Method() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30F140))(this);
  }
  void set_Method(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x931E70))(this, value);
  }
  ModdingAPI::Exposed::System::Net::IWebProxy* get_Proxy() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::IWebProxy*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3EBFD0))(this);
  }
  void set_Proxy(ModdingAPI::Exposed::System::Net::IWebProxy* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::IWebProxy*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9320A0))(this, value);
  }
  ModdingAPI::Exposed::System::Uri* get_RequestUri() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Uri*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319970))(this);
  }
  bool get_SendChunked() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932180))(this);
  }
  ModdingAPI::Exposed::System::Net::ServicePoint* get_ServicePoint() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::ServicePoint*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932190))(this);
  }
  ModdingAPI::Exposed::System::Net::ServicePoint* get_ServicePointNoLock() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::ServicePoint*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30F200))(this);
  }
  int32_t get_Timeout() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9321A0))(this);
  }
  System_String* get_TransferEncoding() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9321B0))(this);
  }
  bool get_UnsafeAuthenticatedConnectionSharing() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932250))(this);
  }
  bool get_ExpectContinue() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932260))(this);
  }
  void set_ExpectContinue(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932270))(this, value);
  }
  ModdingAPI::Exposed::System::Uri* get_AuthUri() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Uri*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319960))(this);
  }
  bool get_ProxyQuery() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932280))(this);
  }
  ModdingAPI::Exposed::System::Net::ServerCertValidationCallback* get_ServerCertValidationCallback() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::ServerCertValidationCallback*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x400370))(this);
  }
  ModdingAPI::Exposed::System::Net::ServicePoint* GetServicePoint() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::ServicePoint*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9322C0))(this);
  }
  bool CheckIfForceWrite(ModdingAPI::Exposed::System::Net::SimpleAsyncResult* result) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::SimpleAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932460))(this, result);
  }
  ModdingAPI::Exposed::System::IAsyncResult* BeginGetResponse(ModdingAPI::Exposed::System::AsyncCallback* callback, Il2CppObject* state) {
    return reinterpret_cast<ModdingAPI::Exposed::System::IAsyncResult*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::AsyncCallback*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932640))(this, callback, state);
  }
  ModdingAPI::Exposed::System::Net::WebResponse* EndGetResponse(ModdingAPI::Exposed::System::IAsyncResult* asyncResult) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::WebResponse*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::IAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932C70))(this, asyncResult);
  }
  ModdingAPI::Exposed::System::Net::WebResponse* GetResponse() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Net::WebResponse*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932E30))(this);
  }
  bool get_FinishedReading() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x7AA820))(this);
  }
  void set_FinishedReading(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932F30))(this, value);
  }
  bool get_Aborted() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932F40))(this);
  }
  void Abort() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x932F60))(this);
  }
  void System::Runtime::Serialization::ISerializable::GetObjectData(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0x91D8C0))(this, serializationInfo, streamingContext);
  }
  void GetObjectData(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9333F0))(this, serializationInfo, streamingContext);
  }
  void CheckRequestStarted() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x933720))(this);
  }
  void DoContinueDelegate(int32_t statusCode, ModdingAPI::Exposed::System::Net::WebHeaderCollection* headers) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, int32_t, ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9337D0))(this, statusCode, headers);
  }
  void RewriteRedirectToGet() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9337F0))(this);
  }
  bool Redirect(ModdingAPI::Exposed::System::Net::WebAsyncResult* result, int32_t code, ModdingAPI::Exposed::System::Net::WebResponse* response) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebAsyncResult*, int32_t, ModdingAPI::Exposed::System::Net::WebResponse*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9338E0))(this, result, code, response);
  }
  System_String* GetHeaders() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9341A0))(this);
  }
  void DoPreAuthenticate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x934C10))(this);
  }
  void SetWriteStreamError(int32_t status, ModdingAPI::Exposed::System::Exception* exc) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, int32_t, ModdingAPI::Exposed::System::Exception*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x934E30))(this, status, exc);
  }
  ModdingAPI::Exposed::System::Byte_array* GetRequestHeaders() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Byte_array*(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9351A0))(this);
  }
  void SetWriteStream(ModdingAPI::Exposed::System::Net::WebConnectionStream* stream) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebConnectionStream*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x935750))(this, stream);
  }
  void SetWriteStreamInner(ModdingAPI::Exposed::System::Net::SimpleAsyncCallback* callback) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::SimpleAsyncCallback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x935970))(this, callback);
  }
  void SetWriteStreamError(ModdingAPI::Exposed::System::Exception* exc) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Exception*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x935AD0))(this, exc);
  }
  void SetResponseError(int32_t status, ModdingAPI::Exposed::System::Exception* e, System_String* where) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, int32_t, ModdingAPI::Exposed::System::Exception*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x935BB0))(this, status, e, where);
  }
  void CheckSendError(ModdingAPI::Exposed::System::Net::WebConnectionData* data) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebConnectionData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x935FB0))(this, data);
  }
  bool HandleNtlmAuth(ModdingAPI::Exposed::System::Net::WebAsyncResult* r) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9361E0))(this, r);
  }
  void SetResponseData(ModdingAPI::Exposed::System::Net::WebConnectionData* data) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebConnectionData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x936400))(this, data);
  }
  bool CheckAuthorization(ModdingAPI::Exposed::System::Net::WebResponse* response, int32_t code) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebResponse*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x936F00))(this, response, code);
  }
  bool CheckFinalStatus(ModdingAPI::Exposed::System::Net::WebAsyncResult* result) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::WebAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x936F30))(this, result);
  }
  bool get_ReuseConnection() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937A50))(this);
  }
  void set_ReuseConnection(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937A60))(this, value);
  }
  void _SetWriteStream_b__258_0(ModdingAPI::Exposed::System::Net::SimpleAsyncResult* result) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::SimpleAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937A70))(this, result);
  }
  void _SetWriteStream_b__258_1(ModdingAPI::Exposed::System::Net::SimpleAsyncResult* inner) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::SimpleAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937D40))(this, inner);
  }
  bool _SetWriteStreamInner_b__259_0(ModdingAPI::Exposed::System::Net::SimpleAsyncResult* result) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*, ModdingAPI::Exposed::System::Net::SimpleAsyncResult*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937DE0))(this, result);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::HttpWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x937EE0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<int32_t> defaultMaxResponseHeadersLength = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->defaultMaxResponseHeadersLength; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x9310A0))();
  }
};
}