// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI::Exposed::Mono::RuntimePropertyHandle.hpp"
#include "ModdingAPI::Exposed::System::RuntimeTypeHandle.hpp"


namespace ModdingAPI::Exposed::System::Reflection {
struct __PropertyInfo_Il2CppStaticFields {
};

struct __PropertyInfo_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _7_get_MemberType;
  VirtualInvokeData _11_GetCustomAttributes;
  VirtualInvokeData _12_GetCustomAttributes;
  VirtualInvokeData _13_IsDefined;
  VirtualInvokeData _14_GetCustomAttributesData;
  VirtualInvokeData _15_get_MetadataToken;
  VirtualInvokeData _16_get_Module;
  VirtualInvokeData _22_GetGetMethod;
  VirtualInvokeData _25_GetSetMethod;
  VirtualInvokeData _27_GetValue;
  VirtualInvokeData _29_SetValue;
  VirtualInvokeData _31_GetOptionalCustomModifiers;
  VirtualInvokeData _32_GetRequiredCustomModifiers;
  VirtualInvokeData _33_GetConstantValue;
  VirtualInvokeData _34_GetRawConstantValue;
  VirtualInvokeData _65535__ctor;
};

struct __PropertyInfo_Il2CppClass {
  Il2CppClass_1 _1;
  __PropertyInfo_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __PropertyInfo_Il2CppVtbl vtbl;
};

class PropertyInfo {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C91CC0;
  static inline    __PropertyInfo_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __PropertyInfo_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__PropertyInfo_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __PropertyInfo_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member methods:
  int32_t get_MemberType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x37AB70))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  ModdingAPI::Exposed::System::Reflection::MethodInfo* GetGetMethod() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF1BD70))(this);
  }
  ModdingAPI::Exposed::System::Reflection::MethodInfo* GetSetMethod() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::MethodInfo*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF28290))(this);
  }
  Il2CppObject* GetValue(Il2CppObject* obj, ModdingAPI::Exposed::System::Object_array* index) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*, Il2CppObject*, ModdingAPI::Exposed::System::Object_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF267C0))(this, obj, index);
  }
  Il2CppObject* GetValue(Il2CppObject* obj) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF282B0))(this, obj);
  }
  void SetValue(Il2CppObject* obj, Il2CppObject* value, ModdingAPI::Exposed::System::Object_array* index) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*, Il2CppObject*, Il2CppObject*, ModdingAPI::Exposed::System::Object_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF282F0))(this, obj, value, index);
  }
  ModdingAPI::Exposed::System::Type_array* GetOptionalCustomModifiers() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF28330))(this);
  }
  ModdingAPI::Exposed::System::Type_array* GetRequiredCustomModifiers() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type_array*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF283D0))(this);
  }
  Il2CppObject* GetConstantValue() {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF285B0))(this);
  }
  Il2CppObject* GetRawConstantValue() {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF285F0))(this);
  }
  bool Equals(Il2CppObject* obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xA57180))(this, obj);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Reflection::PropertyInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x736090))(this);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::System::NotImplementedException* CreateNIE() {
    return reinterpret_cast<ModdingAPI::Exposed::System::NotImplementedException*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xF28470))();
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo* internal_from_handle_type(intptr_t event_handle, intptr_t type_handle) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo*(__fastcall*)(intptr_t, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF28630))(event_handle, type_handle);
  }
  static inline ModdingAPI::Exposed::System::Reflection::PropertyInfo* GetPropertyFromHandle(ModdingAPI::Exposed::Mono::RuntimePropertyHandle handle, ModdingAPI::Exposed::System::RuntimeTypeHandle reflectedType) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Reflection::PropertyInfo*(__fastcall*)(ModdingAPI::Exposed::Mono::RuntimePropertyHandle, ModdingAPI::Exposed::System::RuntimeTypeHandle)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF28690))(handle, reflectedType);
  }
};
}