// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::ComponentModel {
struct __WeakHashtable_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Collections::IEqualityComparer* _comparer;
};

struct __WeakHashtable_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _19_System_Collections_IEnumerable_GetEnumerator;
  VirtualInvokeData _23_Add;
  VirtualInvokeData _24_Clear;
  VirtualInvokeData _25_Clone;
  VirtualInvokeData _26_Contains;
  VirtualInvokeData _27_ContainsKey;
  VirtualInvokeData _28_CopyTo;
  VirtualInvokeData _29_get_Item;
  VirtualInvokeData _30_set_Item;
  VirtualInvokeData _31_GetEnumerator;
  VirtualInvokeData _32_GetHash;
  VirtualInvokeData _33_get_IsReadOnly;
  VirtualInvokeData _34_get_IsFixedSize;
  VirtualInvokeData _35_get_IsSynchronized;
  VirtualInvokeData _36_KeyEquals;
  VirtualInvokeData _37_get_Keys;
  VirtualInvokeData _38_get_Values;
  VirtualInvokeData _39_Remove;
  VirtualInvokeData _40_get_SyncRoot;
  VirtualInvokeData _41_get_Count;
  VirtualInvokeData _42_GetObjectData;
  VirtualInvokeData _43_OnDeserialization;
};

struct __WeakHashtable_Il2CppClass {
  Il2CppClass_1 _1;
  __WeakHashtable_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __WeakHashtable_Il2CppVtbl vtbl;
};

class WeakHashtable {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C79FB0;
  static inline    __WeakHashtable_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __WeakHashtable_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__WeakHashtable_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __WeakHashtable_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Collections::Hashtable::bucket_array* Hashtable_buckets;
  int32_t Hashtable_count;
  int32_t Hashtable_occupancy;
  int32_t Hashtable_loadsize;
  float Hashtable_loadFactor;
  int32_t Hashtable_version;
  bool Hashtable_isWriterInProgress;
  ModdingAPI::Exposed::System::Collections::ICollection* Hashtable_keys;
  ModdingAPI::Exposed::System::Collections::ICollection* Hashtable_values;
  ModdingAPI::Exposed::System::Collections::IEqualityComparer* Hashtable__keycomparer;
  Il2CppObject* Hashtable__syncRoot;
  int64_t _lastGlobalMem;
  int32_t _lastHashCount;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::WeakHashtable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC19620))(this);
  }
  void Clear() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::WeakHashtable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC196F0))(this);
  }
  void Remove(Il2CppObject* key) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::WeakHashtable*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC19700))(this, key);
  }
  void SetWeak(Il2CppObject* key, Il2CppObject* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::WeakHashtable*, Il2CppObject*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC19710))(this, key, value);
  }
  void ScavengeKeys() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::WeakHashtable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xC198C0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::IEqualityComparer*> _comparer = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::IEqualityComparer*>(
   []() { return &GetStaticClassInstance()->pStaticFields->_comparer; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xC19D70))();
  }
};
}