// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Runtime.Serialization.StreamingContext.hpp"


namespace ModdingAPI::Exposed::System::Xml::Schema {
struct __XmlSchemaException_Il2CppStaticFields {
};

struct __XmlSchemaException_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _5_get_Message;
  VirtualInvokeData _6_get_Data;
  VirtualInvokeData _7_get_InnerException;
  VirtualInvokeData _8_get_StackTrace;
  VirtualInvokeData _9_get_Source;
  VirtualInvokeData _10_GetObjectData;
  VirtualInvokeData _11_GetType;
};

struct __XmlSchemaException_Il2CppClass {
  Il2CppClass_1 _1;
  __XmlSchemaException_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __XmlSchemaException_Il2CppVtbl vtbl;
};

class XmlSchemaException {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C3EBB8;
  static inline    __XmlSchemaException_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __XmlSchemaException_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__XmlSchemaException_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __XmlSchemaException_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  System_String* Exception__className;
  System_String* _message;
  ModdingAPI::Exposed::System::Collections::IDictionary* Exception__data;
  ModdingAPI::Exposed::System::Exception* Exception__innerException;
  System_String* Exception__helpURL;
  Il2CppObject* Exception__stackTrace;
  System_String* Exception__stackTraceString;
  System_String* Exception__remoteStackTraceString;
  int32_t Exception__remoteStackIndex;
  Il2CppObject* Exception__dynamicMethods;
  int32_t _HResult;
  System_String* Exception__source;
  ModdingAPI::Exposed::System::Runtime::Serialization::SafeSerializationManager* Exception__safeSerializationManager;
  ModdingAPI::Exposed::System::Diagnostics::StackTrace_array* captured_traces;
  ModdingAPI::Exposed::System::IntPtr_array* Exception_native_trace_ips;
  System_String* res;
  ModdingAPI::Exposed::System::String_array* args;
  System_String* sourceUri;
  int32_t lineNumber;
  int32_t linePosition;
  ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* sourceSchemaObject;
  System_String* message;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* info, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext context) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0120))(this, info, context);
  }
  void GetObjectData(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* info, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext context) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0510))(this, info, context);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0660))(this);
  }
  void ::ctor(System_String* message) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0690))(this, message);
  }
  void ::ctor(System_String* message, ModdingAPI::Exposed::System::Exception* innerException) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::Exception*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F06B0))(this, message, innerException);
  }
  void ::ctor(System_String* message, ModdingAPI::Exposed::System::Exception* innerException, int32_t lineNumber, int32_t linePosition) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::Exception*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F06D0))(this, message, innerException, lineNumber, linePosition);
  }
  void ::ctor(System_String* res, ModdingAPI::Exposed::System::String_array* args) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::String_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0860))(this, res, args);
  }
  void ::ctor(System_String* res, System_String* arg) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F08E0))(this, res, arg);
  }
  void ::ctor(System_String* res, System_String* arg, System_String* sourceUri, int32_t lineNumber, int32_t linePosition) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, System_String*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0A40))(this, res, arg, sourceUri, lineNumber, linePosition);
  }
  void ::ctor(System_String* res, System_String* sourceUri, int32_t lineNumber, int32_t linePosition) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0BB0))(this, res, sourceUri, lineNumber, linePosition);
  }
  void ::ctor(System_String* res, ModdingAPI::Exposed::System::String_array* args, System_String* sourceUri, int32_t lineNumber, int32_t linePosition) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::String_array*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0C40))(this, res, args, sourceUri, lineNumber, linePosition);
  }
  void ::ctor(System_String* res, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0CD0))(this, res, source);
  }
  void ::ctor(System_String* res, System_String* arg, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, System_String*, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0CF0))(this, res, arg, source);
  }
  void ::ctor(System_String* res, ModdingAPI::Exposed::System::String_array* args, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::String_array*, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0E10))(this, res, args, source);
  }
  void ::ctor(System_String* res, ModdingAPI::Exposed::System::String_array* args, ModdingAPI::Exposed::System::Exception* innerException, System_String* sourceUri, int32_t lineNumber, int32_t linePosition, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, ModdingAPI::Exposed::System::String_array*, ModdingAPI::Exposed::System::Exception*, System_String*, int32_t, int32_t, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0ED0))(this, res, args, innerException, sourceUri, lineNumber, linePosition, source);
  }
  System_String* get_GetRes() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x307640))(this);
  }
  ModdingAPI::Exposed::System::String_array* get_Args() {
    return reinterpret_cast<ModdingAPI::Exposed::System::String_array*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3BC530))(this);
  }
  System_String* get_SourceUri() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319850))(this);
  }
  int32_t get_LineNumber() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F1030))(this);
  }
  int32_t get_LinePosition() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F1040))(this);
  }
  ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* get_SourceSchemaObject() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x30F140))(this);
  }
  void SetSource(System_String* sourceUri, int32_t lineNumber, int32_t linePosition) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, System_String*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F1050))(this, sourceUri, lineNumber, linePosition);
  }
  void SetSchemaObject(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3F1050))(this, source);
  }
  void SetSource(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject* source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*, ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F1070))(this, source);
  }
  System_String* get_Message() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Xml::Schema::XmlSchemaException*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F10B0))(this);
  }

  // Static methods:
  static inline System_String* CreateMessage(System_String* res, ModdingAPI::Exposed::System::String_array* args) {
    return reinterpret_cast<System_String*(__fastcall*)(System_String*, ModdingAPI::Exposed::System::String_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x5F0F70))(res, args);
  }
};
}