// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Runtime.Serialization.StreamingContext.hpp"


namespace ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary {
struct __ObjectWriter_Il2CppStaticFields {
};

struct __ObjectWriter_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __ObjectWriter_Il2CppClass {
  Il2CppClass_1 _1;
  __ObjectWriter_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ObjectWriter_Il2CppVtbl vtbl;
};

class ObjectWriter {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C57068;
  static inline    __ObjectWriter_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __ObjectWriter_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ObjectWriter_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ObjectWriter_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Collections::Queue* m_objectQueue;
  ModdingAPI::Exposed::System::Runtime::Serialization::ObjectIDGenerator* m_idGenerator;
  int32_t m_currentId;
  ModdingAPI::Exposed::System::Runtime::Serialization::ISurrogateSelector* m_surrogates;
  ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext m_context;
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::__BinaryWriter* serWriter;
  ModdingAPI::Exposed::System::Runtime::Serialization::SerializationObjectManager* m_objectManager;
  int64_t topId;
  System_String* topName;
  ModdingAPI::Exposed::System::Runtime::Remoting::Messaging::Header_array* headers;
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::InternalFE* formatterEnums;
  ModdingAPI::Exposed::System::Runtime::Serialization::SerializationBinder* m_binder;
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::SerObjectInfoInit* serObjectInfoInit;
  ModdingAPI::Exposed::System::Runtime::Serialization::IFormatterConverter* m_formatterConverter;
  ModdingAPI::Exposed::System::Object_array* crossAppDomainArray;
  Il2CppObject* previousObj;
  int64_t previousId;
  ModdingAPI::Exposed::System::Type* previousType;
  int32_t previousCode;
  ModdingAPI::Exposed::System::Collections::Hashtable* assemblyToIdTable;
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::SerStack* niPool;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Runtime::Serialization::ISurrogateSelector* selector, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext context, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::InternalFE* formatterEnums, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationBinder* binder) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::ISurrogateSelector*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::InternalFE*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationBinder*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x974600))(this, selector, context, formatterEnums, binder);
  }
  void Serialize(Il2CppObject* graph, ModdingAPI::Exposed::System::Runtime::Remoting::Messaging::Header_array* inHeaders, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::__BinaryWriter* serWriter, bool fCheck) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, Il2CppObject*, ModdingAPI::Exposed::System::Runtime::Remoting::Messaging::Header_array*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::__BinaryWriter*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x974870))(this, graph, inHeaders, serWriter, fCheck);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::SerializationObjectManager* get_ObjectManager() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::SerializationObjectManager*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x319980))(this);
  }
  void Write(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x975030))(this, objectInfo, memberNameInfo, typeNameInfo);
  }
  void Write(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, ModdingAPI::Exposed::System::String_array* memberNames, ModdingAPI::Exposed::System::Type_array* memberTypes, ModdingAPI::Exposed::System::Object_array* memberData, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo_array* memberObjectInfos) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::String_array*, ModdingAPI::Exposed::System::Type_array*, ModdingAPI::Exposed::System::Object_array*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x975670))(this, objectInfo, memberNameInfo, typeNameInfo, memberNames, memberTypes, memberData, memberObjectInfos);
  }
  void WriteMemberSetup(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, System_String* memberName, ModdingAPI::Exposed::System::Type* memberType, Il2CppObject* memberData, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* memberObjectInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, System_String*, ModdingAPI::Exposed::System::Type*, Il2CppObject*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x975AF0))(this, objectInfo, memberNameInfo, typeNameInfo, memberName, memberType, memberData, memberObjectInfo);
  }
  void WriteMembers(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberTypeNameInfo, Il2CppObject* memberData, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* memberObjectInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, Il2CppObject*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x975C60))(this, memberNameInfo, memberTypeNameInfo, memberData, objectInfo, typeNameInfo, memberObjectInfo);
  }
  void WriteArray(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* memberObjectInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x976130))(this, objectInfo, memberNameInfo, memberObjectInfo);
  }
  void WriteArrayMember(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* arrayElemTypeNameInfo, Il2CppObject* data) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x976CC0))(this, objectInfo, arrayElemTypeNameInfo, data);
  }
  void WriteRectangle(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, int32_t rank, ModdingAPI::Exposed::System::Int32_array* maxA, ModdingAPI::Exposed::System::Array* array, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* arrayElemNameTypeInfo, ModdingAPI::Exposed::System::Int32_array* lowerBoundA) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, int32_t, ModdingAPI::Exposed::System::Int32_array*, ModdingAPI::Exposed::System::Array*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Int32_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9770D0))(this, objectInfo, rank, maxA, array, arrayElemNameTypeInfo, lowerBoundA);
  }
  Il2CppObject* GetNext(int64_t objID) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9773C0))(this, objID);
  }
  int64_t InternalGetId(Il2CppObject* obj, bool assignUniqueIdToValueType, ModdingAPI::Exposed::System::Type* type, bool isNew) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, Il2CppObject*, bool, ModdingAPI::Exposed::System::Type*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977590))(this, obj, assignUniqueIdToValueType, type, isNew);
  }
  int64_t Schedule(Il2CppObject* obj, bool assignUniqueIdToValueType, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, Il2CppObject*, bool, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977680))(this, obj, assignUniqueIdToValueType, type);
  }
  int64_t Schedule(Il2CppObject* obj, bool assignUniqueIdToValueType, ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, Il2CppObject*, bool, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977700))(this, obj, assignUniqueIdToValueType, type, objectInfo);
  }
  bool WriteKnownValueClass(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, Il2CppObject* data) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9777B0))(this, memberNameInfo, typeNameInfo, data);
  }
  void WriteObjectRef(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* nameInfo, int64_t objectId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977920))(this, nameInfo, objectId);
  }
  void WriteString(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, Il2CppObject* stringObject) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977940))(this, memberNameInfo, typeNameInfo, stringObject);
  }
  bool CheckForNull(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* memberNameInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* typeNameInfo, Il2CppObject* data) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977B00))(this, objectInfo, memberNameInfo, typeNameInfo, data);
  }
  void WriteSerializedStreamHeader(int64_t topId, int64_t headerId) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, int64_t, int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977C00))(this, topId, headerId);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* TypeToNameInfo(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, int32_t code, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* nameInfo) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, int32_t, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977C30))(this, type, objectInfo, code, nameInfo);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* TypeToNameInfo(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977CF0))(this, type);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* TypeToNameInfo(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977D40))(this, objectInfo);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* TypeToNameInfo(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* nameInfo) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977DF0))(this, objectInfo, nameInfo);
  }
  void TypeToNameInfo(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* nameInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977E60))(this, type, nameInfo);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* MemberToNameInfo(System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977EF0))(this, name);
  }
  int32_t ToCode(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x977F20))(this, type);
  }
  int64_t GetAssemblyId(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo* objectInfo) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::WriteObjectInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x978000))(this, objectInfo);
  }
  ModdingAPI::Exposed::System::Type* GetType(Il2CppObject* obj) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9783C0))(this, obj);
  }
  ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* GetNameInfo() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9783E0))(this);
  }
  bool CheckTypeFormat(int32_t test, int32_t want) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9785B0))(this, test, want);
  }
  void PutNameInfo(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo* nameInfo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::ObjectWriter*, ModdingAPI::Exposed::System::Runtime::Serialization::Formatters::Binary::NameInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x9785C0))(this, nameInfo);
  }
};
}