// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Decimal.hpp"
#include "ModdingAPI.Exposed.System.DateTime.hpp"

namespace ModdingAPI::Exposed::System {
struct __Double_Il2CppObject {
  double m_value;
};
struct __Double_Il2CppStaticFields {
  double NegativeZero;
};

struct __Double_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_CompareTo;
  VirtualInvokeData _5_ToString;
  VirtualInvokeData _6_GetTypeCode;
  VirtualInvokeData _7_System_IConvertible_ToBoolean;
  VirtualInvokeData _8_System_IConvertible_ToChar;
  VirtualInvokeData _9_System_IConvertible_ToSByte;
  VirtualInvokeData _10_System_IConvertible_ToByte;
  VirtualInvokeData _11_System_IConvertible_ToInt16;
  VirtualInvokeData _12_System_IConvertible_ToUInt16;
  VirtualInvokeData _13_System_IConvertible_ToInt32;
  VirtualInvokeData _14_System_IConvertible_ToUInt32;
  VirtualInvokeData _15_System_IConvertible_ToInt64;
  VirtualInvokeData _16_System_IConvertible_ToUInt64;
  VirtualInvokeData _17_System_IConvertible_ToSingle;
  VirtualInvokeData _18_System_IConvertible_ToDouble;
  VirtualInvokeData _19_System_IConvertible_ToDecimal;
  VirtualInvokeData _20_System_IConvertible_ToDateTime;
  VirtualInvokeData _21_ToString;
  VirtualInvokeData _22_System_IConvertible_ToType;
  VirtualInvokeData _23_CompareTo;
  VirtualInvokeData _24_Equals;
};

struct __Double_Il2CppClass {
  Il2CppClass_1 _1;
  __Double_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Double_Il2CppVtbl vtbl;
};

class Double {
  static constexpr uint64_t _rvaObjectInstance     = 0x3C41ED0;
  static inline    Double* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t _rvaClassInstance     = 0x3C261B0;
  static inline    __Double_Il2CppClass* _pStaticClassInstance = nullptr;

public:
  // Singleton object getter:
  static inline Double* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (Double**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

  // Static class getter:
  static inline __Double_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__Double_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Member fields:
  double m_value;

  // Member methods:
  int32_t CompareTo(Il2CppObject* value) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x154C0))(this, value);
  }
  int32_t CompareTo(double value) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x154D0))(this, value);
  }
  bool Equals(Il2CppObject* obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Double*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x154E0))(this, obj);
  }
  bool Equals(double obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Double*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x154F0))(this, obj);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15500))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Double*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15510))(this);
  }
  System_String* ToString(System_String* format) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Double*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15540))(this, format);
  }
  System_String* ToString(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15580))(this, provider);
  }
  System_String* ToString(System_String* format, ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Double*, System_String*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x155C0))(this, format, provider);
  }
  int32_t GetTypeCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15600))(this);
  }
  bool System::IConvertible::ToBoolean(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15610))(this, provider);
  }
  wchar_t System::IConvertible::ToChar(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<wchar_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x156D0))(this, provider);
  }
  char System::IConvertible::ToSByte(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<char(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x156E0))(this, provider);
  }
  uint8_t System::IConvertible::ToByte(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<uint8_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15790))(this, provider);
  }
  int16_t System::IConvertible::ToInt16(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<int16_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15840))(this, provider);
  }
  uint16_t System::IConvertible::ToUInt16(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<uint16_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158F0))(this, provider);
  }
  int32_t System::IConvertible::ToInt32(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x159A0))(this, provider);
  }
  uint32_t System::IConvertible::ToUInt32(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<uint32_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15A50))(this, provider);
  }
  int64_t System::IConvertible::ToInt64(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15B00))(this, provider);
  }
  uint64_t System::IConvertible::ToUInt64(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<uint64_t(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15BB0))(this, provider);
  }
  float System::IConvertible::ToSingle(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15C60))(this, provider);
  }
  double System::IConvertible::ToDouble(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<double(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15D10))(this, provider);
  }
  ModdingAPI::Exposed::System::Decimal System::IConvertible::ToDecimal(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Decimal(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15D20))(this, provider);
  }
  ModdingAPI::Exposed::System::DateTime System::IConvertible::ToDateTime(ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15E80))(this, provider);
  }
  Il2CppObject* System::IConvertible::ToType(ModdingAPI::Exposed::System::Type* type, ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<Il2CppObject*(__fastcall*)(ModdingAPI::Exposed::System::Double*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15E90))(this, type, provider);
  }

  // Static methods:
  static inline bool IsInfinity(double d) {
    return reinterpret_cast<bool(__fastcall*)(double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6510D0))(d);
  }
  static inline bool IsPositiveInfinity(double d) {
    return reinterpret_cast<bool(__fastcall*)(double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651100))(d);
  }
  static inline bool IsNegativeInfinity(double d) {
    return reinterpret_cast<bool(__fastcall*)(double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651120))(d);
  }
  static inline bool IsNegative(double d) {
    return reinterpret_cast<bool(__fastcall*)(double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651140))(d);
  }
  static inline bool IsNaN(double d) {
    return reinterpret_cast<bool(__fastcall*)(double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651160))(d);
  }
  static inline double Parse(System_String* s) {
    return reinterpret_cast<double(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651750))(s);
  }
  static inline double Parse(System_String* s, ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<double(__fastcall*)(System_String*, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651810))(s, provider);
  }
  static inline double Parse(System_String* s, int32_t style, ModdingAPI::Exposed::System::IFormatProvider* provider) {
    return reinterpret_cast<double(__fastcall*)(System_String*, int32_t, ModdingAPI::Exposed::System::IFormatProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6518D0))(s, style, provider);
  }
  static inline double Parse(System_String* s, int32_t style, ModdingAPI::Exposed::System::Globalization::NumberFormatInfo* info) {
    return reinterpret_cast<double(__fastcall*)(System_String*, int32_t, ModdingAPI::Exposed::System::Globalization::NumberFormatInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6519A0))(s, style, info);
  }
  static inline bool TryParse(System_String* s, double result) {
    return reinterpret_cast<bool(__fastcall*)(System_String*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6519B0))(s, result);
  }
  static inline bool TryParse(System_String* s, int32_t style, ModdingAPI::Exposed::System::IFormatProvider* provider, double result) {
    return reinterpret_cast<bool(__fastcall*)(System_String*, int32_t, ModdingAPI::Exposed::System::IFormatProvider*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651A80))(s, style, provider, result);
  }
  static inline bool TryParse(System_String* s, int32_t style, ModdingAPI::Exposed::System::Globalization::NumberFormatInfo* info, double result) {
    return reinterpret_cast<bool(__fastcall*)(System_String*, int32_t, ModdingAPI::Exposed::System::Globalization::NumberFormatInfo*, double)>(Helpers::Memory::GetInstance().MakeAbsolute(0x651B70))(s, style, info, result);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x651E00))();
  }

};
}