// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Linq::Expressions {
struct __InvocationExpression1_Il2CppStaticFields {
};

struct __InvocationExpression1_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_get_NodeType;
  VirtualInvokeData _5_get_Type;
  VirtualInvokeData _6_get_CanReduce;
  VirtualInvokeData _7_Reduce;
  VirtualInvokeData _8_VisitChildren;
  VirtualInvokeData _9_Accept;
  VirtualInvokeData _12_GetArgument;
  VirtualInvokeData _13_get_ArgumentCount;
  VirtualInvokeData _14_Rewrite;
};

struct __InvocationExpression1_Il2CppClass {
  Il2CppClass_1 _1;
  __InvocationExpression1_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __InvocationExpression1_Il2CppVtbl vtbl;
};

class InvocationExpression1 {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C26D38;
  static inline    __InvocationExpression1_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __InvocationExpression1_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__InvocationExpression1_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __InvocationExpression1_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::Type* InvocationExpression__Type_k__BackingField;
  ModdingAPI::Exposed::System::Linq::Expressions::Expression* InvocationExpression__Expression_k__BackingField;
  Il2CppObject* _arg0;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Linq::Expressions::Expression* lambda, ModdingAPI::Exposed::System::Type* returnType, ModdingAPI::Exposed::System::Linq::Expressions::Expression* arg0) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression1*, ModdingAPI::Exposed::System::Linq::Expressions::Expression*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::Linq::Expressions::Expression*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11FE6A0))(this, lambda, returnType, arg0);
  }
  ModdingAPI::Exposed::System::Linq::Expressions::Expression* GetArgument(int32_t index) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Linq::Expressions::Expression*(__fastcall*)(ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression1*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11FE760))(this, index);
  }
  int32_t get_ArgumentCount() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression1*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4114C0))(this);
  }
  ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression* Rewrite(ModdingAPI::Exposed::System::Linq::Expressions::Expression* lambda, ModdingAPI::Exposed::System::Linq::Expressions::Expression_array* arguments) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression*(__fastcall*)(ModdingAPI::Exposed::System::Linq::Expressions::InvocationExpression1*, ModdingAPI::Exposed::System::Linq::Expressions::Expression*, ModdingAPI::Exposed::System::Linq::Expressions::Expression_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x11FE920))(this, lambda, arguments);
  }
};
}