// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::Text {
struct __InternalEncoderBestFitFallbackBuffer_Il2CppStaticFields {
  Il2CppObject* s_InternalSyncObject;
};

struct __InternalEncoderBestFitFallbackBuffer_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Fallback;
  VirtualInvokeData _5_Fallback;
  VirtualInvokeData _6_GetNextChar;
  VirtualInvokeData _7_MovePrevious;
  VirtualInvokeData _8_get_Remaining;
  VirtualInvokeData _9_Reset;
  VirtualInvokeData _10_InternalFallback;
};

struct __InternalEncoderBestFitFallbackBuffer_Il2CppClass {
  Il2CppClass_1 _1;
  __InternalEncoderBestFitFallbackBuffer_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __InternalEncoderBestFitFallbackBuffer_Il2CppVtbl vtbl;
};

class InternalEncoderBestFitFallbackBuffer {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C340A8;
  static inline    __InternalEncoderBestFitFallbackBuffer_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __InternalEncoderBestFitFallbackBuffer_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__InternalEncoderBestFitFallbackBuffer_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __InternalEncoderBestFitFallbackBuffer_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  wchar_t* charStart;
  wchar_t* charEnd;
  ModdingAPI::Exposed::System::Text::EncoderNLS* encoder;
  bool setEncoder;
  bool bUsedEncoder;
  bool bFallingBack;
  int32_t iRecursionCount;
  wchar_t cBestFit;
  ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallback* oFallback;
  int32_t iCount;
  int32_t iSize;

  // Member methods:
  void ::ctor(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallback* fallback) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*, ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallback*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0840))(this, fallback);
  }
  bool Fallback(wchar_t charUnknown, int32_t index) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*, wchar_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0AE0))(this, charUnknown, index);
  }
  bool Fallback(wchar_t charUnknownHigh, wchar_t charUnknownLow, int32_t index) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*, wchar_t, wchar_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0B20))(this, charUnknownHigh, charUnknownLow, index);
  }
  wchar_t GetNextChar() {
    return reinterpret_cast<wchar_t(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0DE0))(this);
  }
  bool MovePrevious() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0E10))(this);
  }
  int32_t get_Remaining() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0E30))(this);
  }
  void Reset() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0E40))(this);
  }
  wchar_t TryBestFit(wchar_t cUnknown) {
    return reinterpret_cast<wchar_t(__fastcall*)(ModdingAPI::Exposed::System::Text::InternalEncoderBestFitFallbackBuffer*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB0E60))(this, cUnknown);
  }

  // Static fields:
  static inline __CppStaticProperty<Il2CppObject*> s_InternalSyncObject = __CppStaticProperty<Il2CppObject*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_InternalSyncObject; }
  );

  // Static methods:
  static inline Il2CppObject* get_InternalSyncObject() {
    return reinterpret_cast<Il2CppObject*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xEB06D0))();
  }
};
}