// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.Runtime.Serialization.StreamingContext.hpp"


namespace ModdingAPI::Exposed::System::Net {
struct __WebHeaderCollection_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Net::HeaderInfoTable* HInfo;
  ModdingAPI::Exposed::System::String_array* s_CommonHeaderNames;
  ModdingAPI::Exposed::System::SByte_array* s_CommonHeaderHints;
  ModdingAPI::Exposed::System::Char_array* HttpTrimCharacters;
  ModdingAPI::Exposed::System::Net::WebHeaderCollection::RfcChar_array* RfcCharMap;
};

struct __WebHeaderCollection_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_System_Collections_ICollection_CopyTo;
  VirtualInvokeData _6_System_Collections_ICollection_get_SyncRoot;
  VirtualInvokeData _7_System_Collections_ICollection_get_IsSynchronized;
  VirtualInvokeData _9_System_Runtime_Serialization_ISerializable_GetObjectData;
  VirtualInvokeData _11_GetObjectData;
  VirtualInvokeData _12_OnDeserialization;
  VirtualInvokeData _13_GetEnumerator;
  VirtualInvokeData _14_get_Count;
  VirtualInvokeData _15_Add;
  VirtualInvokeData _16_Get;
  VirtualInvokeData _17_GetValues;
  VirtualInvokeData _18_Set;
  VirtualInvokeData _19_Remove;
  VirtualInvokeData _20_Get;
  VirtualInvokeData _21_GetKey;
};

struct __WebHeaderCollection_Il2CppClass {
  Il2CppClass_1 _1;
  __WebHeaderCollection_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __WebHeaderCollection_Il2CppVtbl vtbl;
};

class WebHeaderCollection {
  static constexpr uint64_t         _rvaObjectInstance     = 0x3C3F120;
  static inline    WebHeaderCollection* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t                     _rvaClassInstance     = 0x3C3E6A8;
  static inline    __WebHeaderCollection_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Singleton object getter:
  static inline WebHeaderCollection* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (WebHeaderCollection**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

// Static class getter:
  static inline __WebHeaderCollection_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__WebHeaderCollection_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __WebHeaderCollection_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  bool NameObjectCollectionBase__readOnly;
  ModdingAPI::Exposed::System::Collections::ArrayList* NameObjectCollectionBase__entriesArray;
  ModdingAPI::Exposed::System::Collections::IEqualityComparer* NameObjectCollectionBase__keyComparer;
  ModdingAPI::Exposed::System::Collections::Hashtable* NameObjectCollectionBase__entriesTable;
  ModdingAPI::Exposed::System::Collections::Specialized::NameObjectCollectionBase::NameObjectEntry* NameObjectCollectionBase__nullKeyEntry;
  ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* NameObjectCollectionBase__serializationInfo;
  int32_t NameObjectCollectionBase__version;
  Il2CppObject* NameObjectCollectionBase__syncRoot;
  ModdingAPI::Exposed::System::String_array* NameValueCollection__all;
  ModdingAPI::Exposed::System::String_array* NameValueCollection__allKeys;
  ModdingAPI::Exposed::System::String_array* m_CommonHeaders;
  int32_t m_NumCommonHeaders;
  ModdingAPI::Exposed::System::Collections::Specialized::NameValueCollection* m_InnerCollection;
  uint16_t m_Type;

  // Member methods:
  void NormalizeCommonHeaders() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05520))(this);
  }
  ModdingAPI::Exposed::System::Collections::Specialized::NameValueCollection* get_InnerCollection() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Specialized::NameValueCollection*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB056F0))(this);
  }
  bool get_AllowHttpRequestHeader() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB059A0))(this);
  }
  void Remove(int32_t header) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB059D0))(this, header);
  }
  void AddInternal(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05BC0))(this, name, value);
  }
  void ChangeInternal(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05C30))(this, name, value);
  }
  void RemoveInternal(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05CA0))(this, name);
  }
  void ThrowOnRestrictedHeader(System_String* headerName) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06230))(this, headerName);
  }
  void Add(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06490))(this, name, value);
  }
  void Add(System_String* header) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06670))(this, header);
  }
  void Set(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06940))(this, name, value);
  }
  void SetInternal(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06B80))(this, name, value);
  }
  void Remove(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06DB0))(this, name);
  }
  ModdingAPI::Exposed::System::String_array* GetValues(System_String* header) {
    return reinterpret_cast<ModdingAPI::Exposed::System::String_array*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB06F00))(this, header);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07230))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07640))(this);
  }
  void ::ctor(uint16_t type) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, uint16_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB076F0))(this, type);
  }
  void ::ctor(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07810))(this, serializationInfo, streamingContext);
  }
  void OnDeserialization(Il2CppObject* sender) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this, sender);
  }
  void GetObjectData(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07AB0))(this, serializationInfo, streamingContext);
  }
  void System::Runtime::Serialization::ISerializable::GetObjectData(ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo* serializationInfo, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext streamingContext) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, ModdingAPI::Exposed::System::Runtime::Serialization::SerializationInfo*, ModdingAPI::Exposed::System::Runtime::Serialization::StreamingContext)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07C70))(this, serializationInfo, streamingContext);
  }
  System_String* Get(System_String* name) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB07CA0))(this, name);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* GetEnumerator() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB080E0))(this);
  }
  int32_t get_Count() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB08250))(this);
  }
  System_String* Get(int32_t index) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB08290))(this, index);
  }
  System_String* GetKey(int32_t index) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Net::WebHeaderCollection*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB082E0))(this, index);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Net::HeaderInfoTable*> HInfo = __CppStaticProperty<ModdingAPI::Exposed::System::Net::HeaderInfoTable*>(
   []() { return &GetStaticClassInstance()->pStaticFields->HInfo; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::String_array*> s_CommonHeaderNames = __CppStaticProperty<ModdingAPI::Exposed::System::String_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CommonHeaderNames; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::SByte_array*> s_CommonHeaderHints = __CppStaticProperty<ModdingAPI::Exposed::System::SByte_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CommonHeaderHints; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Char_array*> HttpTrimCharacters = __CppStaticProperty<ModdingAPI::Exposed::System::Char_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->HttpTrimCharacters; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Net::WebHeaderCollection::RfcChar_array*> RfcCharMap = __CppStaticProperty<ModdingAPI::Exposed::System::Net::WebHeaderCollection::RfcChar_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->RfcCharMap; }
  );

  // Static methods:
  static inline bool AllowMultiValues(System_String* name) {
    return reinterpret_cast<bool(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05890))(name);
  }
  static inline System_String* CheckBadChars(System_String* name, bool isHeaderValue) {
    return reinterpret_cast<System_String*(__fastcall*)(System_String*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB05CF0))(name, isHeaderValue);
  }
  static inline bool ContainsNonAsciiChars(System_String* token) {
    return reinterpret_cast<bool(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB061C0))(token);
  }
  static inline System_String* GetAsString(ModdingAPI::Exposed::System::Collections::Specialized::NameValueCollection* cc, bool winInetCompat, bool forTrace) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Collections::Specialized::NameValueCollection*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xB072D0))(cc, winInetCompat, forTrace);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xB08330))();
  }
};
}