// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::System::ComponentModel {
struct __ExtenderProvidedPropertyAttribute_Il2CppStaticFields {
};

struct __ExtenderProvidedPropertyAttribute_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_get_TypeId;
  VirtualInvokeData _5_Match;
  VirtualInvokeData _6_IsDefaultAttribute;
};

struct __ExtenderProvidedPropertyAttribute_Il2CppClass {
  Il2CppClass_1 _1;
  __ExtenderProvidedPropertyAttribute_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __ExtenderProvidedPropertyAttribute_Il2CppVtbl vtbl;
};

class ExtenderProvidedPropertyAttribute {
  static constexpr uint64_t         _rvaObjectInstance     = 0x3C3D190;
  static inline    ExtenderProvidedPropertyAttribute* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t                     _rvaClassInstance     = 0x3C3C770;
  static inline    __ExtenderProvidedPropertyAttribute_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Singleton object getter:
  static inline ExtenderProvidedPropertyAttribute* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (ExtenderProvidedPropertyAttribute**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

// Static class getter:
  static inline __ExtenderProvidedPropertyAttribute_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__ExtenderProvidedPropertyAttribute_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __ExtenderProvidedPropertyAttribute_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::System::ComponentModel::PropertyDescriptor* extenderProperty;
  ModdingAPI::Exposed::System::ComponentModel::IExtenderProvider* provider;
  ModdingAPI::Exposed::System::Type* receiverType;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  ModdingAPI::Exposed::System::ComponentModel::PropertyDescriptor* get_ExtenderProperty() {
    return reinterpret_cast<ModdingAPI::Exposed::System::ComponentModel::PropertyDescriptor*(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x311320))(this);
  }
  ModdingAPI::Exposed::System::ComponentModel::IExtenderProvider* get_Provider() {
    return reinterpret_cast<ModdingAPI::Exposed::System::ComponentModel::IExtenderProvider*(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x335360))(this);
  }
  ModdingAPI::Exposed::System::Type* get_ReceiverType() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Type*(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3110A0))(this);
  }
  bool Equals(Il2CppObject* obj) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEBC4D0))(this, obj);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xD50650))(this);
  }
  bool IsDefaultAttribute() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEBC620))(this);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute* Create(ModdingAPI::Exposed::System::ComponentModel::PropertyDescriptor* extenderProperty, ModdingAPI::Exposed::System::Type* receiverType, ModdingAPI::Exposed::System::ComponentModel::IExtenderProvider* provider) {
    return reinterpret_cast<ModdingAPI::Exposed::System::ComponentModel::ExtenderProvidedPropertyAttribute*(__fastcall*)(ModdingAPI::Exposed::System::ComponentModel::PropertyDescriptor*, ModdingAPI::Exposed::System::Type*, ModdingAPI::Exposed::System::ComponentModel::IExtenderProvider*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xEBC360))(extenderProperty, receiverType, provider);
  }
};
}