// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"


namespace ModdingAPI::Exposed::TMPro {
struct __TMP_TextInfo_Il2CppStaticFields {
  ModdingAPI::Exposed::UnityEngine::Vector2 k_InfinityVectorPositive;
  ModdingAPI::Exposed::UnityEngine::Vector2 k_InfinityVectorNegative;
};

struct __TMP_TextInfo_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __TMP_TextInfo_Il2CppClass {
  Il2CppClass_1 _1;
  __TMP_TextInfo_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __TMP_TextInfo_Il2CppVtbl vtbl;
};

class TMP_TextInfo {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C580A0;
  static inline    __TMP_TextInfo_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __TMP_TextInfo_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__TMP_TextInfo_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __TMP_TextInfo_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::TMPro::TMP_Text* textComponent;
  int32_t characterCount;
  int32_t spriteCount;
  int32_t spaceCount;
  int32_t wordCount;
  int32_t linkCount;
  int32_t lineCount;
  int32_t pageCount;
  int32_t materialCount;
  ModdingAPI::Exposed::TMPro::TMP_CharacterInfo_array* characterInfo;
  ModdingAPI::Exposed::TMPro::TMP_WordInfo_array* wordInfo;
  ModdingAPI::Exposed::TMPro::TMP_LinkInfo_array* linkInfo;
  ModdingAPI::Exposed::TMPro::TMP_LineInfo_array* lineInfo;
  ModdingAPI::Exposed::TMPro::TMP_PageInfo_array* pageInfo;
  ModdingAPI::Exposed::TMPro::TMP_MeshInfo_array* meshInfo;
  ModdingAPI::Exposed::TMPro::TMP_MeshInfo_array* m_CachedMeshInfo;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6BE0))(this);
  }
  void ::ctor(ModdingAPI::Exposed::TMPro::TMP_Text* textComponent) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*, ModdingAPI::Exposed::TMPro::TMP_Text*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6CD0))(this, textComponent);
  }
  void Clear() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6E30))(this);
  }
  void ClearMeshInfo(bool updateMesh) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6EC0))(this, updateMesh);
  }
  void ClearAllMeshInfo() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6F60))(this);
  }
  void ResetVertexLayout(bool isVolumetric) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA6FF0))(this, isVolumetric);
  }
  void ClearUnusedVertices(ModdingAPI::Exposed::TMPro::MaterialReference_array* materials) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*, ModdingAPI::Exposed::TMPro::MaterialReference_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA7080))(this, materials);
  }
  void ClearLineInfo() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA7120))(this);
  }
  ModdingAPI::Exposed::TMPro::TMP_MeshInfo_array* CopyMeshInfoVertexData() {
    return reinterpret_cast<ModdingAPI::Exposed::TMPro::TMP_MeshInfo_array*(__fastcall*)(ModdingAPI::Exposed::TMPro::TMP_TextInfo*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA7450))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Vector2> k_InfinityVectorPositive = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Vector2>(
   []() { return &GetStaticClassInstance()->pStaticFields->k_InfinityVectorPositive; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Vector2> k_InfinityVectorNegative = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Vector2>(
   []() { return &GetStaticClassInstance()->pStaticFields->k_InfinityVectorNegative; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xAA7990))();
  }
};
}