// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __TweenVolume_Il2CppStaticFields {
};

struct __TweenVolume_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Start;
  VirtualInvokeData _5_OnUpdate;
  VirtualInvokeData _6_SetStartToCurrentValue;
  VirtualInvokeData _7_SetEndToCurrentValue;
};

struct __TweenVolume_Il2CppClass {
  Il2CppClass_1 _1;
  __TweenVolume_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __TweenVolume_Il2CppVtbl vtbl;
};

class TweenVolume {
public:
  // Il2Cpp fields:
  __TweenVolume_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  int32_t method;
  int32_t style;
  ModdingAPI::Exposed::UnityEngine::AnimationCurve* animationCurve;
  bool ignoreTimeScale;
  float delay;
  float duration;
  bool steeperCurves;
  int32_t tweenGroup;
  bool doNotResetOnDisable;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* onFinished;
  ModdingAPI::Exposed::UnityEngine::GameObject* eventReceiver;
  System_String* callWhenFinished;
  bool UITweener_mStarted;
  float UITweener_mStartTime;
  float UITweener_mDuration;
  float UITweener_mAmountPerDelta;
  float UITweener_mFactor;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* UITweener_mTemp;
  float from;
  float to;
  ModdingAPI::Exposed::UnityEngine::AudioSource* mSource;

  // Member methods:
  ModdingAPI::Exposed::UnityEngine::AudioSource* get_audioSource() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AudioSource*(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5B90))(this);
  }
  float get_volume() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5D20))(this);
  }
  void set_volume(float value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5D30))(this, value);
  }
  float get_value() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5D40))(this);
  }
  void set_value(float value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5E60))(this, value);
  }
  void OnUpdate(float factor, bool isFinished) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*, float, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B5F50))(this, factor, isFinished);
  }
  void SetStartToCurrentValue() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B6110))(this);
  }
  void SetEndToCurrentValue() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B6130))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::TweenVolume*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B1180))(this);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::TweenVolume* Begin(ModdingAPI::Exposed::UnityEngine::GameObject* go, float duration, float targetVolume) {
    return reinterpret_cast<ModdingAPI::Exposed::TweenVolume*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::GameObject*, float, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20B6040))(go, duration, targetVolume);
  }
};
}