// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"


namespace ModdingAPI::Exposed {
struct __UITable_Il2CppStaticFields {
};

struct __UITable_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Sort;
  VirtualInvokeData _5_Start;
  VirtualInvokeData _6_Init;
  VirtualInvokeData _7_LateUpdate;
  VirtualInvokeData _8_Reposition;
};

struct __UITable_Il2CppClass {
  Il2CppClass_1 _1;
  __UITable_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __UITable_Il2CppVtbl vtbl;
};

class UITable {
public:
  // Il2Cpp fields:
  __UITable_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  int32_t columns;
  int32_t direction;
  int32_t sorting;
  int32_t pivot;
  int32_t cellAlignment;
  bool hideInactive;
  bool keepWithinPanel;
  ModdingAPI::Exposed::UnityEngine::Vector2 padding;
  ModdingAPI::Exposed::UITable::OnReposition* onReposition;
  ModdingAPI::Exposed::System::Comparison_T_* onCustomSort;
  ModdingAPI::Exposed::UIPanel* mPanel;
  bool mInitDone;
  bool mReposition;

  // Member methods:
  void set_repositionNow(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2040F50))(this, value);
  }
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* GetChildList() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::List_T_*(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2040FB0))(this);
  }
  void Sort(ModdingAPI::Exposed::System::Collections::Generic::List_T_* list) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2041620))(this, list);
  }
  void Start() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20417B0))(this);
  }
  void Init() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2041830))(this);
  }
  void LateUpdate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2041930))(this);
  }
  void OnValidate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20419A0))(this);
  }
  void RepositionVariableSize(ModdingAPI::Exposed::System::Collections::Generic::List_T_* children) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*, ModdingAPI::Exposed::System::Collections::Generic::List_T_*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2041AA0))(this, children);
  }
  void Reposition() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2042780))(this);
  }
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UITable*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x20429F0))(this);
  }
};
}