// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::UnityEngine {
struct __RectOffset_Il2CppStaticFields {
};

struct __RectOffset_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __RectOffset_Il2CppClass {
  Il2CppClass_1 _1;
  __RectOffset_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __RectOffset_Il2CppVtbl vtbl;
};

class RectOffset {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C80A68;
  static inline    __RectOffset_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __RectOffset_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__RectOffset_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __RectOffset_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t m_Ptr;
  Il2CppObject* m_SourceStyle;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109D8B0))(this);
  }
  void ::ctor(Il2CppObject* sourceStyle, intptr_t source) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, Il2CppObject*, intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xF6F540))(this, sourceStyle, source);
  }
  void ::ctor(int32_t left, int32_t right, int32_t top, int32_t bottom) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109D910))(this, left, right, top, bottom);
  }
  int32_t get_left() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DB50))(this);
  }
  void set_left(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DBA0))(this, value);
  }
  int32_t get_right() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DC00))(this);
  }
  void set_right(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DC50))(this, value);
  }
  int32_t get_top() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DCB0))(this);
  }
  void set_top(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DD00))(this, value);
  }
  int32_t get_bottom() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DD60))(this);
  }
  void set_bottom(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DDB0))(this, value);
  }
  int32_t get_horizontal() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DE10))(this);
  }
  int32_t get_vertical() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DE60))(this);
  }
  void Finalize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DEB0))(this);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DFD0))(this);
  }
  void Destroy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::RectOffset*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109E330))(this);
  }

  // Static methods:
  static inline intptr_t InternalCreate() {
    return reinterpret_cast<intptr_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DAB0))();
  }
  static inline void InternalDestroy(intptr_t ptr) {
    reinterpret_cast<void(__fastcall*)(intptr_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x109DB00))(ptr);
  }
};
}