// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI::Exposed::UnityEngine::Vector3.hpp"
#include "ModdingAPI::Exposed::UnityEngine::Quaternion.hpp"


namespace ModdingAPI::Exposed::UnityEngine {
struct __Object_Il2CppStaticFields {
  int32_t OffsetOfInstanceIDInCPlusPlusObject;
};

struct __Object_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __Object_Il2CppClass {
  Il2CppClass_1 _1;
  __Object_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Object_Il2CppVtbl vtbl;
};

class Object {
  static constexpr uint64_t         _rvaObjectInstance     = 0x3C7D210;
  static inline    Object* _pStaticObjectInstance = nullptr;

  static constexpr uint64_t                     _rvaClassInstance     = 0x3C784D8;
  static inline    __Object_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Singleton object getter:
  static inline Object* GetSingletonInstance() {
    while (!_pStaticObjectInstance) {
      Sleep(100);
      auto* ppObjectInstance = (Object**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaObjectInstance);
      if (ppObjectInstance)
        _pStaticObjectInstance = *ppObjectInstance;
    }
    return _pStaticObjectInstance;
  }

// Static class getter:
  static inline __Object_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__Object_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __Object_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t m_CachedPtr;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  int32_t GetInstanceID() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076400))(this);
  }
  int32_t GetHashCode() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076560))(this);
  }
  bool Equals(Il2CppObject* other) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, Il2CppObject*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076570))(this, other);
  }
  void EnsureRunningOnMainThread() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076890))(this);
  }
  intptr_t GetCachedPtr() {
    return reinterpret_cast<intptr_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x666540))(this);
  }
  System_String* get_name() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076A20))(this);
  }
  void set_name(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076AF0))(this, value);
  }
  int32_t get_hideFlags() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077790))(this);
  }
  void set_hideFlags(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10777E0))(this, value);
  }
  System_String* ToString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077CC0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<int32_t> OffsetOfInstanceIDInCPlusPlusObject = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->OffsetOfInstanceIDInCPlusPlusObject; }
  );

  // Static methods:
  static inline bool CompareBaseObjects(ModdingAPI::Exposed::UnityEngine::Object* lhs, ModdingAPI::Exposed::UnityEngine::Object* rhs) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076790))(lhs, rhs);
  }
  static inline bool IsNativeObjectAlive(ModdingAPI::Exposed::UnityEngine::Object* o) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076990))(o);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Instantiate(ModdingAPI::Exposed::UnityEngine::Object* original, ModdingAPI::Exposed::UnityEngine::Vector3 position, ModdingAPI::Exposed::UnityEngine::Quaternion rotation) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076BE0))(original, position, rotation);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Instantiate(ModdingAPI::Exposed::UnityEngine::Object* original, ModdingAPI::Exposed::UnityEngine::Vector3 position, ModdingAPI::Exposed::UnityEngine::Quaternion rotation, ModdingAPI::Exposed::UnityEngine::Transform* parent) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion, ModdingAPI::Exposed::UnityEngine::Transform*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1076E70))(original, position, rotation, parent);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Instantiate(ModdingAPI::Exposed::UnityEngine::Object* original) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10770F0))(original);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Instantiate(ModdingAPI::Exposed::UnityEngine::Object* original, ModdingAPI::Exposed::UnityEngine::Transform* parent) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Transform*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077220))(original, parent);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Instantiate(ModdingAPI::Exposed::UnityEngine::Object* original, ModdingAPI::Exposed::UnityEngine::Transform* parent, bool instantiateInWorldSpace) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Transform*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10772D0))(original, parent, instantiateInWorldSpace);
  }
  static inline void Destroy(ModdingAPI::Exposed::UnityEngine::Object* obj, float t) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077470))(obj, t);
  }
  static inline void Destroy(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10774D0))(obj);
  }
  static inline void DestroyImmediate(ModdingAPI::Exposed::UnityEngine::Object* obj, bool allowDestroyingAssets) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10775B0))(obj, allowDestroyingAssets);
  }
  static inline void DestroyImmediate(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077610))(obj);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object_array* FindObjectsOfType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10776F0))(type);
  }
  static inline void DontDestroyOnLoad(ModdingAPI::Exposed::UnityEngine::Object* target) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077740))(target);
  }
  static inline void DestroyObject(ModdingAPI::Exposed::UnityEngine::Object* obj, float t) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077840))(obj, t);
  }
  static inline void DestroyObject(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077920))(obj);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object_array* FindSceneObjectsOfType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077A00))(type);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object_array* FindObjectsOfTypeIncludingAssets(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077A50))(type);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object_array* FindObjectsOfTypeAll(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077AA0))(type);
  }
  static inline void CheckNullArgument(Il2CppObject* arg, System_String* message) {
    reinterpret_cast<void(__fastcall*)(Il2CppObject*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077AF0))(arg, message);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* FindObjectOfType(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077BB0))(type);
  }
  static inline int32_t GetOffsetOfInstanceIDInCPlusPlusObject() {
    return reinterpret_cast<int32_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077EF0))();
  }
  static inline bool CurrentThreadIsMainThread() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077F40))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_CloneSingle(ModdingAPI::Exposed::UnityEngine::Object* data) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077F90))(data);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_CloneSingleWithParent(ModdingAPI::Exposed::UnityEngine::Object* data, ModdingAPI::Exposed::UnityEngine::Transform* parent, bool worldPositionStays) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Transform*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1077FE0))(data, parent, worldPositionStays);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_InstantiateSingle(ModdingAPI::Exposed::UnityEngine::Object* data, ModdingAPI::Exposed::UnityEngine::Vector3 pos, ModdingAPI::Exposed::UnityEngine::Quaternion rot) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1078060))(data, pos, rot);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_InstantiateSingleWithParent(ModdingAPI::Exposed::UnityEngine::Object* data, ModdingAPI::Exposed::UnityEngine::Transform* parent, ModdingAPI::Exposed::UnityEngine::Vector3 pos, ModdingAPI::Exposed::UnityEngine::Quaternion rot) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Transform*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1078150))(data, parent, pos, rot);
  }
  static inline System_String* ToString(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1078250))(obj);
  }
  static inline System_String* GetName(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10782A0))(obj);
  }
  static inline void SetName(ModdingAPI::Exposed::UnityEngine::Object* obj, System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10782F0))(obj, name);
  }
  static inline bool DoesObjectWithInstanceIDExist(int32_t instanceID) {
    return reinterpret_cast<bool(__fastcall*)(int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1078350))(instanceID);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* FindObjectFromInstanceID(int32_t instanceID) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10783A0))(instanceID);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x10783F0))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_InstantiateSingle_Injected(ModdingAPI::Exposed::UnityEngine::Object* data, ModdingAPI::Exposed::UnityEngine::Vector3 pos, ModdingAPI::Exposed::UnityEngine::Quaternion rot) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1078470))(data, pos, rot);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Object* Internal_InstantiateSingleWithParent_Injected(ModdingAPI::Exposed::UnityEngine::Object* data, ModdingAPI::Exposed::UnityEngine::Transform* parent, ModdingAPI::Exposed::UnityEngine::Vector3 pos, ModdingAPI::Exposed::UnityEngine::Quaternion rot) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*, ModdingAPI::Exposed::UnityEngine::Transform*, ModdingAPI::Exposed::UnityEngine::Vector3, ModdingAPI::Exposed::UnityEngine::Quaternion)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10784E0))(data, parent, pos, rot);
  }
};
}