// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier.hpp"
#include "ModdingAPI::Exposed::System::Nullable_T_.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Matrix4x4.hpp"
#include "ModdingAPI::Exposed::UnityEngine::Vector2.hpp"
#include "ModdingAPI::Exposed::UnityEngine::Matrix4x4.hpp"


namespace ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing {
struct __RuntimeUtilities_Il2CppStaticFields {
  ModdingAPI::Exposed::UnityEngine::Texture2D* m_WhiteTexture;
  ModdingAPI::Exposed::UnityEngine::Texture3D* m_WhiteTexture3D;
  ModdingAPI::Exposed::UnityEngine::Texture2D* m_BlackTexture;
  ModdingAPI::Exposed::UnityEngine::Texture3D* m_BlackTexture3D;
  ModdingAPI::Exposed::UnityEngine::Texture2D* m_TransparentTexture;
  ModdingAPI::Exposed::UnityEngine::Texture3D* m_TransparentTexture3D;
  ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_* m_LutStrips;
  ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessResources* s_Resources;
  ModdingAPI::Exposed::UnityEngine::Mesh* s_FullscreenTriangle;
  ModdingAPI::Exposed::UnityEngine::Material* s_CopyStdMaterial;
  ModdingAPI::Exposed::UnityEngine::Material* s_CopyStdFromDoubleWideMaterial;
  ModdingAPI::Exposed::UnityEngine::Material* s_CopyMaterial;
  ModdingAPI::Exposed::UnityEngine::Material* s_CopyFromTexArrayMaterial;
  ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* s_CopySheet;
  ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* s_CopyFromTexArraySheet;
  ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_* m_AssemblyTypes;
};

struct __RuntimeUtilities_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __RuntimeUtilities_Il2CppClass {
  Il2CppClass_1 _1;
  __RuntimeUtilities_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __RuntimeUtilities_Il2CppVtbl vtbl;
};

class RuntimeUtilities {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C90670;
  static inline    __RuntimeUtilities_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __RuntimeUtilities_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__RuntimeUtilities_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __RuntimeUtilities_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*> m_WhiteTexture = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_WhiteTexture; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*> m_WhiteTexture3D = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_WhiteTexture3D; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*> m_BlackTexture = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_BlackTexture; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*> m_BlackTexture3D = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_BlackTexture3D; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*> m_TransparentTexture = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture2D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_TransparentTexture; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*> m_TransparentTexture3D = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Texture3D*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_TransparentTexture3D; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*> m_LutStrips = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::Dictionary_TKey__TValue_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_LutStrips; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessResources*> s_Resources = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessResources*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_Resources; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Mesh*> s_FullscreenTriangle = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Mesh*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_FullscreenTriangle; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*> s_CopyStdMaterial = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopyStdMaterial; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*> s_CopyStdFromDoubleWideMaterial = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopyStdFromDoubleWideMaterial; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*> s_CopyMaterial = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopyMaterial; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*> s_CopyFromTexArrayMaterial = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Material*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopyFromTexArrayMaterial; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*> s_CopySheet = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopySheet; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*> s_CopyFromTexArraySheet = __CppStaticProperty<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*>(
   []() { return &GetStaticClassInstance()->pStaticFields->s_CopyFromTexArraySheet; }
  );
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*> m_AssemblyTypes = __CppStaticProperty<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*>(
   []() { return &GetStaticClassInstance()->pStaticFields->m_AssemblyTypes; }
  );

  // Static methods:
  static inline ModdingAPI::Exposed::UnityEngine::Texture2D* get_whiteTexture() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture2D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1060))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture3D* get_whiteTexture3D() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture3D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1310))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture2D* get_blackTexture() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture2D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1660))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture3D* get_blackTexture3D() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture3D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1920))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture2D* get_transparentTexture() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture2D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1C70))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture3D* get_transparentTexture3D() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture3D*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E1F20))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Texture2D* GetLutStrip(int32_t size) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Texture2D*(__fastcall*)(int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E2270))(size);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Mesh* get_fullscreenTriangle() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Mesh*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E27C0))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Material* get_copyStdMaterial() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Material*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E2DD0))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Material* get_copyStdFromDoubleWideMaterial() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Material*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3080))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Material* get_copyMaterial() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Material*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3330))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Material* get_copyFromTexArrayMaterial() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Material*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E35E0))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* get_copySheet() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3890))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* get_copyFromTexArraySheet() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3A80))();
  }
  static inline void UpdateResources(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessResources* resources) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessResources*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3C70))(resources);
  }
  static inline void SetRenderTargetWithLoadStoreAction(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t loadAction, int32_t storeAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3DF0))(cmd, rt, loadAction, storeAction);
  }
  static inline void SetRenderTargetWithLoadStoreAction(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier color, int32_t colorLoadAction, int32_t colorStoreAction, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E3E40))(cmd, color, colorLoadAction, colorStoreAction, depth, depthLoadAction, depthStoreAction);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, bool clear, ModdingAPI::Exposed::System::Nullable_T_ viewport) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, bool, ModdingAPI::Exposed::System::Nullable_T_)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4000))(cmd, source, destination, clear, viewport);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, int32_t loadAction, ModdingAPI::Exposed::System::Nullable_T_ viewport) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, int32_t, ModdingAPI::Exposed::System::Nullable_T_)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4370))(cmd, source, destination, propertySheet, pass, loadAction, viewport);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, bool clear, ModdingAPI::Exposed::System::Nullable_T_ viewport) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, bool, ModdingAPI::Exposed::System::Nullable_T_)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E46D0))(cmd, source, destination, propertySheet, pass, clear, viewport);
  }
  static inline void BlitFullscreenTriangleFromDoubleWide(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t pass, int32_t eye) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4840))(cmd, source, destination, material, pass, eye);
  }
  static inline void BlitFullscreenTriangleToDoubleWide(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, int32_t eye) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4A50))(cmd, source, destination, propertySheet, pass, eye);
  }
  static inline void BlitFullscreenTriangleFromTexArray(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, bool clear, int32_t depthSlice) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4CB0))(cmd, source, destination, propertySheet, pass, clear, depthSlice);
  }
  static inline void BlitFullscreenTriangleToTexArray(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, bool clear, int32_t depthSlice) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E4FF0))(cmd, source, destination, propertySheet, pass, clear, depthSlice);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, bool clear, ModdingAPI::Exposed::System::Nullable_T_ viewport) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, bool, ModdingAPI::Exposed::System::Nullable_T_)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E5310))(cmd, source, destination, depth, propertySheet, pass, clear, viewport);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array* destinations, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, int32_t pass, bool clear, ModdingAPI::Exposed::System::Nullable_T_ viewport) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, int32_t, bool, ModdingAPI::Exposed::System::Nullable_T_)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E5700))(cmd, source, destinations, depth, propertySheet, pass, clear, viewport);
  }
  static inline void BuiltinBlit(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E5A30))(cmd, source, destination);
  }
  static inline void BuiltinBlit(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E5B90))(cmd, source, destination, mat, pass);
  }
  static inline void BlitFullscreenTriangle(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet* propertySheet, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties, int32_t pass, bool clear) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PropertySheet*, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E5D00))(cmd, source, destination, propertySheet, properties, pass, clear);
  }
  static inline void CopyTexture(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer* cmd, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier destination) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6000))(cmd, source, destination);
  }
  static inline bool get_scriptableRenderPipelineActive() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6260))();
  }
  static inline bool get_supportsDeferredShading() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E63D0))();
  }
  static inline bool get_supportsDepthNormals() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E64B0))();
  }
  static inline bool get_isSinglePassStereoEnabled() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E65A0))();
  }
  static inline bool get_isVREnabled() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x15938A0))();
  }
  static inline bool get_isAndroidOpenGL() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6620))();
  }
  static inline int32_t get_defaultHDRRenderTextureFormat() {
    return reinterpret_cast<int32_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x8C4B90))();
  }
  static inline bool isFloatingPointFormat(int32_t format) {
    return reinterpret_cast<bool(__fastcall*)(int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E66C0))(format);
  }
  static inline void Destroy(ModdingAPI::Exposed::UnityEngine::Object* obj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Object*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E66E0))(obj);
  }
  static inline bool get_isLinearColorSpace() {
    return reinterpret_cast<bool(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E67B0))();
  }
  static inline bool IsResolvedDepthAvailable(ModdingAPI::Exposed::UnityEngine::Camera* camera) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Camera*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6800))(camera);
  }
  static inline void DestroyProfile(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessProfile* profile, bool destroyEffects) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessProfile*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E68E0))(profile, destroyEffects);
  }
  static inline void DestroyVolume(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessVolume* volume, bool destroyProfile, bool destroyGameObject) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessVolume*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6A90))(volume, destroyProfile, destroyGameObject);
  }
  static inline bool IsPostProcessingActive(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessLayer* layer) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessLayer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6C10))(layer);
  }
  static inline bool IsTemporalAntialiasingActive(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessLayer* layer) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessLayer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6D10))(layer);
  }
  static inline float Exp2(float x) {
    return reinterpret_cast<float(__fastcall*)(float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6EB0))(x);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Matrix4x4 GetJitteredPerspectiveProjectionMatrix(ModdingAPI::Exposed::UnityEngine::Camera* camera, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Matrix4x4(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Camera*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E6F60))(camera, offset);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Matrix4x4 GetJitteredOrthographicProjectionMatrix(ModdingAPI::Exposed::UnityEngine::Camera* camera, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Matrix4x4(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Camera*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E7300))(camera, offset);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Matrix4x4 GenerateJitteredProjectionMatrixFromOriginal(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessRenderContext* context, ModdingAPI::Exposed::UnityEngine::Matrix4x4 origProj, ModdingAPI::Exposed::UnityEngine::Vector2 jitter) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Matrix4x4(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::PostProcessing::PostProcessRenderContext*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E7670))(context, origProj, jitter);
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_* GetAllAssemblyTypes() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E7870))();
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x22E7BF0))();
  }
};
}