// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::UnityEngine {
struct __AssetBundle_Il2CppStaticFields {
};

struct __AssetBundle_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __AssetBundle_Il2CppClass {
  Il2CppClass_1 _1;
  __AssetBundle_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __AssetBundle_Il2CppVtbl vtbl;
};

class AssetBundle {
public:
  // Il2Cpp fields:
  __AssetBundle_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D4F0))(this);
  }
  bool Contains(System_String* name) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D770))(this, name);
  }
  ModdingAPI::Exposed::UnityEngine::Object* LoadAsset(System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D7D0))(this, name);
  }
  ModdingAPI::Exposed::UnityEngine::Object* LoadAsset(System_String* name, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D8A0))(this, name, type);
  }
  ModdingAPI::Exposed::UnityEngine::Object* LoadAsset_Internal(System_String* name, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DA20))(this, name, type);
  }
  ModdingAPI::Exposed::UnityEngine::AssetBundleRequest* LoadAssetAsync(System_String* name) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundleRequest*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DA90))(this, name);
  }
  ModdingAPI::Exposed::UnityEngine::AssetBundleRequest* LoadAssetAsync(System_String* name, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundleRequest*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DB60))(this, name, type);
  }
  ModdingAPI::Exposed::UnityEngine::Object_array* LoadAllAssets() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DCE0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Object_array* LoadAllAssets(ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DDA0))(this, type);
  }
  ModdingAPI::Exposed::UnityEngine::AssetBundleRequest* LoadAssetAsync_Internal(System_String* name, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundleRequest*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DEB0))(this, name, type);
  }
  void Unload(bool unloadAllLoadedObjects) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DF20))(this, unloadAllLoadedObjects);
  }
  ModdingAPI::Exposed::UnityEngine::Object_array* LoadAssetWithSubAssets_Internal(System_String* name, ModdingAPI::Exposed::System::Type* type) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Object_array*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::AssetBundle*, System_String*, ModdingAPI::Exposed::System::Type*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158DF80))(this, name, type);
  }

  // Static methods:
  static inline ModdingAPI::Exposed::UnityEngine::AssetBundle_array* GetAllLoadedAssetBundles_Native() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundle_array*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D580))();
  }
  static inline ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_* GetAllLoadedAssetBundles() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::Generic::IEnumerable_T_*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D580))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::AssetBundleCreateRequest* LoadFromFileAsync_Internal(System_String* path, uint32_t crc, uint64_t offset) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundleCreateRequest*(__fastcall*)(System_String*, uint32_t, uint64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D5D0))(path, crc, offset);
  }
  static inline ModdingAPI::Exposed::UnityEngine::AssetBundleCreateRequest* LoadFromFileAsync(System_String* path) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundleCreateRequest*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D640))(path);
  }
  static inline ModdingAPI::Exposed::UnityEngine::AssetBundle* LoadFromFile_Internal(System_String* path, uint32_t crc, uint64_t offset) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundle*(__fastcall*)(System_String*, uint32_t, uint64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D6A0))(path, crc, offset);
  }
  static inline ModdingAPI::Exposed::UnityEngine::AssetBundle* LoadFromFile(System_String* path) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::AssetBundle*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x158D710))(path);
  }
};
}