// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.System.DateTime.hpp"
#include "ModdingAPI::Exposed::System::DateTime.hpp"
#include "ModdingAPI.Exposed.System.TimeSpan.hpp"


namespace ModdingAPI::Exposed::UnityPlugin {
struct __Utils_Il2CppStaticFields {
};

struct __Utils_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __Utils_Il2CppClass {
  Il2CppClass_1 _1;
  __Utils_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __Utils_Il2CppVtbl vtbl;
};

class Utils {
public:
  // Il2Cpp fields:
  __Utils_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityPlugin::Utils*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }

  // Static methods:
  static inline System_String* MarshalString(ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate* getString) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E223D0))(getString);
  }
  static inline System_String* MarshalCachedString(System_String* res, ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate* getString) {
    return reinterpret_cast<System_String*(__fastcall*)(System_String*, ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E224E0))(res, getString);
  }
  static inline ModdingAPI::Exposed::System::Uri* MarshalUri(ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate* getString) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Uri*(__fastcall*)(ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E22510))(getString);
  }
  static inline ModdingAPI::Exposed::System::Uri* MarshalCachedUri(ModdingAPI::Exposed::System::Uri* res, ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate* getString) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Uri*(__fastcall*)(ModdingAPI::Exposed::System::Uri*, ModdingAPI::Exposed::UnityPlugin::Utils::GetStringDelegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E226E0))(res, getString);
  }
  static inline ModdingAPI::Exposed::System::DateTime MarshalDateTime(ModdingAPI::Exposed::UnityPlugin::Utils::GetUInt64Delegate* getValue) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::UnityPlugin::Utils::GetUInt64Delegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E227A0))(getValue);
  }
  static inline ModdingAPI::Exposed::System::DateTime MarshalCachedDateTime(ModdingAPI::Exposed::System::DateTime res, ModdingAPI::Exposed::UnityPlugin::Utils::GetUInt64Delegate* getValue) {
    return reinterpret_cast<ModdingAPI::Exposed::System::DateTime(__fastcall*)(ModdingAPI::Exposed::System::DateTime, ModdingAPI::Exposed::UnityPlugin::Utils::GetUInt64Delegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E227F0))(res, getValue);
  }
  static inline ModdingAPI::Exposed::System::TimeSpan MarshalTimeSpan(ModdingAPI::Exposed::UnityPlugin::Utils::GetInt64Delegate* getValue) {
    return reinterpret_cast<ModdingAPI::Exposed::System::TimeSpan(__fastcall*)(ModdingAPI::Exposed::UnityPlugin::Utils::GetInt64Delegate*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E22900))(getValue);
  }
  static inline System_String* FormatException(ModdingAPI::Exposed::System::Exception* e) {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::System::Exception*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1E229C0))(e);
  }
};
}