// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.Vector4.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Rendering.RenderTargetIdentifier.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Matrix4x4.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Rect.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"
#include "ModdingAPI.Exposed.UnityEngine.RenderTextureDescriptor.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Color.hpp"


namespace ModdingAPI::Exposed::UnityEngine::Rendering {
struct __CommandBuffer_Il2CppStaticFields {
};

struct __CommandBuffer_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Dispose;
};

struct __CommandBuffer_Il2CppClass {
  Il2CppClass_1 _1;
  __CommandBuffer_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __CommandBuffer_Il2CppVtbl vtbl;
};

class CommandBuffer {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C512F8;
  static inline    __CommandBuffer_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __CommandBuffer_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__CommandBuffer_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __CommandBuffer_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t m_Ptr;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3C00))(this);
  }
  void ReleaseBuffer() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3CB0))(this);
  }
  void SetComputeVectorParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t nameID, ModdingAPI::Exposed::UnityEngine::Vector4 val) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3D00))(this, computeShader, nameID, val);
  }
  void Internal_SetComputeFloats(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t nameID, ModdingAPI::Exposed::System::Single_array* values) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, ModdingAPI::Exposed::System::Single_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3D80))(this, computeShader, nameID, values);
  }
  void Internal_SetComputeTextureParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, int32_t nameID, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t mipLevel) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3E00))(this, computeShader, kernelIndex, nameID, rt, mipLevel);
  }
  void SetComputeBufferParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, int32_t nameID, ModdingAPI::Exposed::UnityEngine::ComputeBuffer* buffer) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::ComputeBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3E90))(this, computeShader, kernelIndex, nameID, buffer);
  }
  void Internal_DispatchCompute(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, int32_t threadGroupsX, int32_t threadGroupsY, int32_t threadGroupsZ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3F20))(this, computeShader, kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);
  }
  void set_name(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3FB0))(this, value);
  }
  void Clear() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4010))(this);
  }
  void Internal_DrawMesh(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4060))(this, mesh, matrix, material, submeshIndex, shaderPass, properties);
  }
  void Internal_DrawRenderer(ModdingAPI::Exposed::UnityEngine::Renderer* renderer, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Renderer*, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4100))(this, renderer, material, submeshIndex, shaderPass);
  }
  void Internal_DrawMeshInstanced(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, int32_t submeshIndex, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t shaderPass, ModdingAPI::Exposed::UnityEngine::Matrix4x4_array* matrices, int32_t count, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, int32_t, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Matrix4x4_array*, int32_t, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4190))(this, mesh, submeshIndex, material, shaderPass, matrices, count, properties);
  }
  void SetViewport(ModdingAPI::Exposed::UnityEngine::Rect pixelRect) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rect)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4220))(this, pixelRect);
  }
  void CopyTexture_Internal(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier src, int32_t srcElement, int32_t srcMip, int32_t srcX, int32_t srcY, int32_t srcWidth, int32_t srcHeight, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dst, int32_t dstElement, int32_t dstMip, int32_t dstX, int32_t dstY, int32_t mode) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4280))(this, src, srcElement, srcMip, srcX, srcY, srcWidth, srcHeight, dst, dstElement, dstMip, dstX, dstY, mode);
  }
  void Blit_Texture(ModdingAPI::Exposed::UnityEngine::Texture* source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass, ModdingAPI::Exposed::UnityEngine::Vector2 scale, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Texture*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4310))(this, source, dest, mat, pass, scale, offset);
  }
  void Blit_Identifier(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass, ModdingAPI::Exposed::UnityEngine::Vector2 scale, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A43C0))(this, source, dest, mat, pass, scale, offset);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t readWrite, int32_t antiAliasing, bool enableRandomWrite, int32_t memorylessMode, bool useDynamicScale) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, bool, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4470))(this, nameID, width, height, depthBuffer, filter, format, readWrite, antiAliasing, enableRandomWrite, memorylessMode, useDynamicScale);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t readWrite, int32_t antiAliasing, bool enableRandomWrite, int32_t memorylessMode) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, bool, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4520))(this, nameID, width, height, depthBuffer, filter, format, readWrite, antiAliasing, enableRandomWrite, memorylessMode);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t readWrite, int32_t antiAliasing, bool enableRandomWrite) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A45C0))(this, nameID, width, height, depthBuffer, filter, format, readWrite, antiAliasing, enableRandomWrite);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t readWrite, int32_t antiAliasing) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A46A0))(this, nameID, width, height, depthBuffer, filter, format, readWrite, antiAliasing);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t readWrite) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4700))(this, nameID, width, height, depthBuffer, filter, format, readWrite);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4750))(this, nameID, width, height, depthBuffer, filter, format);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A47A0))(this, nameID, width, height, depthBuffer, filter);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A47F0))(this, nameID, width, height, depthBuffer);
  }
  void GetTemporaryRT(int32_t nameID, int32_t width, int32_t height) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4830))(this, nameID, width, height);
  }
  void GetTemporaryRTWithDescriptor(int32_t nameID, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor desc, int32_t filter) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4870))(this, nameID, desc, filter);
  }
  void GetTemporaryRT(int32_t nameID, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor desc, int32_t filter) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A48F0))(this, nameID, desc, filter);
  }
  void ReleaseTemporaryRT(int32_t nameID) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4990))(this, nameID);
  }
  void ClearRenderTarget(bool clearDepth, bool clearColor, ModdingAPI::Exposed::UnityEngine::Color backgroundColor, float depth) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, bool, bool, ModdingAPI::Exposed::UnityEngine::Color, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A49F0))(this, clearDepth, clearColor, backgroundColor, depth);
  }
  void ClearRenderTarget(bool clearDepth, bool clearColor, ModdingAPI::Exposed::UnityEngine::Color backgroundColor) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, bool, bool, ModdingAPI::Exposed::UnityEngine::Color)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4A80))(this, clearDepth, clearColor, backgroundColor);
  }
  void SetGlobalFloat(int32_t nameID, float value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4B10))(this, nameID, value);
  }
  void SetGlobalVector(int32_t nameID, ModdingAPI::Exposed::UnityEngine::Vector4 value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4B80))(this, nameID, value);
  }
  void SetViewProjectionMatrices(ModdingAPI::Exposed::UnityEngine::Matrix4x4 view, ModdingAPI::Exposed::UnityEngine::Matrix4x4 proj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Matrix4x4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4BF0))(this, view, proj);
  }
  void SetGlobalTexture_Impl(int32_t nameID, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4C60))(this, nameID, rt);
  }
  void BeginSample(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4CD0))(this, name);
  }
  void EndSample(System_String* name) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4D30))(this, name);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4D90))(this, rt);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t loadAction, int32_t storeAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4E20))(this, rt, loadAction, storeAction);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t mipLevel, int32_t cubemapFace, int32_t depthSlice) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A4F60))(this, rt, mipLevel, cubemapFace, depthSlice);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier color, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5180))(this, color, depth);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier color, int32_t colorLoadAction, int32_t colorStoreAction, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5230))(this, color, colorLoadAction, colorStoreAction, depth, depthLoadAction, depthStoreAction);
  }
  void SetRenderTarget(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array* colors, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A53D0))(this, colors, depth);
  }
  void SetRenderTargetSingle_Internal(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5640))(this, rt, colorLoadAction, colorStoreAction, depthLoadAction, depthStoreAction);
  }
  void SetRenderTargetColorDepth_Internal(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier color, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A56E0))(this, color, depth, colorLoadAction, colorStoreAction, depthLoadAction, depthStoreAction);
  }
  void SetRenderTargetMulti_Internal(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array* colors, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferLoadAction_array* colorLoadActions, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferStoreAction_array* colorStoreActions, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferLoadAction_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferStoreAction_array*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5780))(this, colors, depth, colorLoadActions, colorStoreActions, depthLoadAction, depthStoreAction);
  }
  void Finalize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5820))(this);
  }
  void Dispose() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A58B0))(this);
  }
  void Dispose(bool disposing) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5960))(this, disposing);
  }
  void Release() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A58B0))(this);
  }
  void SetComputeVectorParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, System_String* name, ModdingAPI::Exposed::UnityEngine::Vector4 val) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, System_String*, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5A20))(this, computeShader, name, val);
  }
  void SetComputeFloatParams(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, System_String* name, ModdingAPI::Exposed::System::Single_array* values) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, System_String*, ModdingAPI::Exposed::System::Single_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5AF0))(this, computeShader, name, values);
  }
  void SetComputeTextureParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, System_String* name, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, System_String*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5BC0))(this, computeShader, kernelIndex, name, rt);
  }
  void SetComputeBufferParam(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, System_String* name, ModdingAPI::Exposed::UnityEngine::ComputeBuffer* buffer) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, System_String*, ModdingAPI::Exposed::UnityEngine::ComputeBuffer*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5CA0))(this, computeShader, kernelIndex, name, buffer);
  }
  void DispatchCompute(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t kernelIndex, int32_t threadGroupsX, int32_t threadGroupsY, int32_t threadGroupsZ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3F20))(this, computeShader, kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);
  }
  void DrawMesh(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A5D70))(this, mesh, matrix, material, submeshIndex, shaderPass, properties);
  }
  void DrawMesh(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6110))(this, mesh, matrix, material, submeshIndex, shaderPass);
  }
  void DrawMesh(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6180))(this, mesh, matrix, material, submeshIndex);
  }
  void DrawMesh(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A61E0))(this, mesh, matrix, material);
  }
  void DrawRenderer(ModdingAPI::Exposed::UnityEngine::Renderer* renderer, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Renderer*, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6240))(this, renderer, material, submeshIndex, shaderPass);
  }
  void DrawRenderer(ModdingAPI::Exposed::UnityEngine::Renderer* renderer, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Renderer*, ModdingAPI::Exposed::UnityEngine::Material*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6460))(this, renderer, material, submeshIndex);
  }
  void DrawMeshInstanced(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, int32_t submeshIndex, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t shaderPass, ModdingAPI::Exposed::UnityEngine::Matrix4x4_array* matrices, int32_t count, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, int32_t, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Matrix4x4_array*, int32_t, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6480))(this, mesh, submeshIndex, material, shaderPass, matrices, count, properties);
  }
  void CopyTexture(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier src, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dst) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A68C0))(this, src, dst);
  }
  void CopyTexture(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier src, int32_t srcElement, int32_t srcMip, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dst, int32_t dstElement, int32_t dstMip) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6990))(this, src, srcElement, srcMip, dst, dstElement, dstMip);
  }
  void Blit(ModdingAPI::Exposed::UnityEngine::Texture* source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Texture*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6A80))(this, source, dest);
  }
  void Blit(ModdingAPI::Exposed::UnityEngine::Texture* source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Texture*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6AD0))(this, source, dest, mat);
  }
  void Blit(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6B20))(this, source, dest);
  }
  void Blit(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6B70))(this, source, dest, mat);
  }
  void Blit(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6BC0))(this, source, dest, mat, pass);
  }
  void SetGlobalVector(System_String* name, ModdingAPI::Exposed::UnityEngine::Vector4 value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, System_String*, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6C10))(this, name, value);
  }
  void SetGlobalTexture(System_String* name, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, System_String*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6CD0))(this, name, value);
  }
  void SetGlobalTexture(int32_t nameID, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6DA0))(this, nameID, value);
  }
  void SetComputeVectorParam_Injected(ModdingAPI::Exposed::UnityEngine::ComputeShader* computeShader, int32_t nameID, ModdingAPI::Exposed::UnityEngine::Vector4 val) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::ComputeShader*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6E10))(this, computeShader, nameID, val);
  }
  void Internal_DrawMesh_Injected(ModdingAPI::Exposed::UnityEngine::Mesh* mesh, ModdingAPI::Exposed::UnityEngine::Matrix4x4 matrix, ModdingAPI::Exposed::UnityEngine::Material* material, int32_t submeshIndex, int32_t shaderPass, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock* properties) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Mesh*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, int32_t, ModdingAPI::Exposed::UnityEngine::MaterialPropertyBlock*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6E90))(this, mesh, matrix, material, submeshIndex, shaderPass, properties);
  }
  void SetViewport_Injected(ModdingAPI::Exposed::UnityEngine::Rect pixelRect) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rect)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6F20))(this, pixelRect);
  }
  void Blit_Texture_Injected(ModdingAPI::Exposed::UnityEngine::Texture* source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass, ModdingAPI::Exposed::UnityEngine::Vector2 scale, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Texture*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A6F80))(this, source, dest, mat, pass, scale, offset);
  }
  void Blit_Identifier_Injected(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier source, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier dest, ModdingAPI::Exposed::UnityEngine::Material* mat, int32_t pass, ModdingAPI::Exposed::UnityEngine::Vector2 scale, ModdingAPI::Exposed::UnityEngine::Vector2 offset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Material*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A7010))(this, source, dest, mat, pass, scale, offset);
  }
  void GetTemporaryRTWithDescriptor_Injected(int32_t nameID, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor desc, int32_t filter) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::RenderTextureDescriptor, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A70A0))(this, nameID, desc, filter);
  }
  void ClearRenderTarget_Injected(bool clearDepth, bool clearColor, ModdingAPI::Exposed::UnityEngine::Color backgroundColor, float depth) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, bool, bool, ModdingAPI::Exposed::UnityEngine::Color, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A7120))(this, clearDepth, clearColor, backgroundColor, depth);
  }
  void SetGlobalVector_Injected(int32_t nameID, ModdingAPI::Exposed::UnityEngine::Vector4 value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, int32_t, ModdingAPI::Exposed::UnityEngine::Vector4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A71B0))(this, nameID, value);
  }
  void SetViewProjectionMatrices_Injected(ModdingAPI::Exposed::UnityEngine::Matrix4x4 view, ModdingAPI::Exposed::UnityEngine::Matrix4x4 proj) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Matrix4x4, ModdingAPI::Exposed::UnityEngine::Matrix4x4)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A7220))(this, view, proj);
  }
  void SetRenderTargetSingle_Internal_Injected(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier rt, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A7290))(this, rt, colorLoadAction, colorStoreAction, depthLoadAction, depthStoreAction);
  }
  void SetRenderTargetColorDepth_Internal_Injected(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier color, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, int32_t, int32_t, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A7320))(this, color, depth, colorLoadAction, colorStoreAction, depthLoadAction, depthStoreAction);
  }
  void SetRenderTargetMulti_Internal_Injected(ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array* colors, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier depth, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferLoadAction_array* colorLoadActions, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferStoreAction_array* colorStoreActions, int32_t depthLoadAction, int32_t depthStoreAction) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Rendering::CommandBuffer*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderTargetIdentifier, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferLoadAction_array*, ModdingAPI::Exposed::UnityEngine::Rendering::RenderBufferStoreAction_array*, int32_t, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A73B0))(this, colors, depth, colorLoadActions, colorStoreActions, depthLoadAction, depthStoreAction);
  }

  // Static methods:
  static inline intptr_t InitBuffer() {
    return reinterpret_cast<intptr_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x10A3C60))();
  }
};
}