// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed::UnityEngine::Networking {
struct __UnityWebRequest_Il2CppStaticFields {
};

struct __UnityWebRequest_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Dispose;
};

struct __UnityWebRequest_Il2CppClass {
  Il2CppClass_1 _1;
  __UnityWebRequest_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __UnityWebRequest_Il2CppVtbl vtbl;
};

class UnityWebRequest {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C66040;
  static inline    __UnityWebRequest_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __UnityWebRequest_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__UnityWebRequest_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __UnityWebRequest_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t m_Ptr;
  ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler* m_DownloadHandler;
  ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler* m_UploadHandler;
  ModdingAPI::Exposed::UnityEngine::Networking::CertificateHandler* m_CertificateHandler;
  ModdingAPI::Exposed::System::Uri* m_Uri;
  bool _disposeCertificateHandlerOnDispose_k__BackingField;
  bool _disposeDownloadHandlerOnDispose_k__BackingField;
  bool _disposeUploadHandlerOnDispose_k__BackingField;

  // Member methods:
  void ::ctor(System_String* url, System_String* method) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556300))(this, url, method);
  }
  void ::ctor(System_String* url, System_String* method, ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler* downloadHandler, ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler* uploadHandler) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*, System_String*, ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler*, ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556390))(this, url, method, downloadHandler, uploadHandler);
  }
  bool get_disposeCertificateHandlerOnDispose() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xFA4EB0))(this);
  }
  void set_disposeCertificateHandlerOnDispose(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x6CE3F0))(this, value);
  }
  bool get_disposeDownloadHandlerOnDispose() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15564F0))(this);
  }
  void set_disposeDownloadHandlerOnDispose(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556500))(this, value);
  }
  bool get_disposeUploadHandlerOnDispose() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556510))(this);
  }
  void set_disposeUploadHandlerOnDispose(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAB3C70))(this, value);
  }
  void Release() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556570))(this);
  }
  void InternalDestroy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15565C0))(this);
  }
  void InternalSetDefaults() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15566D0))(this);
  }
  void Finalize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15566E0))(this);
  }
  void Dispose() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15567B0))(this);
  }
  void DisposeHandlers() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15568A0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequestAsyncOperation* BeginWebRequest() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequestAsyncOperation*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556900))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequestAsyncOperation* SendWebRequest() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequestAsyncOperation*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556950))(this);
  }
  void Abort() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15569B0))(this);
  }
  int32_t SetMethod(int32_t methodType) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556A00))(this, methodType);
  }
  void InternalSetMethod(int32_t methodType) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556A60))(this, methodType);
  }
  int32_t SetCustomMethod(System_String* customMethodName) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556BE0))(this, customMethodName);
  }
  void InternalSetCustomMethod(System_String* customMethodName) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556C40))(this, customMethodName);
  }
  void set_method(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556DC0))(this, value);
  }
  int32_t GetError() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15570F0))(this);
  }
  System_String* get_error() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557140))(this);
  }
  System_String* get_url() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557480))(this);
  }
  void set_url(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15574D0))(this, value);
  }
  System_String* GetUrl() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557480))(this);
  }
  int32_t SetUrl(System_String* url) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15576F0))(this, url);
  }
  void InternalSetUrl(System_String* url) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557750))(this, url);
  }
  int64_t get_responseCode() {
    return reinterpret_cast<int64_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15578D0))(this);
  }
  bool get_isModifiable() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557920))(this);
  }
  bool get_isDone() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557970))(this);
  }
  bool get_isNetworkError() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15579C0))(this);
  }
  bool get_isHttpError() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557A10))(this);
  }
  int32_t InternalSetRequestHeader(System_String* name, System_String* value) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557A60))(this, name, value);
  }
  void SetRequestHeader(System_String* name, System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, System_String*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557AD0))(this, name, value);
  }
  int32_t SetUploadHandler(ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler* uh) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557CE0))(this, uh);
  }
  ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler* get_uploadHandler() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAD4220))(this);
  }
  void set_uploadHandler(ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, ModdingAPI::Exposed::UnityEngine::Networking::UploadHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557D40))(this, value);
  }
  int32_t SetDownloadHandler(ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler* dh) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557ED0))(this, dh);
  }
  ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler* get_downloadHandler() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xADD890))(this);
  }
  void set_downloadHandler(ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, ModdingAPI::Exposed::UnityEngine::Networking::DownloadHandler*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1557F30))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::Networking::CertificateHandler* get_certificateHandler() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::CertificateHandler*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAD25E0))(this);
  }

  // Static methods:
  static inline System_String* GetWebErrorString(int32_t err) {
    return reinterpret_cast<System_String*(__fastcall*)(int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556450))(err);
  }
  static inline System_String* GetHTTPStatusString(int64_t responseCode) {
    return reinterpret_cast<System_String*(__fastcall*)(int64_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15564A0))(responseCode);
  }
  static inline intptr_t Create() {
    return reinterpret_cast<intptr_t(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x1556520))();
  }
  static inline ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest* Get(System_String* uri) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x15580C0))(uri);
  }
  static inline ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest* Post(System_String* uri, ModdingAPI::Exposed::UnityEngine::WWWForm* formData) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*(__fastcall*)(System_String*, ModdingAPI::Exposed::UnityEngine::WWWForm*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1558390))(uri, formData);
  }
  static inline void SetupPost(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest* request, ModdingAPI::Exposed::UnityEngine::WWWForm* formData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::Networking::UnityWebRequest*, ModdingAPI::Exposed::UnityEngine::WWWForm*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x1558550))(request, formData);
  }
};
}