// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"
#include "ModdingAPI.Exposed.UnityEngine.UI.Navigation.hpp"
#include "ModdingAPI.Exposed.UnityEngine.UI.ColorBlock.hpp"
#include "ModdingAPI.Exposed.UnityEngine.UI.SpriteState.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Color.hpp"
#include "ModdingAPI.Exposed.UnityEngine.Vector2.hpp"


namespace ModdingAPI::Exposed::UnityEngine::UI {
struct __InputField_Il2CppStaticFields {
  ModdingAPI::Exposed::System::Char_array* kSeparators;
};

struct __InputField_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Awake;
  VirtualInvokeData _5_OnEnable;
  VirtualInvokeData _6_Start;
  VirtualInvokeData _7_OnDisable;
  VirtualInvokeData _8_OnDestroy;
  VirtualInvokeData _9_IsActive;
  VirtualInvokeData _10_OnRectTransformDimensionsChange;
  VirtualInvokeData _11_OnBeforeTransformParentChanged;
  VirtualInvokeData _12_OnTransformParentChanged;
  VirtualInvokeData _13_OnDidApplyAnimationProperties;
  VirtualInvokeData _14_OnCanvasGroupChanged;
  VirtualInvokeData _15_OnCanvasHierarchyChanged;
  VirtualInvokeData _16_IsDestroyed;
  VirtualInvokeData _24_IsInteractable;
  VirtualInvokeData _25_InstantClearState;
  VirtualInvokeData _26_DoStateTransition;
  VirtualInvokeData _27_FindSelectableOnLeft;
  VirtualInvokeData _28_FindSelectableOnRight;
  VirtualInvokeData _29_FindSelectableOnUp;
  VirtualInvokeData _30_FindSelectableOnDown;
  VirtualInvokeData _31_OnMove;
  VirtualInvokeData _32_OnPointerDown;
  VirtualInvokeData _33_OnPointerUp;
  VirtualInvokeData _34_OnPointerEnter;
  VirtualInvokeData _35_OnPointerExit;
  VirtualInvokeData _36_OnSelect;
  VirtualInvokeData _37_OnDeselect;
  VirtualInvokeData _38_Select;
  VirtualInvokeData _46_UnityEngine_UI_ICanvasElement_get_transform;
  VirtualInvokeData _59_LateUpdate;
  VirtualInvokeData _60_OnBeginDrag;
  VirtualInvokeData _61_OnDrag;
  VirtualInvokeData _62_OnEndDrag;
  VirtualInvokeData _63_OnUpdateSelected;
  VirtualInvokeData _64_Append;
  VirtualInvokeData _65_Append;
  VirtualInvokeData _66_Rebuild;
  VirtualInvokeData _67_LayoutComplete;
  VirtualInvokeData _68_GraphicUpdateComplete;
  VirtualInvokeData _69_OnPointerClick;
  VirtualInvokeData _70_OnSubmit;
  VirtualInvokeData _71_CalculateLayoutInputHorizontal;
  VirtualInvokeData _72_CalculateLayoutInputVertical;
  VirtualInvokeData _73_get_minWidth;
  VirtualInvokeData _74_get_preferredWidth;
  VirtualInvokeData _75_get_flexibleWidth;
  VirtualInvokeData _76_get_minHeight;
  VirtualInvokeData _77_get_preferredHeight;
  VirtualInvokeData _78_get_flexibleHeight;
  VirtualInvokeData _79_get_layoutPriority;
};

struct __InputField_Il2CppClass {
  Il2CppClass_1 _1;
  __InputField_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __InputField_Il2CppVtbl vtbl;
};

class InputField {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C808A0;
  static inline    __InputField_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __InputField_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__InputField_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __InputField_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  intptr_t Object_m_CachedPtr;
  ModdingAPI::Exposed::UnityEngine::UI::Navigation Selectable_m_Navigation;
  int32_t Selectable_m_Transition;
  ModdingAPI::Exposed::UnityEngine::UI::ColorBlock Selectable_m_Colors;
  ModdingAPI::Exposed::UnityEngine::UI::SpriteState Selectable_m_SpriteState;
  ModdingAPI::Exposed::UnityEngine::UI::AnimationTriggers* Selectable_m_AnimationTriggers;
  bool Selectable_m_Interactable;
  ModdingAPI::Exposed::UnityEngine::UI::Graphic* Selectable_m_TargetGraphic;
  bool Selectable_m_GroupsAllowInteraction;
  int32_t Selectable_m_CurrentSelectionState;
  bool Selectable__isPointerInside_k__BackingField;
  bool Selectable__isPointerDown_k__BackingField;
  bool Selectable__hasSelection_k__BackingField;
  ModdingAPI::Exposed::System::Collections::Generic::List_T_* Selectable_m_CanvasGroupCache;
  ModdingAPI::Exposed::UnityEngine::TouchScreenKeyboard* m_Keyboard;
  ModdingAPI::Exposed::UnityEngine::UI::Text* m_TextComponent;
  ModdingAPI::Exposed::UnityEngine::UI::Graphic* m_Placeholder;
  int32_t m_ContentType;
  int32_t m_InputType;
  wchar_t m_AsteriskChar;
  int32_t m_KeyboardType;
  int32_t m_LineType;
  bool m_HideMobileInput;
  int32_t m_CharacterValidation;
  int32_t m_CharacterLimit;
  ModdingAPI::Exposed::UnityEngine::UI::InputField::SubmitEvent* m_OnEndEdit;
  ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent* m_OnValueChanged;
  ModdingAPI::Exposed::UnityEngine::UI::InputField::OnValidateInput* m_OnValidateInput;
  ModdingAPI::Exposed::UnityEngine::Color m_CaretColor;
  bool m_CustomCaretColor;
  ModdingAPI::Exposed::UnityEngine::Color m_SelectionColor;
  System_String* m_Text;
  float m_CaretBlinkRate;
  int32_t m_CaretWidth;
  bool m_ReadOnly;
  int32_t m_CaretPosition;
  int32_t m_CaretSelectPosition;
  ModdingAPI::Exposed::UnityEngine::RectTransform* caretRectTrans;
  ModdingAPI::Exposed::UnityEngine::UIVertex_array* m_CursorVerts;
  ModdingAPI::Exposed::UnityEngine::TextGenerator* m_InputTextCache;
  ModdingAPI::Exposed::UnityEngine::CanvasRenderer* m_CachedInputRenderer;
  bool m_PreventFontCallback;
  ModdingAPI::Exposed::UnityEngine::Mesh* m_Mesh;
  bool m_AllowInput;
  bool m_ShouldActivateNextUpdate;
  bool m_UpdateDrag;
  bool m_DragPositionOutOfBounds;
  bool m_CaretVisible;
  ModdingAPI::Exposed::UnityEngine::Coroutine* m_BlinkCoroutine;
  float m_BlinkStartTime;
  int32_t m_DrawStart;
  int32_t m_DrawEnd;
  ModdingAPI::Exposed::UnityEngine::Coroutine* m_DragCoroutine;
  System_String* m_OriginalText;
  bool m_WasCanceled;
  bool m_HasDoneFocusTransition;
  ModdingAPI::Exposed::UnityEngine::WaitForSecondsRealtime* m_WaitForSecondsRealtime;
  ModdingAPI::Exposed::UnityEngine::Event* m_ProcessingEvent;

  // Member methods:
  void ::ctor() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3E750))(this);
  }
  ModdingAPI::Exposed::UnityEngine::EventSystems::BaseInput* get_input() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::EventSystems::BaseInput*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3EC30))(this);
  }
  System_String* get_compositionString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3EDB0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Mesh* get_mesh() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Mesh*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3EEE0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::TextGenerator* get_cachedInputTextGenerator() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::TextGenerator*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F080))(this);
  }
  void set_shouldHideMobileInput(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F1F0))(this, value);
  }
  bool get_shouldHideMobileInput() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F2C0))(this);
  }
  bool get_shouldActivateOnSelect() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F330))(this);
  }
  System_String* get_text() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F380))(this);
  }
  void set_text(System_String* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F390))(this, value);
  }
  bool get_isFocused() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F7B0))(this);
  }
  float get_caretBlinkRate() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F7C0))(this);
  }
  void set_caretBlinkRate(float value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, float)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F7D0))(this, value);
  }
  int32_t get_caretWidth() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F8B0))(this);
  }
  void set_caretWidth(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F8C0))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::Text* get_textComponent() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::Text*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAEE910))(this);
  }
  void set_textComponent(ModdingAPI::Exposed::UnityEngine::UI::Text* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::Text*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3F990))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::Graphic* get_placeholder() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::Graphic*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAEE930))(this);
  }
  void set_placeholder(ModdingAPI::Exposed::UnityEngine::UI::Graphic* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::Graphic*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40090))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::Color get_caretColor() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Color(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40150))(this);
  }
  void set_caretColor(ModdingAPI::Exposed::UnityEngine::Color value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Color)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE401B0))(this, value);
  }
  bool get_customCaretColor() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40240))(this);
  }
  void set_customCaretColor(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40250))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::Color get_selectionColor() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Color(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40270))(this);
  }
  void set_selectionColor(ModdingAPI::Exposed::UnityEngine::Color value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Color)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40280))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::InputField::SubmitEvent* get_onEndEdit() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::InputField::SubmitEvent*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAEE9C0))(this);
  }
  void set_onEndEdit(ModdingAPI::Exposed::UnityEngine::UI::InputField::SubmitEvent* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::InputField::SubmitEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40310))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent* get_onValueChange() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE403D0))(this);
  }
  void set_onValueChange(ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE403E0))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent* get_onValueChanged() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE403D0))(this);
  }
  void set_onValueChanged(ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::InputField::OnChangeEvent*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE403E0))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::UI::InputField::OnValidateInput* get_onValidateInput() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::UI::InputField::OnValidateInput*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE404A0))(this);
  }
  void set_onValidateInput(ModdingAPI::Exposed::UnityEngine::UI::InputField::OnValidateInput* value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::InputField::OnValidateInput*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE404B0))(this, value);
  }
  int32_t get_characterLimit() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40570))(this);
  }
  void set_characterLimit(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40580))(this, value);
  }
  int32_t get_contentType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40680))(this);
  }
  void set_contentType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40690))(this, value);
  }
  int32_t get_lineType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAEE9D0))(this);
  }
  void set_lineType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40880))(this, value);
  }
  int32_t get_inputType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE409B0))(this);
  }
  void set_inputType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE409C0))(this, value);
  }
  ModdingAPI::Exposed::UnityEngine::TouchScreenKeyboard* get_touchScreenKeyboard() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::TouchScreenKeyboard*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xAE3B40))(this);
  }
  int32_t get_keyboardType() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40A70))(this);
  }
  void set_keyboardType(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40A80))(this, value);
  }
  int32_t get_characterValidation() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40B30))(this);
  }
  void set_characterValidation(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40B40))(this, value);
  }
  bool get_readOnly() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40BF0))(this);
  }
  void set_readOnly(bool value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40C00))(this, value);
  }
  bool get_multiLine() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40C10))(this);
  }
  wchar_t get_asteriskChar() {
    return reinterpret_cast<wchar_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40C30))(this);
  }
  void set_asteriskChar(wchar_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40C40))(this, value);
  }
  bool get_wasCanceled() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40D20))(this);
  }
  void ClampPos(int32_t pos) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40D30))(this, pos);
  }
  int32_t get_caretPositionInternal() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40D80))(this);
  }
  void set_caretPositionInternal(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40DB0))(this, value);
  }
  int32_t get_caretSelectPositionInternal() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40E00))(this);
  }
  void set_caretSelectPositionInternal(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40E30))(this, value);
  }
  bool get_hasSelection() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40E80))(this);
  }
  int32_t get_caretPosition() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40E00))(this);
  }
  void set_caretPosition(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40EF0))(this, value);
  }
  int32_t get_selectionAnchorPosition() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40D80))(this);
  }
  void set_selectionAnchorPosition(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40FD0))(this, value);
  }
  int32_t get_selectionFocusPosition() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE40E00))(this);
  }
  void set_selectionFocusPosition(int32_t value) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41050))(this, value);
  }
  void OnEnable() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE410D0))(this);
  }
  void OnDisable() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE415B0))(this);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* CaretBlink() {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41AA0))(this);
  }
  void SetCaretVisible() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41BF0))(this);
  }
  void SetCaretActive() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41C70))(this);
  }
  void UpdateCaretMaterial() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41E10))(this);
  }
  void OnFocus() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41FC0))(this);
  }
  void SelectAll() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE41FD0))(this);
  }
  void MoveTextEnd(bool shift) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42060))(this, shift);
  }
  void MoveTextStart(bool shift) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42180))(this, shift);
  }
  bool InPlaceEditing() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x39B730))(this);
  }
  void UpdateCaretFromKeyboard() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42270))(this);
  }
  void LateUpdate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE423F0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Vector2 ScreenToLocal(ModdingAPI::Exposed::UnityEngine::Vector2 screen) {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Vector2(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42490))(this, screen);
  }
  int32_t GetUnclampedCharacterLineFromPosition(ModdingAPI::Exposed::UnityEngine::Vector2 pos, ModdingAPI::Exposed::UnityEngine::TextGenerator* generator) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Vector2, ModdingAPI::Exposed::UnityEngine::TextGenerator*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42A10))(this, pos, generator);
  }
  int32_t GetCharacterIndexFromPosition(ModdingAPI::Exposed::UnityEngine::Vector2 pos) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42C60))(this, pos);
  }
  bool MayDrag(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE42F70))(this, eventData);
  }
  void OnBeginDrag(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE43090))(this, eventData);
  }
  void OnDrag(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE430C0))(this, eventData);
  }
  ModdingAPI::Exposed::System::Collections::IEnumerator* MouseDragOutsideRect(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    return reinterpret_cast<ModdingAPI::Exposed::System::Collections::IEnumerator*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE43470))(this, eventData);
  }
  void OnEndDrag(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE435D0))(this, eventData);
  }
  void OnPointerDown(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE43600))(this, eventData);
  }
  int32_t KeyPressed(ModdingAPI::Exposed::UnityEngine::Event* evt) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Event*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE43860))(this, evt);
  }
  bool IsValidChar(wchar_t c) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE43FF0))(this, c);
  }
  void ProcessEvent(ModdingAPI::Exposed::UnityEngine::Event* e) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Event*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE440B0))(this, e);
  }
  void OnUpdateSelected(ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE440C0))(this, eventData);
  }
  System_String* GetSelectedString() {
    return reinterpret_cast<System_String*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE44310))(this);
  }
  int32_t FindtNextWordBegin() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE44470))(this);
  }
  void MoveRight(bool shift, bool ctrl) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE44600))(this, shift, ctrl);
  }
  int32_t FindtPrevWordBegin() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE448F0))(this);
  }
  void MoveLeft(bool shift, bool ctrl) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE44A40))(this, shift, ctrl);
  }
  int32_t DetermineCharacterLine(int32_t charPos, ModdingAPI::Exposed::UnityEngine::TextGenerator* generator) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t, ModdingAPI::Exposed::UnityEngine::TextGenerator*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE44E40))(this, charPos, generator);
  }
  int32_t LineUpCharacterPosition(int32_t originalPos, bool goToFirstChar) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE45030))(this, originalPos, goToFirstChar);
  }
  int32_t LineDownCharacterPosition(int32_t originalPos, bool goToLastChar) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE452B0))(this, originalPos, goToLastChar);
  }
  void MoveDown(bool shift) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE455C0))(this, shift);
  }
  void MoveDown(bool shift, bool goToLastChar) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE455D0))(this, shift, goToLastChar);
  }
  void MoveUp(bool shift) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE458F0))(this, shift);
  }
  void MoveUp(bool shift, bool goToFirstChar) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, bool, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE45900))(this, shift, goToFirstChar);
  }
  void Delete() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE45C00))(this);
  }
  void ForwardSpace() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE45F20))(this);
  }
  void Backspace() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46020))(this);
  }
  void Insert(wchar_t c) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46150))(this, c);
  }
  void SendOnValueChangedAndUpdateLabel() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE462B0))(this);
  }
  void SendOnValueChanged() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE462D0))(this);
  }
  void SendOnSubmit() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE463C0))(this);
  }
  void Append(System_String* input) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE464B0))(this, input);
  }
  void Append(wchar_t input) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46550))(this, input);
  }
  void UpdateLabel() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46720))(this);
  }
  bool IsSelectionVisible() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46C10))(this);
  }
  void SetDrawRangeToContainCaretPosition(int32_t caretPos) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE47060))(this, caretPos);
  }
  void ForceLabelUpdate() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE47840))(this);
  }
  void MarkGeometryAsDirty() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE47850))(this);
  }
  void Rebuild(int32_t update) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE478F0))(this, update);
  }
  void LayoutComplete() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  void GraphicUpdateComplete() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  void UpdateGeometry() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE47900))(this);
  }
  void AssignPositioningIfNeeded() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE47E50))(this);
  }
  void OnFillVBO(ModdingAPI::Exposed::UnityEngine::Mesh* vbo) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::Mesh*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE48A10))(this, vbo);
  }
  void GenerateCaret(ModdingAPI::Exposed::UnityEngine::UI::VertexHelper* vbo, ModdingAPI::Exposed::UnityEngine::Vector2 roundingOffset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::VertexHelper*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE48CA0))(this, vbo, roundingOffset);
  }
  void CreateCursorVerts() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE49560))(this);
  }
  void GenerateHightlight(ModdingAPI::Exposed::UnityEngine::UI::VertexHelper* vbo, ModdingAPI::Exposed::UnityEngine::Vector2 roundingOffset) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::VertexHelper*, ModdingAPI::Exposed::UnityEngine::Vector2)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE49740))(this, vbo, roundingOffset);
  }
  wchar_t Validate(System_String* text, int32_t pos, wchar_t ch) {
    return reinterpret_cast<wchar_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, System_String*, int32_t, wchar_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4A010))(this, text, pos, ch);
  }
  void ActivateInputField() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4A760))(this);
  }
  void ActivateInputFieldInternal() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4A8B0))(this);
  }
  void OnSelect(ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4AB30))(this, eventData);
  }
  void OnPointerClick(ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::PointerEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4ABA0))(this, eventData);
  }
  void DeactivateInputField() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4ABD0))(this);
  }
  void OnDeselect(ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4AE60))(this, eventData);
  }
  void OnSubmit(ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData* eventData) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::EventSystems::BaseEventData*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4AE90))(this, eventData);
  }
  void EnforceContentType() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4AEE0))(this);
  }
  void EnforceTextHOverflow() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B050))(this);
  }
  void SetToCustomIfContentTypeIsNot(ModdingAPI::Exposed::UnityEngine::UI::InputField::ContentType_array* allowedContentTypes) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, ModdingAPI::Exposed::UnityEngine::UI::InputField::ContentType_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B160))(this, allowedContentTypes);
  }
  void SetToCustom() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B1D0))(this);
  }
  void DoStateTransition(int32_t state, bool instant) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*, int32_t, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B1F0))(this, state, instant);
  }
  void CalculateLayoutInputHorizontal() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  void CalculateLayoutInputVertical() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x2FEC40))(this);
  }
  float get_minWidth() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3D1D0))(this);
  }
  float get_preferredWidth() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B220))(this);
  }
  float get_flexibleWidth() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3D380))(this);
  }
  float get_minHeight() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3D1D0))(this);
  }
  float get_preferredHeight() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B420))(this);
  }
  float get_flexibleHeight() {
    return reinterpret_cast<float(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE3D380))(this);
  }
  int32_t get_layoutPriority() {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B6A0))(this);
  }
  ModdingAPI::Exposed::UnityEngine::Transform* UnityEngine::UI::ICanvasElement::get_transform() {
    return reinterpret_cast<ModdingAPI::Exposed::UnityEngine::Transform*(__fastcall*)(ModdingAPI::Exposed::UnityEngine::UI::InputField*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x4117E0))(this);
  }

  // Static fields:
  static inline __CppStaticProperty<ModdingAPI::Exposed::System::Char_array*> kSeparators = __CppStaticProperty<ModdingAPI::Exposed::System::Char_array*>(
   []() { return &GetStaticClassInstance()->pStaticFields->kSeparators; }
  );

  // Static methods:
  static inline System_String* get_clipboard() {
    return reinterpret_cast<System_String*(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x403ED0))();
  }
  static inline void set_clipboard(System_String* value) {
    reinterpret_cast<void(__fastcall*)(System_String*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x403F20))(value);
  }
  static inline int32_t GetLineStartPosition(ModdingAPI::Exposed::UnityEngine::TextGenerator* gen, int32_t line) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::TextGenerator*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46D00))(gen, line);
  }
  static inline int32_t GetLineEndPosition(ModdingAPI::Exposed::UnityEngine::TextGenerator* gen, int32_t line) {
    return reinterpret_cast<int32_t(__fastcall*)(ModdingAPI::Exposed::UnityEngine::TextGenerator*, int32_t)>(Helpers::Memory::GetInstance().MakeAbsolute(0xE46E90))(gen, line);
  }
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0xE4B6B0))();
  }
};
}