// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppStaticFields {
};

struct __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
  VirtualInvokeData _4_Dispose;
  VirtualInvokeData _5_SblXCiMPddwpGkmmMqEoUPgVkXg;
};

struct __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppClass {
  Il2CppClass_1 _1;
  __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppVtbl vtbl;
};

class WusYVFBbnjmFQkOhEUclLJIshwS {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C6CF00;
  static inline    __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __WusYVFBbnjmFQkOhEUclLJIshwS_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Member fields:
  ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS::VRDyUFuidimSYTPiqcSRFqBUYhJ* OcOHFAsrrTCinszYFCWAJgQzxQR;
  ModdingAPI::Exposed::QNhYhnUzQjITmWUXFOIhIpVOePD* RgngEpgQoIgYFLxNqWRKQhoiiaiv;
  ModdingAPI::Exposed::Rewired::Utils::Classes::Utility::ThreadHelper* wppFHLdbZuzRyblvbhzvIyaRxrS;
  int32_t FwxfymxVUzZdxHjWuCwdkgkPutw;
  int32_t rCusjsumjAfGdZJEUEuuNbnwafB;
  System_String* JQTVMKeYcXhEpkVfiLKRjmlhiym;
  ModdingAPI::Exposed::System::Byte_array* KeBMjVasABkYwNziIodCNAwmDgsh;
  ModdingAPI::Exposed::System::Byte_array* gZqMGFdJXFZZvmPrSlUnWnwEDxMF;
  int32_t FtXWXrAxfLJxEONSHGIjIpVTAPm;
  ModdingAPI::Exposed::CmVZaFTaQCvkGCuyUAzqsObTvza* kmYXiFLhGGEucMzeRSdIdZySzqg;
  ModdingAPI::Exposed::CmVZaFTaQCvkGCuyUAzqsObTvza* LflsgDZRPJYAWkxtknkTKttanQZ;
  bool aStwDHfMTTrjGocQNajmbHbmhvJ;

  // Member methods:
  void ::ctor(System_String* hidDevicePath, int32_t reportByteLength, System_String* productName, ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS::VRDyUFuidimSYTPiqcSRFqBUYhJ* processReportDelegate) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*, System_String*, int32_t, System_String*, ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS::VRDyUFuidimSYTPiqcSRFqBUYhJ*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7260))(this, hidDevicePath, reportByteLength, productName, processReportDelegate);
  }
  void RlXzuMMBSmmuFIYXRJDvBFGdebZ() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7890))(this);
  }
  void PEFtMzsjFOlPuGRKvggTfBCQAFP() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7A30))(this);
  }
  void GyFLOvtxiOAhikjStsvCctGdzpy() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7C30))(this);
  }
  bool qFxTeTEaVJCPlwRcwUHfNdTexn(ModdingAPI::Exposed::System::Byte_array* ) {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*, ModdingAPI::Exposed::System::Byte_array*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7E40))(this, );
  }
  bool IGxKKSLjmZcPwChforDOXJaBvZb() {
    return reinterpret_cast<bool(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7EA0))(this);
  }
  void Dispose() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D7FD0))(this);
  }
  void Finalize() {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8080))(this);
  }
  void SblXCiMPddwpGkmmMqEoUPgVkXg(bool ) {
    reinterpret_cast<void(__fastcall*)(ModdingAPI::Exposed::WusYVFBbnjmFQkOhEUclLJIshwS*, bool)>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8100))(this, );
  }
};
}