// clang-format off
//
//   BSD 4-Clause License
//
//   Copyright (c) 2020 Berkay Yigit <berkaytgy@gmail.com>
//   All rights reserved.
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions are met:
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//   2. Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//   3. All advertising materials mentioning features or use of this software
//      must display the following acknowledgement:
//      This product includes software developed by Berkay Yigit.
//      To support the developer, please donate to:
//      "https://www.paypal.me/berkayylmao".
//   4. Neither the name of "berkayylmao's The Long Dark Mods" nor the
//      names of its contributors may be used to endorse or promote products
//      derived from this software without specific prior written permission.
//
//   THIS SOFTWARE IS PROVIDED BY Berkay Yigit ''AS IS'' AND  ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL Berkay Yigit BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// clang-format on

/*
 * Generated by Il2CppTypeDumper (by berkayylmao) on 10:43 02/05/2020 UTC.
 * MIT License
 * Copyright(c) 2020 Berkay Yigit <berkaytgy@gmail.com>
 *
 * A fork of Il2CppDumper (by Perfare)
 * Il2CppDumper license:
 *   MIT License
 *   Copyright(c) 2016 Perfare
 */

#pragma once
#include "Il2CppBase.h"


namespace ModdingAPI::Exposed {
struct __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppStaticFields {
  intptr_t PBrErMrModRYdhnEAQaoEMtkCptA;
  int32_t GiNOobmnHEQEiywTrvQxleszgIE;
  int32_t HEqihPDMKItxDioIeQCJchzCjmvO;
  int32_t MsCsKBxsjMeIoEYSdGnsCpJnGsX;
  int32_t dkBwxlrTkpLGnxxnJlTmMzonWRF;
  int32_t HHcTtKdKWQxSYkZLdsHIzbkkEZV;
  int32_t tNovdfDIKoDwrygtFmLPupgyplT;
  int32_t pYesNWphMpiwCDgbEKpoeqtEHomi;
  int32_t tjEmHreRROmedejbUEiMwnuVgEA;
  int32_t SmpAVfbIiUhiwxFyxhFzAUYEkGmL;
  int32_t RhpJkRZnELgAQNrDyAWLsiNyxLt;
  int32_t uSQoYuqHeXSkzWooUhNRYwxatHM;
  int32_t rlJpkuWHEJHJIaSZvRuqDqpSvzVd;
  int32_t AkuXuJxrQRCKULSLWiBghHhHnJb;
  int32_t sqNxoOHuwGowWSgDKwdSnKDwGUj;
  int32_t DFBkJeLtofbmeFDVwsChZJPNylK;
  int32_t SlHAheWnLESQNZNbmvHbMrpPugd;
  int32_t LUaPgyjIsthyunywOKHooiAYbzz;
  int32_t dwMwCzYDxvBxlsPBqnwyZkMzwwS;
  int32_t zIVvMcPfuzSnvLqDnpirvasfHnL;
  int32_t cKYBsBbpHHgAcnfhgcxjjXgXZUZ;
  int32_t PcltYCDURdNelcRaDVOFNQNFMBc;
  int32_t fIrWsHypxGvROexIpDTvXnXXCuh;
  int32_t ltmWXaVyZjMOJQNjagNgKjbxCqQ;
  int32_t tVbTnVsAhlHYIeGZPRKGfmUXFLdW;
  int32_t MWTtrnyuMNsmZDDrQqJNvOQMccK;
  int32_t yEEnRqPXAYFNnijOrHDUIJnnFbq;
  int32_t rZUGXuCASXacUAWvVLszlibQfCne;
  int32_t VzFbLndUqSqjyzNIsXdNvAyviDm;
  int32_t kKCFDZRiukqezlFnFccZTXOtZib;
  int32_t SptIFyaTUfGoXhhnImAVfqyJAvJ;
  int32_t khIEqFuxeKYqILsjuLcqIgWgLSM;
  int32_t kUHhWRjKrwvyWFGUxMXpFvFceUz;
  int32_t coNhutwhcmhAPkoHtyWPViPWsHC;
  int32_t TfOUlOeDGgIURAsMnYpwgYRmecvX;
  int32_t DyqNiXBDdEEOcZbEjNQZjsixEof;
  int32_t txfPnHVyIkgjSzNZIRCxfKjrMyM;
  int32_t fefjJRxKxCmvXcgnUYTLAJWQCpN;
  int32_t yrCexOHNGMFqSHAMWZgSZiRzrSw;
  int32_t JqtcQgymbLgyEmvRVUFQcAWPfky;
  int32_t ZrrHmyceoiHUkEzCyAEuSRXhPNS;
  int32_t wVuJPgKaUnzjiDCOCrmINnipMfU;
  int32_t yKFmbsiVadyvToGUKTrYKDQmEEe;
  int32_t jNCEYLsuCaadwbTbOrRmcYuIHbt;
  int32_t qmgaEDCDuFqJRHOULCqwZNhfQYi;
  int32_t nDLtmkLmjyKGSHjYPITapnicXpY;
  int32_t PmbpnoXIapLMpNnhxUxPOqqEzNi;
  int32_t eTdVzuAgdOKVexKGJoZTsBYSBEl;
  int32_t XYONYJNdIaJOyRvwHCCuhLGjjch;
  int32_t JZwKndrLqqaQcJPacVTbpztxoJz;
  int32_t iWtZhVZTFouMzaldjTMvCmpAeOcg;
  int32_t ezevfRljJrqQYllxkxoQznrvGIVI;
  int32_t JkcGYcIdZtGyvAqllfODVsGuAnIX;
  int32_t ICsydWeiHHJTOBwJKUApFzzFscd;
  int32_t jAxTGZkNtzhsqSqomdsnjWgnxiD;
  int32_t IzseWvSuhphbxepAPLdLmzVUkITF;
  int32_t CTiwDyfdgTiBzoenLGezpQYCyqL;
  int32_t KGuACivvjvCBsJTzTHUZfCArwGCl;
  int32_t fbAxpOWZoNFszciaGIsUrbVCwi;
  int32_t vcWSfVPiSzWCVodNWhKYuCDfCQE;
  int32_t vViUsVWEVsuVkyjHtxhkkiRPOiE;
  int32_t wVMdjISJOMGesiiHFKyLDQIXtMao;
  int32_t ACnBaoJiwcrjKkallWaEmEEhlTl;
  int32_t sEzpYTBstmezZcknVnmTrEFiFJP;
  int32_t lVgwhJOYHrSLJmRNRgChqymZdPA;
  int32_t zTmPeLMJZAQIOgPlygTCEaHUdTm;
  int32_t dCHZQZNjzIesZVJlAiFkQMobXrA;
  int32_t EZTuMUkhBUlEriyHGjyFvEjOkZP;
  int32_t UrpQexUEHzDgLelWKDrzSARQUkrW;
  int32_t wJYVjzGhzdxezTIxRJrPwkEOHNk;
  int32_t YZACYMIKshulCVaHnqEclMwUGdr;
  int32_t nIgMXoqEPCPJnsMCeLyBDMWBAk;
  int32_t JSUrppirwrpWzSLFKFvHnCnjTA;
  int32_t PnjAhAFKoWYyjRWmbBHoZdODkfXy;
  int32_t mzgZTTSBBRiVXtJhFJCURHyRPZF;
  int32_t IeepwqqoRDAmfXZEQiGqJkOdeXc;
  int32_t GzkihvBjHIwNyjxZrgTunQnzPsZ;
  int32_t jWOSQTfGzeOSXAHlSwnUspAJZRY;
  int32_t NWKwqHpnfuFPXgtebFklfApRFRv;
  int32_t JhibruudTKqqDzmoobaTZlWqqdO;
  int32_t UFZTYSjnVQTkbIQUVLjgFJrxeir;
  int32_t fCXcXznrETTCpywHXcNmVaAUTEE;
  int32_t rVanYZBBBGRdkDCunwukrhPDKMN;
  int32_t UWlZPSCZnBbimOOaWHZkqgAMzhj;
  uint32_t cJgeDuufvZcqTCComhYhMLBusaQn;
  uint32_t zBMjlRiaQyQSdJVusGZjzMyPeMGd;
  uint32_t UmXbzrDTtfkuVveUhxlCGUqapGdg;
  uint32_t WddJZdvciuLAHGmtTTJwOPDvAkKJ;
  uint32_t rDmYhdypipfMMZvnsgZtIDwrqCK;
};

struct __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppVtbl {
  VirtualInvokeData _0_Equals;
  VirtualInvokeData _1_Finalize;
  VirtualInvokeData _2_GetHashCode;
  VirtualInvokeData _3_ToString;
};

struct __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppClass {
  Il2CppClass_1 _1;
  __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppStaticFields* pStaticFields;
  Il2CppClass_2 _2;
  __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppVtbl vtbl;
};

class YuxJLrkiDObHxOhKjSrycgVJFka {
  static constexpr uint64_t                     _rvaClassInstance     = 0x3C6CF80;
  static inline    __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppClass* _pStaticClassInstance = nullptr;

public:
// Static class getter:
  static inline __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppClass* GetStaticClassInstance() {
    while (!_pStaticClassInstance) {
      Sleep(100);
      auto* ppClassInstance = (__YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppClass**)Helpers::Memory::GetInstance().MakeAbsolute(_rvaClassInstance);
      if (ppClassInstance)
        _pStaticClassInstance = *ppClassInstance;
    }
    return _pStaticClassInstance;
  }

  // Il2Cpp fields:
  __YuxJLrkiDObHxOhKjSrycgVJFka_Il2CppClass* __pClassInstance;
  void* __monitor;

  // Static fields:
  static inline __CppStaticProperty<intptr_t> PBrErMrModRYdhnEAQaoEMtkCptA = __CppStaticProperty<intptr_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->PBrErMrModRYdhnEAQaoEMtkCptA; }
  );
  static inline __CppStaticProperty<int32_t> GiNOobmnHEQEiywTrvQxleszgIE = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->GiNOobmnHEQEiywTrvQxleszgIE; }
  );
  static inline __CppStaticProperty<int32_t> HEqihPDMKItxDioIeQCJchzCjmvO = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->HEqihPDMKItxDioIeQCJchzCjmvO; }
  );
  static inline __CppStaticProperty<int32_t> MsCsKBxsjMeIoEYSdGnsCpJnGsX = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->MsCsKBxsjMeIoEYSdGnsCpJnGsX; }
  );
  static inline __CppStaticProperty<int32_t> dkBwxlrTkpLGnxxnJlTmMzonWRF = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->dkBwxlrTkpLGnxxnJlTmMzonWRF; }
  );
  static inline __CppStaticProperty<int32_t> HHcTtKdKWQxSYkZLdsHIzbkkEZV = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->HHcTtKdKWQxSYkZLdsHIzbkkEZV; }
  );
  static inline __CppStaticProperty<int32_t> tNovdfDIKoDwrygtFmLPupgyplT = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->tNovdfDIKoDwrygtFmLPupgyplT; }
  );
  static inline __CppStaticProperty<int32_t> pYesNWphMpiwCDgbEKpoeqtEHomi = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->pYesNWphMpiwCDgbEKpoeqtEHomi; }
  );
  static inline __CppStaticProperty<int32_t> tjEmHreRROmedejbUEiMwnuVgEA = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->tjEmHreRROmedejbUEiMwnuVgEA; }
  );
  static inline __CppStaticProperty<int32_t> SmpAVfbIiUhiwxFyxhFzAUYEkGmL = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->SmpAVfbIiUhiwxFyxhFzAUYEkGmL; }
  );
  static inline __CppStaticProperty<int32_t> RhpJkRZnELgAQNrDyAWLsiNyxLt = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->RhpJkRZnELgAQNrDyAWLsiNyxLt; }
  );
  static inline __CppStaticProperty<int32_t> uSQoYuqHeXSkzWooUhNRYwxatHM = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->uSQoYuqHeXSkzWooUhNRYwxatHM; }
  );
  static inline __CppStaticProperty<int32_t> rlJpkuWHEJHJIaSZvRuqDqpSvzVd = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->rlJpkuWHEJHJIaSZvRuqDqpSvzVd; }
  );
  static inline __CppStaticProperty<int32_t> AkuXuJxrQRCKULSLWiBghHhHnJb = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->AkuXuJxrQRCKULSLWiBghHhHnJb; }
  );
  static inline __CppStaticProperty<int32_t> sqNxoOHuwGowWSgDKwdSnKDwGUj = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->sqNxoOHuwGowWSgDKwdSnKDwGUj; }
  );
  static inline __CppStaticProperty<int32_t> DFBkJeLtofbmeFDVwsChZJPNylK = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->DFBkJeLtofbmeFDVwsChZJPNylK; }
  );
  static inline __CppStaticProperty<int32_t> SlHAheWnLESQNZNbmvHbMrpPugd = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->SlHAheWnLESQNZNbmvHbMrpPugd; }
  );
  static inline __CppStaticProperty<int32_t> LUaPgyjIsthyunywOKHooiAYbzz = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->LUaPgyjIsthyunywOKHooiAYbzz; }
  );
  static inline __CppStaticProperty<int32_t> dwMwCzYDxvBxlsPBqnwyZkMzwwS = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->dwMwCzYDxvBxlsPBqnwyZkMzwwS; }
  );
  static inline __CppStaticProperty<int32_t> zIVvMcPfuzSnvLqDnpirvasfHnL = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->zIVvMcPfuzSnvLqDnpirvasfHnL; }
  );
  static inline __CppStaticProperty<int32_t> cKYBsBbpHHgAcnfhgcxjjXgXZUZ = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->cKYBsBbpHHgAcnfhgcxjjXgXZUZ; }
  );
  static inline __CppStaticProperty<int32_t> PcltYCDURdNelcRaDVOFNQNFMBc = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->PcltYCDURdNelcRaDVOFNQNFMBc; }
  );
  static inline __CppStaticProperty<int32_t> fIrWsHypxGvROexIpDTvXnXXCuh = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->fIrWsHypxGvROexIpDTvXnXXCuh; }
  );
  static inline __CppStaticProperty<int32_t> ltmWXaVyZjMOJQNjagNgKjbxCqQ = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->ltmWXaVyZjMOJQNjagNgKjbxCqQ; }
  );
  static inline __CppStaticProperty<int32_t> tVbTnVsAhlHYIeGZPRKGfmUXFLdW = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->tVbTnVsAhlHYIeGZPRKGfmUXFLdW; }
  );
  static inline __CppStaticProperty<int32_t> MWTtrnyuMNsmZDDrQqJNvOQMccK = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->MWTtrnyuMNsmZDDrQqJNvOQMccK; }
  );
  static inline __CppStaticProperty<int32_t> yEEnRqPXAYFNnijOrHDUIJnnFbq = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->yEEnRqPXAYFNnijOrHDUIJnnFbq; }
  );
  static inline __CppStaticProperty<int32_t> rZUGXuCASXacUAWvVLszlibQfCne = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->rZUGXuCASXacUAWvVLszlibQfCne; }
  );
  static inline __CppStaticProperty<int32_t> VzFbLndUqSqjyzNIsXdNvAyviDm = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->VzFbLndUqSqjyzNIsXdNvAyviDm; }
  );
  static inline __CppStaticProperty<int32_t> kKCFDZRiukqezlFnFccZTXOtZib = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->kKCFDZRiukqezlFnFccZTXOtZib; }
  );
  static inline __CppStaticProperty<int32_t> SptIFyaTUfGoXhhnImAVfqyJAvJ = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->SptIFyaTUfGoXhhnImAVfqyJAvJ; }
  );
  static inline __CppStaticProperty<int32_t> khIEqFuxeKYqILsjuLcqIgWgLSM = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->khIEqFuxeKYqILsjuLcqIgWgLSM; }
  );
  static inline __CppStaticProperty<int32_t> kUHhWRjKrwvyWFGUxMXpFvFceUz = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->kUHhWRjKrwvyWFGUxMXpFvFceUz; }
  );
  static inline __CppStaticProperty<int32_t> coNhutwhcmhAPkoHtyWPViPWsHC = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->coNhutwhcmhAPkoHtyWPViPWsHC; }
  );
  static inline __CppStaticProperty<int32_t> TfOUlOeDGgIURAsMnYpwgYRmecvX = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->TfOUlOeDGgIURAsMnYpwgYRmecvX; }
  );
  static inline __CppStaticProperty<int32_t> DyqNiXBDdEEOcZbEjNQZjsixEof = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->DyqNiXBDdEEOcZbEjNQZjsixEof; }
  );
  static inline __CppStaticProperty<int32_t> txfPnHVyIkgjSzNZIRCxfKjrMyM = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->txfPnHVyIkgjSzNZIRCxfKjrMyM; }
  );
  static inline __CppStaticProperty<int32_t> fefjJRxKxCmvXcgnUYTLAJWQCpN = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->fefjJRxKxCmvXcgnUYTLAJWQCpN; }
  );
  static inline __CppStaticProperty<int32_t> yrCexOHNGMFqSHAMWZgSZiRzrSw = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->yrCexOHNGMFqSHAMWZgSZiRzrSw; }
  );
  static inline __CppStaticProperty<int32_t> JqtcQgymbLgyEmvRVUFQcAWPfky = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->JqtcQgymbLgyEmvRVUFQcAWPfky; }
  );
  static inline __CppStaticProperty<int32_t> ZrrHmyceoiHUkEzCyAEuSRXhPNS = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->ZrrHmyceoiHUkEzCyAEuSRXhPNS; }
  );
  static inline __CppStaticProperty<int32_t> wVuJPgKaUnzjiDCOCrmINnipMfU = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->wVuJPgKaUnzjiDCOCrmINnipMfU; }
  );
  static inline __CppStaticProperty<int32_t> yKFmbsiVadyvToGUKTrYKDQmEEe = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->yKFmbsiVadyvToGUKTrYKDQmEEe; }
  );
  static inline __CppStaticProperty<int32_t> jNCEYLsuCaadwbTbOrRmcYuIHbt = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->jNCEYLsuCaadwbTbOrRmcYuIHbt; }
  );
  static inline __CppStaticProperty<int32_t> qmgaEDCDuFqJRHOULCqwZNhfQYi = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->qmgaEDCDuFqJRHOULCqwZNhfQYi; }
  );
  static inline __CppStaticProperty<int32_t> nDLtmkLmjyKGSHjYPITapnicXpY = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->nDLtmkLmjyKGSHjYPITapnicXpY; }
  );
  static inline __CppStaticProperty<int32_t> PmbpnoXIapLMpNnhxUxPOqqEzNi = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->PmbpnoXIapLMpNnhxUxPOqqEzNi; }
  );
  static inline __CppStaticProperty<int32_t> eTdVzuAgdOKVexKGJoZTsBYSBEl = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->eTdVzuAgdOKVexKGJoZTsBYSBEl; }
  );
  static inline __CppStaticProperty<int32_t> XYONYJNdIaJOyRvwHCCuhLGjjch = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->XYONYJNdIaJOyRvwHCCuhLGjjch; }
  );
  static inline __CppStaticProperty<int32_t> JZwKndrLqqaQcJPacVTbpztxoJz = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->JZwKndrLqqaQcJPacVTbpztxoJz; }
  );
  static inline __CppStaticProperty<int32_t> iWtZhVZTFouMzaldjTMvCmpAeOcg = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->iWtZhVZTFouMzaldjTMvCmpAeOcg; }
  );
  static inline __CppStaticProperty<int32_t> ezevfRljJrqQYllxkxoQznrvGIVI = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->ezevfRljJrqQYllxkxoQznrvGIVI; }
  );
  static inline __CppStaticProperty<int32_t> JkcGYcIdZtGyvAqllfODVsGuAnIX = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->JkcGYcIdZtGyvAqllfODVsGuAnIX; }
  );
  static inline __CppStaticProperty<int32_t> ICsydWeiHHJTOBwJKUApFzzFscd = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->ICsydWeiHHJTOBwJKUApFzzFscd; }
  );
  static inline __CppStaticProperty<int32_t> jAxTGZkNtzhsqSqomdsnjWgnxiD = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->jAxTGZkNtzhsqSqomdsnjWgnxiD; }
  );
  static inline __CppStaticProperty<int32_t> IzseWvSuhphbxepAPLdLmzVUkITF = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->IzseWvSuhphbxepAPLdLmzVUkITF; }
  );
  static inline __CppStaticProperty<int32_t> CTiwDyfdgTiBzoenLGezpQYCyqL = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->CTiwDyfdgTiBzoenLGezpQYCyqL; }
  );
  static inline __CppStaticProperty<int32_t> KGuACivvjvCBsJTzTHUZfCArwGCl = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->KGuACivvjvCBsJTzTHUZfCArwGCl; }
  );
  static inline __CppStaticProperty<int32_t> fbAxpOWZoNFszciaGIsUrbVCwi = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->fbAxpOWZoNFszciaGIsUrbVCwi; }
  );
  static inline __CppStaticProperty<int32_t> vcWSfVPiSzWCVodNWhKYuCDfCQE = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->vcWSfVPiSzWCVodNWhKYuCDfCQE; }
  );
  static inline __CppStaticProperty<int32_t> vViUsVWEVsuVkyjHtxhkkiRPOiE = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->vViUsVWEVsuVkyjHtxhkkiRPOiE; }
  );
  static inline __CppStaticProperty<int32_t> wVMdjISJOMGesiiHFKyLDQIXtMao = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->wVMdjISJOMGesiiHFKyLDQIXtMao; }
  );
  static inline __CppStaticProperty<int32_t> ACnBaoJiwcrjKkallWaEmEEhlTl = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->ACnBaoJiwcrjKkallWaEmEEhlTl; }
  );
  static inline __CppStaticProperty<int32_t> sEzpYTBstmezZcknVnmTrEFiFJP = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->sEzpYTBstmezZcknVnmTrEFiFJP; }
  );
  static inline __CppStaticProperty<int32_t> lVgwhJOYHrSLJmRNRgChqymZdPA = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->lVgwhJOYHrSLJmRNRgChqymZdPA; }
  );
  static inline __CppStaticProperty<int32_t> zTmPeLMJZAQIOgPlygTCEaHUdTm = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->zTmPeLMJZAQIOgPlygTCEaHUdTm; }
  );
  static inline __CppStaticProperty<int32_t> dCHZQZNjzIesZVJlAiFkQMobXrA = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->dCHZQZNjzIesZVJlAiFkQMobXrA; }
  );
  static inline __CppStaticProperty<int32_t> EZTuMUkhBUlEriyHGjyFvEjOkZP = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->EZTuMUkhBUlEriyHGjyFvEjOkZP; }
  );
  static inline __CppStaticProperty<int32_t> UrpQexUEHzDgLelWKDrzSARQUkrW = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->UrpQexUEHzDgLelWKDrzSARQUkrW; }
  );
  static inline __CppStaticProperty<int32_t> wJYVjzGhzdxezTIxRJrPwkEOHNk = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->wJYVjzGhzdxezTIxRJrPwkEOHNk; }
  );
  static inline __CppStaticProperty<int32_t> YZACYMIKshulCVaHnqEclMwUGdr = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->YZACYMIKshulCVaHnqEclMwUGdr; }
  );
  static inline __CppStaticProperty<int32_t> nIgMXoqEPCPJnsMCeLyBDMWBAk = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->nIgMXoqEPCPJnsMCeLyBDMWBAk; }
  );
  static inline __CppStaticProperty<int32_t> JSUrppirwrpWzSLFKFvHnCnjTA = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->JSUrppirwrpWzSLFKFvHnCnjTA; }
  );
  static inline __CppStaticProperty<int32_t> PnjAhAFKoWYyjRWmbBHoZdODkfXy = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->PnjAhAFKoWYyjRWmbBHoZdODkfXy; }
  );
  static inline __CppStaticProperty<int32_t> mzgZTTSBBRiVXtJhFJCURHyRPZF = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->mzgZTTSBBRiVXtJhFJCURHyRPZF; }
  );
  static inline __CppStaticProperty<int32_t> IeepwqqoRDAmfXZEQiGqJkOdeXc = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->IeepwqqoRDAmfXZEQiGqJkOdeXc; }
  );
  static inline __CppStaticProperty<int32_t> GzkihvBjHIwNyjxZrgTunQnzPsZ = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->GzkihvBjHIwNyjxZrgTunQnzPsZ; }
  );
  static inline __CppStaticProperty<int32_t> jWOSQTfGzeOSXAHlSwnUspAJZRY = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->jWOSQTfGzeOSXAHlSwnUspAJZRY; }
  );
  static inline __CppStaticProperty<int32_t> NWKwqHpnfuFPXgtebFklfApRFRv = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->NWKwqHpnfuFPXgtebFklfApRFRv; }
  );
  static inline __CppStaticProperty<int32_t> JhibruudTKqqDzmoobaTZlWqqdO = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->JhibruudTKqqDzmoobaTZlWqqdO; }
  );
  static inline __CppStaticProperty<int32_t> UFZTYSjnVQTkbIQUVLjgFJrxeir = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->UFZTYSjnVQTkbIQUVLjgFJrxeir; }
  );
  static inline __CppStaticProperty<int32_t> fCXcXznrETTCpywHXcNmVaAUTEE = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->fCXcXznrETTCpywHXcNmVaAUTEE; }
  );
  static inline __CppStaticProperty<int32_t> rVanYZBBBGRdkDCunwukrhPDKMN = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->rVanYZBBBGRdkDCunwukrhPDKMN; }
  );
  static inline __CppStaticProperty<int32_t> UWlZPSCZnBbimOOaWHZkqgAMzhj = __CppStaticProperty<int32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->UWlZPSCZnBbimOOaWHZkqgAMzhj; }
  );
  static inline __CppStaticProperty<uint32_t> cJgeDuufvZcqTCComhYhMLBusaQn = __CppStaticProperty<uint32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->cJgeDuufvZcqTCComhYhMLBusaQn; }
  );
  static inline __CppStaticProperty<uint32_t> zBMjlRiaQyQSdJVusGZjzMyPeMGd = __CppStaticProperty<uint32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->zBMjlRiaQyQSdJVusGZjzMyPeMGd; }
  );
  static inline __CppStaticProperty<uint32_t> UmXbzrDTtfkuVveUhxlCGUqapGdg = __CppStaticProperty<uint32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->UmXbzrDTtfkuVveUhxlCGUqapGdg; }
  );
  static inline __CppStaticProperty<uint32_t> WddJZdvciuLAHGmtTTJwOPDvAkKJ = __CppStaticProperty<uint32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->WddJZdvciuLAHGmtTTJwOPDvAkKJ; }
  );
  static inline __CppStaticProperty<uint32_t> rDmYhdypipfMMZvnsgZtIDwrqCK = __CppStaticProperty<uint32_t>(
   []() { return &GetStaticClassInstance()->pStaticFields->rDmYhdypipfMMZvnsgZtIDwrqCK; }
  );

  // Static methods:
  static inline void ::cctor() {
    reinterpret_cast<void(__fastcall*)()>(Helpers::Memory::GetInstance().MakeAbsolute(0x3D8BB0))();
  }
};
}